### ISSUE TITLE
Fikse et par Ikonenavn

### ISSUE THREAD

**Issue by ivoiv** [navikt/Designsystemet#1247]
## Beskriv forespørselen

Chevron ikonene synes jeg har altfor spesifikke navn.
Hvorfor heter venstre chevron "Back"? Bør i min mening hete ChevronLeft
Det kan brukes til mye annet enn en tilbakeknapp. Samme om de andre.

Samme med Helptext ikonet, bør hete bare Help, det er ikke noe tekst i det...

Det er heldigvis bare noen få, for resten synes jeg er ganske greit.

## Hvilken funksjon vil dette har for bruker?
Enklere å finne passende ikoner.

## Eksempler/Tilleggsinformasjon 
![image](https://user-images.githubusercontent.com/11502345/133429104-427ad4fe-86b5-40b3-93af-388e16151d95.png)

**Comment by ivoiv** [comment]
Tenkte meg faktisk litt om.

**Comment by KenAJoh** [comment]
Vi sier oss ikke uenig i forslaget og blir å ta det opp i teamet for å finne ut hvordan vi velger å navngi ikonene. 

En forbedring vi tenker å gjøre er å "tagge" ikonene på design.nav.no slik at eks søket "right" vil gi eks arrow-right og next.
