### ISSUE TITLE
[BUG] Disable Tertiary button har bakgrunnsfarge

### ISSUE THREAD

**Issue by ivoiv** [navikt/Designsystemet#1261]
## Hvilken av tjenestene våre gjelder det?

- [X] `Komponenter`
- [ ] `Stiler`
- [ ] `Ikoner`
- [ ] `Annet`

## Beskriv feilen/problemet

Button med variant="tertiary" ser slik ut
![image](https://user-images.githubusercontent.com/11502345/134014740-3268a0c4-b5dd-4f19-8500-f31701481ee5.png)

Når den er disabled ser den slik ut
![image](https://user-images.githubusercontent.com/11502345/134015393-34b4aa52-16d7-4ac2-8815-2fadf728e673.png)

## Forventet oppførsel
Nullstill blir bare grå tekst når den er disabled

**Comment by andnorda** [comment]
Dette er faktisk korrekt etter designet vårt, men jeg skal spille det inn til designerene, så kan de vurdere om dette er en endring vi ønsker å gjøre
