### ISSUE TITLE
Endre fokushåndtering i modaler

### ISSUE THREAD

**Issue by AndreasJacobsen** [navikt/Designsystemet#1358]
## Hvilken av tjenestene våre gjelder det?
Modalkomponent - nav-frontend-modal

- [x] `Komponenter`
- [ ] `Stiler`
- [ ] `Ikoner`
- [ ] `Annet`

## Beskriv feilen/problemet
Modalkomponenten setter fokus på modalelementet når det åpnes istedenfor innholdet. Se [Modal.accessibility.mdx](https://github.com/navikt/nav-frontend-moduler/blob/master/packages/nav-frontend-modal/md/Modal.accessibility.mdx) for dokumentasjon på hvordan dagens oppførsel skal fungere. Istedenfor å sette fokus på første visuelt tydelige element settes fokus direkte på modalen.
Suksesskriterie 3 i WCAG 2.4.3 passer med hvordan [Modal.accessibility.mdx](https://github.com/navikt/nav-frontend-moduler/blob/master/packages/nav-frontend-modal/md/Modal.accessibility.mdx) beskriver at fokus skal settes.
> A Web page implements modal dialogs via scripting. When the trigger button is activated, a dialog opens and focus is set to the first interactive element in the dialog. As long as the dialog is open, focus is limited to the elements of the dialog. When the dialog is dismissed, focus returns to the button or the element following the button.

[w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-focus-order](https://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-focus-order.html)

Success Criterion er eksempler på hvordan kriterier kan oppnås, men andre løsninger kan også være gyldige. Jeg mener at løsningen WCAG viser ikke er god nok. Det første elementet er gjerne lukkeknappen, jeg vil ikke høre "Lukk" som det første som kommer opper opp når jeg åpner ett modalvindu med en skjermleser. 

Istedenfor å sette fokus til første element, slike dokumentasjonen sier, eller sette fokus direkte på modalvinduet bør fokus settes til starten av hovedinnholdet.

> Beskriv hva slags problem(er) som oppstår
Med testkomponent på [design.nav.no/designsystem/components/modal](https://design.nav.no/designsystem/components/modal) settes fokus med VoiceOver direkte på modalvinduet istedenfor innholdet.
![VoiceOver med fokus på modalvindu istedenfor modalinnhold](https://user-images.githubusercontent.com/8527173/145598011-d983ab88-d90b-4854-8cdc-e1b9b99ddf6b.png)
For å komme til innholdet i modalen må jeg bruke hurtigtastene Kontroll-Tilvalg-Skift-Pil ned
![VoiceOver som viser tastatursnarviene for å navigere til innholdet](https://user-images.githubusercontent.com/8527173/145598331-670804f5-882b-40ed-9797-ef37ee51bb8a.png)

> Hva forventet du skulle oppstå?
Fokus direkte til hovedinnholdet av modalen, gjerne en overskrift.

> Hva skjedde istedenfor?
Fokus til starten av modalvinduet, måtte bruke snarvei med mange knapper for å navigere til elementet

## Steg for å reprodusere problemet

1. Gå til https://design.nav.no/designsystem/components/modal
2. Start en skjermleser eller vis fokus med CSS
3. Åpne modalvinduet og se hvor fokus lander

REDIGERT:
Se eksempel på Modal på [adrianroselli.com/2020/10/dialog-focus-in-screen-readers](https://adrianroselli.com/2020/10/dialog-focus-in-screen-readers.html )

**Comment by KenAJoh** [comment]
Takk for henvendelsen! Har videresendt issuet til teamet.

**Comment by sarahbrodwall** [comment]
Hei, Andreas,
Jeg har snakket litt med noen av våre native skjermleserbrukere/uu-eksperter og uu-utviklere for å avklare situasjonen. Siden komponenten brukes i mange forskjellige kontekster og innholdet kan variere mye, er det tryggeste valget for en designsystemkomponent å sette initialt fokus til selve vinduet, som det er i dag.  Fokusrekkefølge blir logisk og suksesskriteriet blir oppfylt, selv om løsningen ikke matcher eksempel 3 på «Understanding SC 2.4.3»-siden. Jeg har også testet i NVDA—den leser gjennom modalen uten behov for spesielle piltaster.  Våre uu-eksperter som bruker VO opplevde ikke at tastaturkombinasjonen var problematisk eller uvanlig.
Vi kommer ikke til å endre defaultoppførselen eller koden i komponenten, men jeg skal oppdatere teksten med mer nyansert råd om fokushåndtering basert på innhold og kontekst.
