### ISSUE TITLE
[BUG] border-collapse på Table skaper tykkere borders på 125% zoom i Chrome

### ISSUE THREAD

**Issue by karl-run** [navikt/Designsystemet#1426]
- [ ] `Komponenter`
- [x] `Stiler`
- [ ] `Ikoner`
- [ ] `Annet`

## Beskriv feilen/problemet

Kanskje litt vel snever bug, men har en `<Table>`, uten custom styling, på 125% zoom i Google Chrome (98.0.4758.80) blir tykkelsen på border på `<Table.DataCell>` varierende mellom radene. Skjer også på 150% og 175% zoom, men ikke 200%. Testet på både Linux og Windows 11. Dette er på vanlig DPI skjerm. Vet ikke om det skjer på HiDPI Windows/OSX.

![image](https://user-images.githubusercontent.com/1507032/154337682-1b18c166-401a-4af6-9227-10b7cfb29660.png)

På samme zoom-nivå i Firefox:

![image](https://user-images.githubusercontent.com/1507032/154337731-d15fb409-4e50-46c9-8c41-1dc3cd932e64.png)

## Steg for å reprodusere problemet

1. Lag en tabell
2. Ha minst 3-4 rader. 
3. Set Chrome til 125% zoom.

## Eksempel/Tilleggsinformasjon

Med `border-collapse: inherit` så blir tykkelsen bra, men da får man små gaps mellom hver celle.

![image](https://user-images.githubusercontent.com/1507032/154338537-93476599-fd4d-401a-9e10-a9d488400620.png)

Er ikke rå nok på HTML-tabeller til å vite hvordan man skulle løst noe sånt. :smiling_face_with_tear: 

```
 Hvis mulig, legg gjerne til kode her, evt lenke til kode i repo
```

**Comment by andnorda** [comment]
Det ser ut som `border-collapse: separate; border-spacing: 0;` kan være en fix, men det gjør at det blir stress om noen ønsker seg vertikale borders.

**Comment by andnorda** [comment]
Lurer på om det er samme som denne: https://bugs.chromium.org/p/chromium/issues/detail?id=1280894

**Comment by andnorda** [comment]
Jeg har en mistanke om at denne blir en wontfix. soz

**Comment by karl-run** [comment]
Kan være med å dele den mistanken. :smile: Hva er vel bedre enn en browser-spesifikk weird edge case CSS bug?

**Comment by andnorda** [comment]
Hjelper det litt om jeg sier at jeg deler smerten din? :kangery:
