### ISSUE TITLE
UU-bug: innholdet i komponentene våre skal være på forståelig norsk

### ISSUE THREAD

**Issue by kariandersen** [navikt/Designsystemet#1441]
## Panel
https://design.nav.no/designsystem/side/panel

- [x ] `Komponenter`
- [ ] `Stiler`
- [ ] `Ikoner`
- [ ] `Annet`

Endring:
Vi må endre innholdet i denne komponenten slik at den er på forståelig norsk.
Kan vi gjenbruke teksten vi bruker i [GuidePanel > ](https://design.nav.no/designsystem/side/guidepanel)?

Saksbehandlingstiden varierer fra kommune til kommune. Hvis det går mer enn X måneder siden du søkte, skal du få brev om at saksbehandlingstiden er forlenget.

![image](https://user-images.githubusercontent.com/40289910/155524071-e847c005-50cd-49c0-af5c-c20550c5ad16.png)

@navikt/uu-teamet

**Comment by KenAJoh** [comment]
Panel komponenten har nå oppdatert dokumentasjon!
