### ISSUE TITLE
[BUG] Frontend moduler fungerer ikke med React 18

### ISSUE THREAD

**Issue by w3bdesign** [navikt/Designsystemet#1479]
## Hvilken av tjenestene våre gjelder det?

 @navikt/ds-react@0.17.19

- [x]  `Komponenter`

## Beskriv feilen/problemet

Forsøker å installere @navikt/ds-react@0.17.19 og får følgende feilmelding:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: nav-jobs@1.0.96
npm ERR! Found: react@18.0.0
npm ERR! node_modules/react
npm ERR!   react@"18.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^17.0.0" from @navikt/ds-react@0.17.19
npm ERR! node_modules/@navikt/ds-react
npm ERR!   @navikt/ds-react@"^0.17.19" from the root project
```

## Steg for å reprodusere problemet

Installer @navikt/ds-react@0.17.19 på en fersk installasjon av React 18

## Eksempel/Tilleggsinformasjon

![bilde](https://user-images.githubusercontent.com/45217974/161343579-ff66a231-245b-45ae-afd0-2b17e49ce74c.png)
```

**Comment by w3bdesign** [comment]
https://github.com/navikt/nav-frontend-moduler/pull/1480

**Comment by KenAJoh** [comment]
Hei, har laget en PR med alle nødvendige endringer her #1480
