### ISSUE TITLE
[BUG] nye Tooltip kræsjer når den SSRes

### ISSUE THREAD

**Issue by karl-run** [navikt/Designsystemet#1494]
## Hvilken av tjenestene våre gjelder det?

- [x] `Komponenter`
- [ ] `Stiler`
- [ ] `Ikoner`
- [ ] `Annet`

## Beskriv feilen/problemet

Når `<Tooltip>` fra react-ds eksisterer i treet under SSRing møter man en `document does not exist`-feil.

![image](https://user-images.githubusercontent.com/1507032/162192769-5e5d5271-92c3-4889-85c2-6fe50ad9adf8.png)

## Steg for å reprodusere problemet

1. Ha en Tooltip
2. SSR den

**Comment by KenAJoh** [comment]
Første fix nevnt på slack fikset bare 1/2 problemer, men denne #1496 fikser forhåpentligvis SSR for Tooltip
Kan oppdatere til disse versjonene å teste:
- @navikt/ds-react@0.17.24
 - @navikt/ds-react-internal@0.12.26
