### ISSUE TITLE
[BUG] uu: checkbox har parsingfeil

### ISSUE THREAD

**Issue by sarahbrodwall** [navikt/Designsystemet#1605]
`label` tillatter bare phrasing-content, men vår checkbox-label har div'er nøstet i seg. Endre disse til spans så er alt i orden.

**Comment by KenAJoh** [comment]
Er det en checkbox-story vi gjør dette i, eller er det noe feil med selve komponenten?

**Comment by sarahbrodwall** [comment]
Det vises slik i demoen på Aksel-siden også, så kanskje begge?

**Comment by KenAJoh** [comment]
Ah skjønner nå, kan få endret til `<span/>`. Dette gjelder vel også Radio da tror jeg
