### ISSUE TITLE
[BUG] Select expand-knapp usynlig ved bruk i Intern Header

### ISSUE THREAD

**Issue by ivoiv** [navikt/Designsystemet#1614]
## Hvilken av tjenestene våre gjelder det?

- [X] `Komponenter`
- [X] `Stiler`
- [ ] `Ikoner`
- [ ] `Annet`

## Beskriv feilen/problemet

Når man bruker Select komponenten i Intern Header slår denne stilen fra baseline.css inn
```
    Inherited from header.navdsi-header
    [data-theme="dark"] {
        color: var(--navds-semantic-color-text-inverted); //rgba(255, 255, 255, 1);
    }
```

Dette gjør expand-ikonet hvit og siden Select har en hvit bakgrunn, blir expand-ikonet i praksis usynlig.

## Eksempel/Tilleggsinformasjon

![image](https://user-images.githubusercontent.com/11502345/183702426-bc3ab966-20ef-4135-ae11-256528ac1f74.png)

**Comment by KenAJoh** [comment]
Er fikset i @navikt/ds-css v0.18.29
