### ISSUE TITLE
Stepper - Mulighet for lineær stepper

### ISSUE THREAD

**Issue by hestad** [navikt/Designsystemet#1625]
Vi i team supplerende stønad bruker per i dag `StepIndicator` fra `step-indicator` i søknaden vår. Den har mulighet for å fullføre søknaden lineært (i rekkefølge) ved å disable senere steg, men dette er ikke mulig med den nye `Stepper`en. Ref. https://material.angular.io/components/stepper/overview#linear-stepper

**Comment by KenAJoh** [comment]
Takk, tar det opp med teamet så skal vi få sett på det!

**Comment by KenAJoh** [comment]
@hestad Hei, vi tester litt løsninger nå og kan se ut som vi går for disse. Vil dette (spesielt eksempel 3) være en fungerende løsning for dere? Hvert steg har da en "completed" og "interactive"-prop slik at man selv bygger flyten.
- https://5f801fb2aea7820022de2936-fpksfyljdt.chromatic.com/iframe.html?args=&id=ds-react-stepper--display-only&viewMode=story
- https://5f801fb2aea7820022de2936-fpksfyljdt.chromatic.com/iframe.html?args=&id=ds-react-stepper--completed-steps&viewMode=story
- https://5f801fb2aea7820022de2936-fpksfyljdt.chromatic.com/iframe.html?args=&id=ds-react-stepper--completed-non-interactive-steps&viewMode=story

**Comment by KenAJoh** [comment]
Er publisert i nyeste versjon av ds pakker ([dokumentasjon](https://aksel.nav.no/designsystem/komponenter/stepper#varianter))

**Comment by hestad** [comment]
> 

Eksempel 3 vil gi oss tilbake funksjonaliten vi mistet; takker :) Og vi skal se på muligheten for den andre tilleggsfunksjonaliten også. Bra jobba!
