### ISSUE TITLE
[BUG] Ikke lenger mulig å sette `onClick` på menyelementer i Dropdown

### ISSUE THREAD

**Issue by stephenramthun** [navikt/Designsystemet#1631]
## Hvilken løsning gjelder det?

- [x] `Komponenter`
- [ ] `Stiler`
- [ ] `Ikoner`
- [ ] `Annet`

## Hva er feilen/problemet?

Ser ut som man ikke lenger kan sette `onClick` i menyelementene til `Dropdown`. Kan se ut som bugen ble innført samtidig som `onSelect`-propen ble innført for `Dropdown`

I stedet for
```typescript
<Component
  {...rest}
  onClick={(event: React.MouseEvent<HTMLElement, MouseEvent>) =>
    context?.onSelect?.(event)
  }
/>
);
```

Bør man gjøre
```typescript
<Component
  {...rest}
  onClick={(event: React.MouseEvent<HTMLButtonElement, MouseEvent>) => {
    onClick?.(event);
    context?.onSelect?.(event)
  }}
/>
```
sånn at `onClick` faktisk blir kalt.

**Comment by KenAJoh** [comment]
Vil være fikset i `@navikt/ds-react-internal v1.2.4` snart 🚀

**Comment by stephenramthun** [comment]
Jøss, det var raskt! 👏
