### ISSUE TITLE
[BUG] useId i ConfirmationPanel med React < 18

### ISSUE THREAD

**Issue by cskrov** [navikt/Designsystemet#1651]
## Hvilken løsning gjelder det?
`@navikt/ds-react/form/ConfirmationPanel`

## Hva er feilen/problemet?
Komponenten bruker React 18 `useId` i stedet for intern `useId`. Fungerer ikke med applikasjoner som bruker React < 18.

> Hva forventet du skulle oppstå?

Bruk av intern `useId`.

> Hva skjedde istedenfor?

Bruk av React 18 `useId`.

## Steg for å reprodusere problemet

1. Ha en applikasjon med React < 18.
2. Oppdater @navikt/ds-react til 1.3.9.
3. Observer feilmelding om at `useId` ikke finnes i React.

```
WARNING in ./node_modules/@navikt/ds-react/esm/form/ConfirmationPanel.js 19:15-20
export 'useId' (imported as 'useId') was not found in 'react' (possible exports: Children, Component, Fragment, Profiler, PureComponent, StrictMode, Suspense, __SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED, cloneElement, createContext, createElement, createFactory, createRef, forwardRef, isValidElement, lazy, memo, useCallback, useContext, useDebugValue, useEffect, useImperativeHandle, useLayoutEffect, useMemo, useReducer, useRef, useState, version)
```

1.3.8: https://github.com/navikt/Designsystemet/blob/v1.3.8/@navikt/core/react/src/form/ConfirmationPanel.tsx#L1
1.3.9: https://github.com/navikt/Designsystemet/blob/v1.3.9/@navikt/core/react/src/form/ConfirmationPanel.tsx#L1

**Comment by KenAJoh** [comment]
Lurte seg inn feil import i en patch 💥 Er fikset i 1.3.11 om litt!
