### ISSUE TITLE
BUG: Aksel-nettsiden tar ikke høyde for sticky header

### ISSUE THREAD

**Issue by sarahbrodwall** [navikt/Designsystemet#1714]
![image](https://user-images.githubusercontent.com/91880567/201307600-b3d8063d-a088-4216-a244-ef7357807779.png)

Hvis man velger en anchor intern i siden, er det ikke alltid det er nok padding øverst, så headingen blir dekket av den sticky headeren.  Jeg opplever ikke problemet med "vanlige" headings, men det funker ikke så bra med infobokser.

**Comment by KenAJoh** [comment]
Fix på tur ut for Alert 🚀
