### ISSUE TITLE
[NEW] Mulighet å si at et bilde er dekorativt i Aksel (laaaav-pri)

### ISSUE THREAD

**Issue by sarahbrodwall** [navikt/Designsystemet#1715]
## Hva?

Selv om det ikke er vanlig, hadde det vært fint om artikkelforfattere fikk muligheten til å legge til dekorative bilder (`alt=""`). Dette er kanskje mest relevant for bloggposter o.l..  Har ikke hatt behov for det ennå, men det kommer nok opp etterhvert.   

## Hva løser dette?

Skjermleserbrukere ikke blir utsatt for for mye preik.

**Comment by KenAJoh** [comment]
Kan nå toggle om bilder bare skal være dekorativt (alt="") ✅
