### ISSUE TITLE
[BUG] Utilstrekkelig fokusdesign på relaterte lenker

### ISSUE THREAD

**Issue by sarahbrodwall** [navikt/Designsystemet#1729]
## Hva er feilen/problemet?
Fokustilstand på relatert lenke-kortene er vanskelig å se.

## Steg for å reprodusere problemet (valgfri)

Naviger med tastatur til en relatert lenke.  Det er bare farge som endrer seg, så det er vanskelig å se hvor fokus ligger.  Anbefaler en fokusring rundt hele kortet, siden hele kortet er klikkbar.  

![Dårlig fokustilstand](https://user-images.githubusercontent.com/91880567/207865761-1c7323f2-7cab-4c84-b7df-6241d24866fe.png)

**Comment by KenAJoh** [comment]
Fikset ✅
