### ISSUE TITLE
[BUG] Tabs bryter WCAG 2.5.2

### ISSUE THREAD

**Issue by sarahbrodwall** [navikt/Designsystemet#1736]
[Tabs](https://aksel.nav.no/komponenter/core/tabs) lar seg aktivere på down-eventen.  Dette bryter med [WCAG 2.5.2](https://www.w3.org/WAI/WCAG21/Understanding/pointer-cancellation.html) om pointer cancellation.  

Forventet oppførsel er at tab'en ikke aktiveres før up-eventen/onClick.

**Comment by KenAJoh** [comment]
Sjekket kildekoden for tabs-løsningen vi bruker i bakgrunnen og de bruker nå onMouseDown 😖 Oppretter et issue på det i koden deres.

**Comment by sarahbrodwall** [comment]
Yikes!  Takk for at du opprettet en issue. :)

**Comment by KenAJoh** [comment]
Issue: https://github.com/radix-ui/primitives/issues/1879

**Comment by KenAJoh** [comment]
Er nå fikset i #2621 🎉
