### ISSUE TITLE
[NEW] Mulighet til å skrive Aksel-innhold i ren HTML

### ISSUE THREAD

**Issue by sarahbrodwall** [navikt/Designsystemet#1742]
## Hva?

En mulighet til å skrive innhold direkte i HTML eller importere HTML inn i Aksel-artikler.  Featuren kunne evt. begrenses til "HTML-godkjente" forfattere.  

## Hva løser dette?

Skriving hadde gått mye, mye raskere for de av oss som kan HTML.  

## Eksempler/Info

Dette er visst mulig i Wordpress?  @mortentollefsen kan utdype.

**Comment by mortentollefsen** [comment]
For meg hadde det gjort kjempestor forskjell å kunne skrive/ferdigstille artiklene i VSC. Dette er jo mulig i mange CMSer, dvs. alle jeg har vært borti tidligere feks. WordPress. Blir veldig glad hvis dette lar seg gjøre!

**Comment by KenAJoh** [comment]
Vært veldig kult om dette var mulig, men slik sanity fungerer i dag vil ikke dette være noe man får rett ut av boksen dessverre. Alle moduler og komponenter er i dag basert på [Portable-text](https://www.sanity.io/blog/why-structured-text-is-awesome-and-you-totally-want-it-in-your-cms)-formatet som Sanity og flere bruker. Måtte på en eller annen måte da kanskje parse html og konvertere til dette formatet noe som ville vært vanskelig med alle "blokkene" som er tilgjengelige. 

En mulighet som sanity tilbyr er markdown-input, men alle komponenter og moduler må da tilpasses begge input-formatene. Ville da kanskje bare vært mulig å skrive tekst + tekstformatering, uten noen av "blokkene" som er tilgjengelige. Men usikker på hvor mye verdi dette ville gitt for seg selv.
