### ISSUE TITLE
[NEW] Expansion panel til Aksel

### ISSUE THREAD

**Issue by sarahbrodwall** [navikt/Designsystemet#1744]
## Hva?

En expansion panel-komponent til bruk i Aksel-artiklene.  Nå bruker jeg en enkel accordion-expander, men denne ser ikke helt riktig ut.

## Hva løser dette?

Får ned kognitiv last for lesere ved å skjule innhold som ikke alle er interessert i å lese.  

## Eksempler/Info

En quick-fix kunne vært å bare style accordion-expanderne annerledes når det er bare en av dem.  Kanskje med en border på toppen som matcher borderen nederst. Det kan se slik ut:

![enkel accordion-expander med border over og under](https://user-images.githubusercontent.com/91880567/212022847-7109ce1a-19a3-4767-ba15-78931d1fc81b.png)

**Comment by KenAJoh** [comment]
@Sjur-NAV Har vi noen expansionpanel eksperimenter vi har lyst å teste på Aksel før vi itererer videre på det ut i designsystemet?

**Comment by sjur-gr** [comment]
Det er det helt sikkert. De andre sakene @sarahbrodwall nevnte (#1741 og navikt/team-aksel#236) kan testes ut med expansion panel.

**Comment by KenAJoh** [comment]
Aksel-siden har nå en ExpansionCard-modul man kan bruke i alle artikler ✨ Har allerede oppdatert de fleste accordions som står alene til ExpansionCard, men alltids greit å dobbelsjekke.
