### ISSUE TITLE
Feil attributt for aria-relevant i flere komponenter

### ISSUE THREAD

**Issue by PerOlavM** [navikt/Designsystemet#1747]
## Hva er feilen/problemet?

Flere komponenter setter aria-relevant til "additions removals".
Dette er ikke en gyldig verdi.
Bør byttes ut til "all".
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-relevant

## Steg for å reprodusere problemet (valgfri)

Søk på "aria-relevant" i repo for å finne alle.
## Eksempel/Tilleggsinformasjon (valgfri)

Kan testes med ARC sin ARIA checker

```
 Hvis mulig, legg gjerne til kode her, evt lenke til kode i repo
```

**Comment by KenAJoh** [comment]
Hei, slik jeg tolket dokumentasjonen bør `additions removals` være en gyldig option.
Men siden vi ikke har med `text` (eller bare `all`), vil kanskje ikke endringer i allerede satte feilmeldinger oppdateres riktig for skjermlesere. Skal dobbelsjekke med uu, men tenker vi kan bare endre til `all` 👍

**Comment by mortentollefsen** [comment]
Enig i at verdiene som brukes nå er gyldige. Det står i wai-aria:

aria-relevant values of removals or all are to be used sparingly. Assistive technologies only need to be informed of content removal when its removal represents
an important change, such as a buddy leaving a chat room.

Jeg har testet dette flere ganger, men det begynner å bli en stund siden. Støtten har vært ganske så fraværende i flere skjermlesere. Muligens burde vi få testet det. Jeg er også litt usikker på hvordan dette kan funke i praksis, dvs. om vi risikerer masse skravling (er jo helt avhengig av hvordan meldingene faktisk oppdateres). Mest sannsynlig vil det ikke være noe problem å bruke all, men nesten like sannsynlig: det vil ikke gjøre noen forskjell.

Skal vi ta en prat og se på hvordan vi evt. kan få gjennomført en test uten alt for mye stress?

**Comment by mortentollefsen** [comment]
Ser ut som om denne testen er ganske relevant:
https://a11ysupport.io/tests/tech__aria__aria-relevant

**Comment by KenAJoh** [comment]
Hei, lukker denne som Wontfix for nå, men er bare å åpne igjen hvis dette fortsatt er er problem! 🙂
