### ISSUE TITLE
[BUG] 2.0.6 - 2.0.18 - React ikoner gir typefeil for role og andre attributter

### ISSUE THREAD

**Issue by ivoiv** [navikt/Designsystemet#1758]
## Hva er feilen/problemet?
React ikoner som f.eks. Office1 gir typefeil for role og andre attributter.

```
type '{ role: "presentation"; }' is missing the following properties from type 'Pick<SVGProps<SVGSVGElement> & SVGRProps, "string" | "name" | "type" | "style" | "clipPath" | "filter" | "mask" | "path" | "children" | ... 463 more ... | keyof SVGRProps>': onResize, onResizeCapturets(2739)
```

## Steg for å reprodusere problemet (valgfri)

1. Importer Office1 eller hvilket som helst annet ikon fra `@navikt/ds-icons`
2. Prøv å bruke ikonet f.eks . `<Office1 role="presentation"/>`

## Eksempel/Tilleggsinformasjon (valgfri)
Denne feilen ble først introdusert med 2.0.6 og finnes fremdeles i 2.0.18

**Comment by KenAJoh** [comment]
[Relarter Issue på Slack](https://nav-it.slack.com/archives/C7NE7A8UF/p1670223050713029)

Vi har ikke funnet ut hvorfor det er blitt et problem i v2.0.6, og kan nesten virke som det ikke er direkte koblet til designsystemet sine pakker da ingen type-koblinger endrer seg i yarn.lock/package-lock

Endringer i dependencies før/etter 2.0.6 er at @types/node ble lagt til i devDeps, men bør ikke påvirke publisert pakke 🤔 

Før
https://github.com/navikt/Designsystemet/blob/1994f3ec974121aa5ba7a7750402fbca8305257a/%40navikt/core/react/package.json

Etter
https://github.com/navikt/Designsystemet/blob/75609e1b09dfd725952d22268b4dba0934968963/%40navikt/core/react/package.json

**Comment by ivoiv** [comment]
@KenAJoh 

Det er noe nytt ved typedefinisjonen etter 2.0.5.
Her har jeg lagt typedefinisjonenene fra begge versjoner av Office1 ikonet under hverandre.
[TypeScript playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcARFDvmQNwCwAUMAHYxZQF5ZwDKAagHEMABWJh0Ab0ZwZcGMBgAbLAH4AXHFQwoLAOb0GsuQuUBJACbrN2vQYC+jRuay5FySnFwRmW3gDddAHkCAmBcLAAmAAYARgAODWw8GAA6ADFoAHd3c2wCAFEADwh5XABhEkhmLFYAHmEwgGtapPwU-gFRCHFajo785RAamAA+OAAyXkERMVQAGnItHWZdMjgAH3Ia8zXNskUIXGRFXfIvA6hTsldgMCutAE9lK9DFE43F7QhGrCvCq4eVxuYGEyBgAAsgQBXKCoaBXczASj4YDeBHAVBgNyAj5kV5sS64gjeGBpZAgYCKHF7YmsHjAABevyJJPpTIAguYAFZQrQvVnaLAwXCQll0mBPZk0kl8dzAZCsfmsADqWGAunBMCu4LVGq1uNAyF0WGwzGcy1WuOUMAJPDAeD0V26DolTqg5qu9pYMEC7vYnog3vY+T8w1QV2IMDBUsWR2euLYhRgpvNjoTUAVqGJUBAVyhzDCEGcACFgIirn4McAAEaUhTU8iZMsQq6ZaDmO0OlatnTyFYAWSLMbIxzA4OQ1aFYW1Ct0ab2ZawEF0GbH09xIDBOs3pWOV03qEaTpCqCFTtDHAOmSuiZgABEXNAwajmFdkAzQFCW7jjurmENWGLNAsEUFhh2rYDQOqHhwWAAh9T2YEMCheNEIgC5TFYdhIDceQ0Vxc5oBTdh53IcwSBYBUYCA08oOHV5FECe1cHrF5KUUZDUPIAgDiLCoLheXjzCYl0GzIXQqTHX1gGGZ9vD4dhd3ePZQL1PR+PhDd3B+KB8jNfdtPYfsywMqAdJ4KNYHuccwBNbYSO7XEtG6DTCT2ZywBEljXScr4fjvNBxygDMxKWb4sAC1BwQgE8z184gfgAGTAo47ni8LkuqLlA1fdKfmMglQIpBDPgSrAvNYvKsGVZtRT2W92WYEVNL2UN8GgfIQhcEqR3MRF5FDT0tyuH4xNwYhUFQaS51yvZwUoAgDP+DcsERZB9yFaKdg3FgrmYclh1cNBUAAOQOq4TKtWcbwnTDnGWvZiC4kcdGQABaZJgFDZxUHCM0qLfV6PpgCjcEB+UPq-Q5KmtYc5Xe6teTE+G3pFFwfm2vYUfOLx8x67H0JYe7wfe85MQVEnUZJJ7wx-IHcBhShFTpiGfvGmtVurZGgecKNKVprGeYxCdlEx8gUfMMQsC66gWfe9hiBzLBJqNOGgawQp7TNVbKZ4iBMhBymVwnScxZeiHx0xbooTSwWLbLZxZvFoGWD8X8zZR0aougYUvwF52IbcSdlID96g5A0Wucp5RQxD82w6+tWIZAIs9zlt6QBQ+Q6MpzPFHkWjupFpP3ugGTWDkp347e-WfEprEuGixQPXTyBUBYU98aBsBKEmnX08oZByOYKlKcoGOAYHrAAEcoSRfu7fep7VuV9mwDwquUeITJceZxe3u3omNbH-Xyc3oHC-wBfQ7ezv26ZSm4Ss9O3cUKEsE3B6b9f9+KXPiGf41H1pTQBt4bpQGND1CUtk3y4D+jAAAErqTUsCGZ52jG+N4+tsDtn9D+cAoEYBQmcIDCcYQMg5jfL9YYb4bQ6ERmwM6QxaE2AYVgAAKg8GBP4obYAvKeK4EFTxpEoLPGouAxJCKwF0V44FqwQC-mQScM1BHyn9kosaxxcCDhIQRZAYAkHqhQQRUCIItwAFUCwwHUYRKAmECQ4UrmkSkBIbHoWgDIykh0STDB4GvGAnDuFoSwuKSUgTDqKIkQiBELgQLsAwbiNmNDElwQILyLAFQfBRj3mRL6GIWpkRhAiRR5gxKrWNDo4ccS3YbyuDUYuQFcCNBXBAfMZsNZVGSXsDWBJ9ocWVq0qA4RUDYFnvPM2+J2DYHUZMqAliFAzMOLyYu-IcxgheG5bixBcxEkUQQMSugYhXF0BEY5klwRMOHBJLh4JpKyQ3ggsuDISRpz2NcsceRjkZkRMMdhGYfDZh2W8755cYDzOsdqJ5nI-AAA1IU6AZNNFgcKDTMFOaii6WEhlYHXiNI5uJGjor2I0AAzCNAALCNEa7BqiKH7GCHQiidK0vBYlGouhvzEppaRMgo1hA5QhQSrADw7R0XUaNdhoBlZXGUCsCEnIeR8itKABQ6lvBYEahJYcm4zLsEMXqUyOlwXqJ1TpGq5hOXkAPI0TJbBWDGoMoeB1G4hx7ShCAQI+BkChnUd0eJINNlkDLl08gwaK61NxGXFRkaLx0X5e3CNewICxrAuw2CTTqiTSGswCAp58V7HtBCNlcq6rkELb021wxnUFrBL0v5mZAVDRtDS6tZaBXqMgN6VA7IYAooLe2ntABNAMXae0AC1PS93YKGdkigxzrVxD3ZW06NWYm6hgOSk6VUDSwK2igEYh7AF5BGaWfbyALWHbiJmqYVj2JDRQHFOAYAVDxie2yYI7xFKvTPOelBzBFDte3bw6jRG-tWmkJ9MJpXfq0O4Hqvcs4RkUVAUKWBr5kFQAcIJixmI8rXQzNwUBMmwZyRh2yBH3BFE6aRtd6HMSD3MP2TaRZ7iWR9LFHqWhzAPkrJXVjH9S0YbYCAPwrGFAiklcodRSxgA-AhMQKEGp42qvwu5Gwcn5qtI1GmpombpMwk4OEPxxxhyoAeFoD+iVZxQlVjdasyhZRv2g-VdwkCz1kEspAy99UenFo5YJw2uIoT5vIFCIloXtZQDjbmlTVc2nsDojpjNyt1H5kLLovYaWvDOA3SsYcaXrHCGDEC8gfhZ3zsnKUCsxx37qP4S+CsiloXedK4pJFzB3MXh9DoGaLWyB+AQbOHlfgLBLmNmuMGuJKxYEyMWBRFYZKZHYa5uKrV6UQg-s+OMrZarqMKCFsghRwuHbKOOZgtKeBxPaoGwo+rjF7EKFBRo7J8A2bYH8J77IhnLw+ywRoCCFq-eYI0DA6FhyPb+zBYBuIIfA8lUocHT3wl-BAIoGi4PUdWccg91HdcYe49QDCp7KPFCdnCACA7DxjsPFOwqC7V2A1XAZEziAJBGrmFBFXEUlJJY1ARLOdgrTMMiqFJhaoUAEHsP7IlJ0zAKhgDEt4eXNP9FEMoLLsoX4NdfjKKrqDsvQQWYN2gNguv1768jXLyoMWN56TNkr63CaXx27N2r4cDvwA25fBZODGvHexZ97AV3Fuk1W89077w5iwDmASaHio4fYtR5j6bvX6vLcZAZr65gGfeTB7T6H4sb9A3eELzCPP7u5dneNBrqvGTU8V+LNLaAWBMJgC15bxv2YW-MDb8++vsvW-t9D4Pvv5v8+huYNM1bE+p+j7d7LngUJqzFQX0v4q5eB-MFfpdYfW-3Yb8t4lCAQ9ZdH6Hgf0P+RgoFKDcwK-isL8T4ANLCrvLXWXL+Hhv8yHL-vlvP+iApYf7CqAGTSP636f5R7AEPBR7gHeDsjyLPyh4IE+xwG-7MDCDYga4KiYHIAq5j4V664YHYhpoKYajYHEF4GkFabghoGfoZgby055ay70GVxMHGhoH5DgDyDobeBcHrwyTmCcFNQobry8F34iFcJsBCF-6X7az24SHOAyEEGn7H5KEBRRiqFDyrQaHIBoFn5KFMZRjJ4Lqh4GGrRGFDxgh6GyET4GGB49TeD2FsZoGgjpLG7pKuFYGW64H4Hz4+HYg8reC+HqS2G35dArhAE+HECRFgFhHeAbqm616y6JEZK15oHTKMgV6ZFMhoGXZYAYwL5oYYx5HFFBHMD5GNChEqGW4+5vDiF1Gix5G8i2T6S1EtHbBoGSpDBJ6x4T7dG7rR7RhoF8DoTuppEC6y6jFvxDDsF141Gh7KjICqrY4T5LErG6BoHshQiFBlCgRNKy7bG7H7E2rxFy4nEa4nFoGVpJhMbMBQh+5YS3E1BQh0GtL2YZIXGW5v5L7KB7FNB0EZiWih53hAmAlGh24sFAku5nGgkQlYpQnwkEjgm6BFAKCImomFAKAolsreoV5wm6C4mhgomBAXgYmknsAokOEYkOGAndBQkuRnGDjpLf5VzeDMmnisloEclYB6QEiy48lEkV48mDiDSW4inJrzH+Gh48mBBD4T6yk65MlC7lRknikqkUlEbKnpJQHqk6lgClHKCyyh6XZGlz4h79GtIihEHhBxzeDsJWm0EKi2ldGOmQmW4OlQgigwkLGWlengiikV6ekiiBmun+nUkemOm0lnH8pBhQCskG4CrsBckxlJlQCBmJlxmhmplxm6mh6xlYqwE5lYo2kgSZklnOkgSuFpl8l4L5k1kVm+nhFplCnlkEhCnVlxmaltnsCamdlYpymOEYFpmDloECAlAFnIlnHjkwCTmUn176G5qzlpmLlaBzlakEF5HjToR2kVHblvBoHKg6hlmW5HloaKBbEFg7je5saHFXmVzRlNnwH3m25tHIEvnO5miXmGgbymAEh8aW6NQ-kvh-n+ovhdH-IR6KGy71o+CxY+nSlwCjQxRTBCBdDiBjCTCtCpB5A9qsJfjKy9CCD9CDDDAjAjAGDOBHQeBeBZL+BBAhBhCRBRBRAACsiQVAqQFC2Q7oeQRQJQYQ8e1GMA9QTQLQnF7Qgg6FqARFAgJFH8ZFEwqFMw3Q8wpUPK2wMqhwryZw7igawIrGkobEbwrGZUfwAIQIpioIlq1wMIT86IyIiauSmI3hNILidZ3EJIZIFIo8YoMAbI9ErIWRCqvIPUtI-lgowogm4VFkRlflsor0pG4VqoRiPUOoqVF0m4xoxEFoMqQotouGqxQauGPkSafogaXorAvoLc-acZIYYYEYJQfRGGcYw4t4OVPK2gDa0AJWZAWWQ4pY5YU2VYtYhCYkTYFqgmbY7oZOPKmQvYeglSmCFWU4k2c0Q2RVi4y4q46aBkG21522Wkh4x4BAnc547Aes14CYPSD4XgDBDWP4H4mcNlv4ug-4ww6OOcuIUidEMEcEPUSEKE3iGEWKjiTl1welHVRV5Ef8VEn1YExljEJVYkDEnE9EQkrkgkrOwkyNZyNydy4aL4CksAYQOl+wqVaqAkWkuqukb5Vqhk6ZO+9NNNEZ7kNkdkkWeGIMBpelrG3QFUpVpU4UkUQUIUplwtgUMUp10+QmZUmULg+i4tSUYE2Uu0VUBUCW26St5UuNVU5qNlDUTU0UgabUAanUBA3Ub4fUqqYpNaNlo0QIE0U0PWatc0gOWkiiQwa0G0EILGO0Vc+0zCJix0lyF0ZsbgRVUY1Yd0x8V6YOlMn030q82wk8+8YIoMCdUMXgBCQoJcb0iMZmlMaMTS6GBMigu8XcEM5wR8iiZdZ8Rd1M6E6i2MjM96Esq89CnM3MrMQoyxigzdQsqAxcHsPMUsMsld8s1+SsKs1e6cHSCoShusV4gW+8xs1YpslMlskAbetsN8sEfUfO6crs7slMXsxtvsgq+84cccKM19kc3dYcWAsc0cicucqcN9QMec2cCN6cX9GIDOKy6cYaUY4NKMtcA9EMDc4QTcNVN8bcHcMtKMS6fcI9EMDG3gvl+848T9qdN8oG4yJ8osHdtwoDQM28FdJ8TY2stdZDp8Wsj8DOpdF8Qo98edT8E9b0gCn8ICNWH8rt38vDOaV1+8oCPS4CkCN4XCcMcCwwd2+McC7qKEzVxwV4OC5Vb4BCCgxCasZCuAFCvVaA8CLC9CBFodP4dCNYBFyOPCIMfC7AAi31wEIiP64ikiwEniz0698231WA0aewtYaAgimi5dS1eiBiyCANVlFiVibiINDi6ETi7lsIQIelHj3iIS-l-i1jwSdqEVYSUjQIkSYkZsVFcSDBw4SSpGiIIQnhwG2SPUiIlY9liSX6ew5gJSZS5gFSrquI1SAF3S+0HxjSzSCmdNZAHS6qpGPSNKxw0ygywyoyYGEyST0yxlBIe6xImegD0oayYVgaRAJALweyByB2JyeNY4Zjby5yBNIDL4jyCKLycc7y4InyuIxsPyrAsFWYPVXyh6VaMT8KjI0K7mxtjI7W7mLAx2-DZAcZ4QuKBKB2hKI0ZKBKlKBK1KUAtK62jKGLLKVifm9t3KRVfK7a1KIqWIYE4qwqAx6isq-mIVSqKk26aq1Qmqz0pqeqEThq7Ae6HLUA+tgm1qla9qALR1jQvLPTew9xHqXqPqTotkDBN+wDbooK-ToaLtbJKa1Qym4NkpUWqa6ajQem2auaWAB2ha4IBLgm5aNKwrYKordtdakFjai6taLaDrbaXaI6rA3ava3r1iQ6-rvrE6i6U6UAM6c644k6y64bq65GyYm6obzLoYe6gaIKx636BA7mF6J6nNt6GTb6T6L6pGlA7694rT56P64yAGNQQGeOj0Vbf6EGYIUGIGyst5MGiGV6yGqGdGWGpmhVwJOGLgSjRGdTuDZGI7hGVGkznGtkdGS6Q8RhW0rGcGwQ0tnGMA3GT98o4NFmIAgm+7omvk4m4Ikmzm6lGmZB4IOrD1amOgV7NBSWRrUR7kBmXAxmz0Zm+7WOugNms9LmHxjmtW4jQo7mnmQofWt4VrN4EAeYB2YWeYkW0WUFSH5oiWhrxrQWBY2W+WOHQ4uWAHEWCyRWukvVZWkbE4q11WTmdW9jd7rWsAzWjWsA4LLH3W6oLAfWA2G1Q7-Wo221+iu1w1M2c2ii02S2K2PUfg6224W2ZNE1EIe2B2R2fwTB9OZpN+t2XLMOn2r2zVsOz2328dunf2AO0sQOIOJnD2T2UOwj5Ahn8Oz0jnBT+OaOwEJOv7JO9bDnBOROf2JOZOw4DwlO1O6nIEpp3UN+zOuIzybOZonOQIsEzcTM-OeWCmwul2MAYueqUuMuluyufuCu1x8pt+mu5p4+4RJuFehuKeT5Ye8Dr5ChQlXufBX5ZxLXUFrNE+nXAeLhHX-uG8vR72BXg3L4w3UpFpt+OeWeM3aBpexezAC31xyRBX6RZxnezeI+sum3lAI+aB23lu+3Zxs+KRy6FXFei+y+6J7R13F3m+2+ChmEj3i5J+h+ahnBU9su9+0AaBn+CZ-+r+tcf3IBvcWeABYPIPMBu9EBwqRZ9XKBSBE+iP93BXOBrlPX6PeB1xWPDw1BimgmSuuP+PGodBMIbBq3IJ5PjB639X-BPBCh9Pghwh40Uh4hekrPYhyhiFt+du7P8hr36h1hWhQvUYgvFhvdJhIvEvxh1hgv3Xt+zhcGrhyA7hPhqvp4XheBBu2IWvDw5RIRKwrhMRYPBuJvKWGRwxlPM+VvAupRBRDRxRq09vVRRV3glR1RPP7vUY9RChjRzvZxi+a6Yz7vHR7X9XAxE3MFUqE3IxYxsx1vt+0x4xcxh5yxfYfH3g6xGfWxOx-xBxgFefVxHXXxcexf9XNxMAdxDxo3TxVfLxbxvxnxTQLB7xfx5fXvzABJGJKJ7pIJ0J4fnfBJtZi3w-jZQ-0JWJQ5w-U-OJOAttE+BJHZsJQJ3Z3xq-F4VJHb-fRoj5E-9J6-jJ9XPJAPMpKpKZx-KpI-ApKprZepp4GZ9-WA2Zl-6Sg5N-b-Spr-p4a-Z-b-m-2pU8HmQVIql4enfSLsaQnwQDUeoeYMk6SagnlYBjpUsheTOJwC++fpb0oPym72lHSj-JAf6Rf6d84BCvXAeGX671d1yp-CfFQOB7FkCQ+AmgWmSIE4DhyuZGHsETTJgDWB65FAT2S1IIDUBlAhsvyR8IiD5ywguMnf3rJSD5+k3SrpwK7JqkZBA5AAZIIHKldFBGgmARPhnK8DpyE5FcguTOJH41yRg+rqYOXJxly8W5J6LuT8R2DDyx5XcmeSrJnEgK15b3r7kAofkvBQedwb4Ogo+DgKbXbnqwI8GVxQK91VTMj0CFRC2CaAyCvBRD7MAvmyQsIePmQoEBlK0lTCpgAkq4ULGbCGSn0EEADAFKrAcigYCAA)

En tekst diff ([prøv her](https://text-compare.com/))viser at 2.0.18 har to ekstra atributter i den definisjonen, "onResize" | "onResizeCapture".  

Ser ut som at det er to nye attributter som React har lagt inn for SVGProps med React 18+ og det clasher med SVG typedefinisjonen for prosjekter som fremdeles kjører React 17. 
Fjerner man disse manuelt fra TS definisjonen forsvinner feilen. Enten må vi tvinge det tilbake til React 17 typer eller må 2.0.6 egentlig bli 3.0.0 for da er det jo breaking i og med at den krever React 18.

Jeg ser at det brukes React 17 eller 18 som peer dependancy i 2.0.6
```
  "peerDependencies": {
    "@types/react": "^17.0.30 || ^18.0.0",
    "react": "^17.0.0 || ^18.0.0"
```

Kanskje byggescriptet bygger TS definisjonene med React 18 typer?

**Comment by KenAJoh** [comment]
Vi har `"@types/react": "^17.0.30 || ^18.0.0"` nå, hjelper det å sette eksplisitt `"@types/react": "^17.0.30"` i løsningen deres?

**Comment by ivoiv** [comment]
Nei, det hjelper ikke. 

Her er problemet at "onResize" | "onResizeCapture" er "hardkodet" som Strings inn i TS definisjonen i den bygde pakken.
Den krever dermed React 18, siden kun React 18 sin SVG type har disse attributtene.

Probleme er egentlig den lange hardkodede lista av attributter i definisjonen du kan se i TS Playground.
Pick bør kun referere til React typene i React pakken og ikke ha noe hardkodet liste for at det skal fungere med alle versjoner.

Her er det egentlig noe i byggscriptet som hardkoder attributtene tipper jeg, mulig noe legacy/compatability option?

**Comment by KenAJoh** [comment]
Skal undersøke, skal kunne gå å bygge types uten "pick" her som da igjen fikser problemer for react 17/18 👍

**Comment by KenAJoh** [comment]
Skal være fikset i 2.1.1 da 🚀 🤞🤞🤞Takk for hjelpen!
