### ISSUE TITLE
[Innspill til komponent]: <Button />

### ISSUE THREAD

**Issue by Trent-NAV** [navikt/Designsystemet#1775]
### Om fjernet bakgrunnsfarge på secondary button.

Hvis formålet med å fjerne bakgrunnsfargen på secondary CTA button er å introdusere en ghost button type er dette noe som eventuelt burde eksistere som et tillegg til primary, secondary og tertiary CTA buttons, altså noe som kan fungere som en kontekstuell sak og som en komponentvariant. Jeg for min del er ikke enig at secondary og ghost er helt det samme og at man derfor ikke bare kan bytte ut den ene for den andre, bruken av secondary er annerledes på IF enn på EF og det kan være greit å ta med i betraktning. Uten bakgrunnsfarge på knappen blir det utfordringer på ulike bakgrunner mtp kontrast, det blir variabler og inkonsistent utrykk. Effekten blir enda sterkere når button uten solid farge står mot ulike farger på en og samme side.  Jeg syns button hierarkiet også svekkes da secondary nå fremstår mer som vår tertiary med border. **Merk:** på IF er secondary + tertiary en ganske vanlig kombinasjon.

En secondary med solid bakgrunn kan benyttes som en CTA handler alene i større grad enn en ghost button, på saksbehandling brukes gjerne secondary mer enn primary der knapper kan være et veldig repeterende innslag i UI'et, på alternerende og ulike bakgrunner. Secondary brukes oftere enn primary når man har gjentatt bruk på samme side da mange primary buttons sammen blir for _tungt_, så suppleres primary inn der man trenger en _heavy handle_ opp mot secondary. 

Det finnes flere DS komponenter som trekker veksler på utrykket fra secondary button, feks stepper linker og search button i secondary variant. Disse kan også opptre på ulike bakgrunner, hvis også de hadde blitt frarøvet bakgrunnsfarge i markørene / eller knappefeltet, så ville de også lidd samme skjebne mtp uforutsigbare utfall. Om disse secondary variantene ikke endres for å følge opp CTA button endringen blir secondary begrepet internt ganske rotete, så alt i alt burde det å bare beholde secondary CTA med solid hvit bakgrunn være mest praktisk for alle kontekster og flater. Å beholde en solid bakgrunnsfarge på secondary følger også opp konseptet med solid farge på primary og sikrer plasseringsvennlighet, enklere implementasjon og best bruksopplevelse etter mitt skjønn. 

![secondary_bg](https://user-images.githubusercontent.com/86958516/215768118-32fcfc70-8e86-4ee9-94f2-f11b10c73cf4.png)

![sec_tert](https://user-images.githubusercontent.com/86958516/215768165-ad58e259-9e54-47d0-b37e-936569c8d741.png)

![secondary_table](https://user-images.githubusercontent.com/86958516/215768190-09b11e0e-36ed-4fdd-b9fb-aeef6fd30858.png)

**Comment by lmfaole** [comment]
Vi kommer med en større rework av button komponenten når vi har tid til det. Det vil svare på noen av disse problemene. Vi kommer tilbake til dere om hvordan det er tenkt å løses 😄

**Comment by sjur-gr** [comment]
Vi la til neutral-varianter av knappene nå som svarer på noen av disse situasjonene. [De kan testes på websiden nå](https://aksel.nav.no/komponenter/core/button#ha8bb240d2c68).

**Comment by Trent-NAV** [comment]
@sjur-gr Med hensyn til utfordringene med manglende solid color på secondary så ser jeg ikke at det løses med de endringene som er gjort nå, men hører gjerne hva du/dere har tenkt rent konseptuelt med buttons. @olejorgenbakken nevner for 3 uker tilbake at det vil komme en større rework av buttons komponentet, er neutral en del av dette? Tar gjerne en touch om tankene dere har bak neutral, for meg virker det som en praktisk utvidelse av button komponentet som sikkert løser andre kontekster, men akkurat dette med en blå (tung) default primary i interaksjon med en default hvit secondary har fremdeles samme dilemma som jeg nevner i min dokumentasjon. 😀

**Comment by lmfaole** [comment]
Det var dette jeg tenkte på 😅

I tillegg diskuterer vi stadig navnene på variantene. Akkurat nå har vi ingen konkret tidslinje på når resultatet av dette arbeidet vil se dagens lys.

**Comment by Trent-NAV** [comment]
Supert initiativ Ole Jørgen. 👍 Del gjerne hva dere har tenkt rent konseptuelt for det kan være flere brukskontekster, så neutral er sikkert formålstjenlig og en grei button type, men i forhold til dette med manglende secondary solid color (slik den var før) så svarer ikke neutral button helt på dette som jeg ser det. Tenker at default primary (solid) burde parres med en solid secondary slik at secondary kan parres med tertiary uten at "tyngdeforskjellen" fordufter. Dette må kunne skje på de bakgrunnsfargene som finnes i miljøet vi jobber i og de kan som nevnt variere.

**Comment by Trent-NAV** [comment]
Enda et eksempel på hvordan manglende bakgrunnsfarge på secondary slår uheldig ut. Håper vi kan konkludere med at den burde tilbakestilles til solid hvit nå. Om ikke tror jeg det kan bli en del fristilte secondary buttons og det er uheldig da DS burde kunne tilby forutsigbare komponenter for flatene vi opererer i. Jeg syns ikke det såkalte ghost grepet gjør det. Introduser heller en ghost som et tillegg eller som variant.

![secondary button](https://user-images.githubusercontent.com/86958516/221697013-48cf1815-55b3-4c8b-aba5-812c10e99e35.png)

**Comment by KenAJoh** [comment]
Hei, vi har gjort det ganske lett å overskrive farger i kode nå 🤞 Har satt en demo opp for hvordan det gjøres for secondary-button her: https://codesandbox.io/s/funny-yalow-q3komm?file=/App.js

For å fikse secondary button med hvit bakgrunn i hele appen deres trengs bare denne å settes på toppnivå i koden så skal alle secondary-buttons bli fikset 🔨 
```css
--ac-button-secondary-bg: white;
```

**Comment by Trent-NAV** [comment]
@KenAJoh Takk for update. Betyr dette at secondary da er tilbakestilt i DS? Like viktig er det da at bakgrunnsfargen gjenopprettes på komponentet i Figma slik at man slipper å gjøre secondary button til en fristilt "orphan".

**Comment by KenAJoh** [comment]
> @KenAJoh Takk for update. Betyr dette at secondary da er tilbakestilt i DS? Like viktig er det da at bakgrunnsfargen gjenopprettes på komponentet i Figma slik at man slipper å gjøre secondary button til en fristilt "orphan".

Secondary-button vil fortsatt ha `transparent` bakgrunn som default, men ved bruk av token vil da hele systemer kunne "opt-out" ved bruk av en linje css som vi håper vil løse problematikken for de fleste. Ikke så kjent med hvordan dette best løses i Figma, @olejorgenbakken kan vel mer der 😄

**Comment by lmfaole** [comment]
Figma blir litt vanskelig der 😿 , men ved å endre bakgrunnsfargen i komponenten vil jo alle andre states være like uansett. Så det kan jo hende det går bra.
