### ISSUE TITLE
[Innspill til ikon]: 

### ISSUE THREAD

**Issue by taniaholst** [navikt/Designsystemet#1776]
### Tilbakemelding

Usikker på om dette blir riktig sted å sende inn forslaget, MEN når jeg leter etter et ikon vet jeg ikke alltid hva navnet på ikonet er, og da hadde det vært nice med flere "tags" som man kan søke på! 
F.eks. om jeg leter etter ikonet som heter Error jeg søkt på "stop" eller "no" ettersom jeg har sett for meg et slags "stopp-skilt" som man har på veiene. Kanskje et dårlig eksempel, men dette skjer ofte når jeg søker etter ikoner, fordi jeg ikke alltid vet hva de heter! 😅

**Comment by KenAJoh** [comment]
Hei, er en kjempegod ide og noe flere har kommet med innspill på. Når vi etterhvert oppdater ikonsiden + ikonpakken er dette høyt på lista 📝

**Comment by Camulos** [comment]
Har nå kartlagt ikoner mot behov i BRsys prosjektet hos Brønnøysundregistrene. Flere ganger opplevde jeg ulogisk navngivning av ikoner her, hvor det var gitt navn ut fra ønsket funksjon fremfor hva ikonet er/symboliserer. Så jeg ønsker meg at navngivning ses på som helhet og at ikoner også får en form for tags i tillegg slik foreslått i issuet. 

Eksempel: "settings" som er et tannhjul burde vel heller ha navnet "cog", og slike er det flere av. "Add" burde hete "plus", ellers så er det rart at minus ikke heter "sub" e.l. ?

**Comment by Camulos** [comment]
Har nå kartlagt ikoner mot behov i BRsys prosjektet hos Brønnøysundregistrene. Flere ganger opplevde jeg ulogisk navngivning av ikoner her, hvor det var gitt navn ut fra ønsket funksjon fremfor hva ikonet er/symboliserer. Så jeg ønsker meg at navngivning ses på som helhet og at ikoner også får en form for tags i tillegg slik foreslått i issuet.

Eksempel: "settings" som er et tannhjul burde vel heller ha navnet "cog", og slike er det flere av. "Add" burde hete "plus", ellers så er det rart at minus ikke heter "sub" e.l. ?

**Comment by lmfaole** [comment]
100% enig i dette! Dette er grunnen til at det tar tid å gjennomføre endringene vi ønsker. Det vil bety mange ødelagte lenker til eksisterende ikoner, og må kommuniserer riktig og times.

Men som sagt: dette er jeg helt enig i!

**Comment by sjur-gr** [comment]
Nå er ny ikonpakke ute som bruker tags i søket. Jeg lukker dette issuet, men skrik ut om det er tags vi bør legge til på de nye ikonene.
