### ISSUE TITLE
[Innspill til komponent]: <ToggleGroup />

### ISSUE THREAD

**Issue by Trent-NAV** [navikt/Designsystemet#1781]
### Tilbakemelding - Label align right

Det er tilfeller der label må stå høyerestilt grunnet generell posisjonskontekst så det hadde vært fint om dette komponentet kunne hatt dette som del av variantoppsettet slik at man slapp å fristille seg fra DS native utrykket kun på grunn av dette.

**Høyerestilt label - nederste eksempel**
![togglegroup_label](https://user-images.githubusercontent.com/86958516/216334332-e0d5e778-0fce-4f95-b548-9d386578bf27.png)

**Comment by lmfaole** [comment]
Har du noen eksempler på kontekster hvor dette er relevant?

**Comment by Trent-NAV** [comment]
Høyerestilt toggle group. Faller ned fra triggerfelt.  

![togglegroup_eks](https://user-images.githubusercontent.com/86958516/216335447-d8fb30f3-e4e1-4143-b083-cc06f1ee18d9.png)

**Comment by lmfaole** [comment]
Interessant. Har du tenkt på noen andre løsninger som kan fungere?

**Comment by Trent-NAV** [comment]
Dette er kun en tidlig fase av en iterasjon men før jeg designer noe som blir native Pesys og lager et eget komponent av det så ser jeg alltid om det er noe fra DS som kan fungere. Det er for øvrig flere kontekster der en right aligned label er kjekt å ha på dette komponentet, og siden det er lavterskel å legge det som en DS native variant i komponentet tenkte jeg at det er bedre å gjøre en liten justering i DS enn at det lages fristilte kopier kun på grunn av slikt. Det å gjøre komponentene plasseringsvennlige og fleksible er spesielt bra for interne flater der brukskontekstene er ganske varierte :) 

PS: Veldig mye av Pesys er gammel plattform som ikke er React kompatibelt, så de gangene vi faktisk får sjansen til å implementere noe på områder med React støtte så velger vi selvsagt DS så langt vi kan. Det er en god del ting vi ikke kan implementere globalt før det foreligger en plattform fornyelse, dette med size toggle er en av dem. Jeg itererer ofte for fremtiden.

**Comment by Trent-NAV** [comment]
For å samle respons på ToggleGroup legger jeg også inn[ tidligere innspill fra Slack](https://nav-it.slack.com/archives/C7NE7A8UF/p1670234367695739) om formspråk og typografi i komponentet.

Jeg syns ToggleGroup fremstår litt egenartet i forhold til formspråket på DS komponenter generelt. For å vise hva jeg mener har jeg stilt den opp sammen med noen andre DS komponenter som deler 4px corner radius attributt.  Er det noe spesiell årsak til at Toggle group har 8px corner radius på containeren? Label framen har 4px. Viser et par eksempler der jeg endret containeren til 4px radius. Jeg syns også den radiusen ser bedre ut når selected state står nærmere container borderen som vist i et av eksemplene. Det vil vel også fungere i focus state. 

![formspr__k_-_toggle_group](https://user-images.githubusercontent.com/86958516/216440212-fe468359-ed8c-4a6c-b74d-85739e5793fd.png)


-------------------------------------------------------------------------------------------------
### Typografi
Når det gjelder labelen blir den veldig tung når semibold er gjennomgående default på Toggle group. Selected og hover state er i seg selv fremtredende og da blir det å bruke samme fontvekt på default / unselected litt "høylytt" når de står på rekke etter min mening. Label/Small og Label/Medium burde hatt Regular weight i konsepter som dette. Lagde et eksempel på Regular sammen med 4px corner radius. 
![formspr__k_-_toggle_group_02](https://user-images.githubusercontent.com/86958516/216439980-fa6f16c4-fab9-41b4-8a79-e1c8a54785ef.png)

-------------------------------------------------------------------------------------------------

### Kontinuitet 
Det at Toggle group har semibold label på samtlige valg matcher heller ikke feks. [Toggle Chips](https://aksel.nav.no/komponenter/core/chips) der det er semibold og regular vekting på en mer forventet måte.

![chips](https://user-images.githubusercontent.com/86958516/216440027-e5819279-04a7-46c4-8c2a-07e3c5c7a518.png)

**Comment by lmfaole** [comment]
Gode innspill! Enig i at ToggleGroup er litt for ulik mange andre komponenter i dag 🦅

**Comment by sjur-gr** [comment]
Toggle Group har også [fått neutral-variant nå](https://aksel.nav.no/komponenter/core/toggle-group#h683348bdd06b). Alignment på label er ganske enkelt å justere i situasjonene det trengs, så det er ikke behov for en prop på det. Jeg trakk ut tilbakemeldingen på design til et eget issue #1811
