### ISSUE TITLE
[Nytt ikon]: Rusproblemer

### ISSUE THREAD

**Issue by ghost** [navikt/Designsystemet#1783]
### Navn på ikonet

Rusproblemer

### Eksempel på ikonet

Ikon til bruk i spotlight https://www.nav.no/komme-i-jobb#rus

Viktig at ikonet ikke er stigmatiserende, men varmt og menneskelig. Gjerne noe som uttrykker håp og lys, selv om man har det vanskelig?

**Comment by lmfaole** [comment]
Vi har dette ikonet i dag, som kanskje egner seg best i dette tilfellet?
https://aksel.nav.no/grunnleggende/staesj/ikoner?icon=SocialAid

![social aid](https://user-images.githubusercontent.com/37940048/217820774-2009a923-0300-4c21-af83-020c6a435a13.svg)

**Comment by ghost** [comment]
Tatt det opp med teamet. Det brukes om sosiale tjenester og har ingenting med rus å gjøre. Må spisse det mer på tema. Slik at det er lett å scanne ikon og forstå tema man skal lese.

**Comment by sjur-gr** [comment]
Her er noen forslag:
<img width="159" alt="Ikoner - Rusproblemer" src="https://user-images.githubusercontent.com/82579704/218321771-f7363194-480d-4ce9-954c-4e361608a21f.png">

**Comment by KenAJoh** [comment]
https://aksel.nav.no/ikoner/HeadHeart
https://aksel.nav.no/ikoner/MedicineBottle
https://aksel.nav.no/ikoner/PillCircle
https://aksel.nav.no/ikoner/PillCircleRectangle
