### ISSUE TITLE
[Nytt ikon]: Psykisk helse

### ISSUE THREAD

**Issue by ghost** [navikt/Designsystemet#1784]
### Navn på ikonet

Psykisk helse

### Eksempel på ikonet

Trenger ikon til bruk i spotlight.

Viktig at ikonet ikke er stigmatiserende, men varmt og menneskelig. Gjerne noe som uttrykker håp og lys, selv om man har det vanskelig?

Ikon: Hjelp til å komme i jobb. Oppfølling på arbeidsplassen, inkludering.

Info på tema:
www.nav.no/psykiske-helseproblemer

**Comment by sjur-gr** [comment]
Her noen forslag:
<img width="113" alt="Ikoner - Psykisk helse" src="https://user-images.githubusercontent.com/82579704/218321842-bb808f74-0e64-4d95-ae5b-adeecd7042dc.png">

**Comment by sjur-gr** [comment]
Etter en rask brukertest prøver vi oss på det første https://aksel.nav.no/ikoner/HeadHeart
