### ISSUE TITLE
[Innspill til komponent]: <DatePicker />

### ISSUE THREAD

**Issue by oivindkulsrud** [navikt/Designsystemet#1794]
### Tilbakemelding

Det nye date komponentet ser generelt veldig bra ut! Vi har imidlertid støtt på et par problemer. Har kjapt skissert et av dem nedenfor:

Om man skriver en dato som er utenfor det lovlige feltet flyttes brukerens eventuelle popup kalender til dette feltet (noe inkonsistens der, av og til må man åpne og lukke to ganger eller noe).

Tekst som er grå er ikke så big deal, heller ikke at brukeren navigeres til langt utenfor lovlig område om de skriver feil.

Men at dropdownen (med måned, år) låser seg til det lovlige området samtidig som brukeren er navigert langt utenfor det og bare kan navigere seg tilbake ved hjelp av 12 trykk på pilene, ikke med dropdownen, blir imidlertid feil sånn vi ser det og burde helst fikses.

Et mulig alternativ er å ha en tilbake til default mnd knapp i datepickeren om bruker manuelt skriver feil dato i tekstfeltet og så åpner kalender popupen for å fikse.

Et annet å la bruker sette dropdownen tilbake til riktig kalender om de er utenfor.

Eksempel:

![image](https://user-images.githubusercontent.com/47426778/217567464-86d45768-bedf-48ba-8134-aedd0439b81a.png)

![image](https://user-images.githubusercontent.com/47426778/217567523-1e73137f-9994-4019-8bb3-bb9057af4b62.png)

dropdownen har ikke noen effekt som lar deg gå tilbake til 2022, fordi 2022 allerede er valgt, man må altså eventuelt navigere seg igjennom året med pilene

**Comment by lmfaole** [comment]
Hmm dette var et litt spesielt tilfelle 🤔

I skjermbildene så står det at de lovlige datoene er mellom 8. september og 21. september 2022, men i datepickeren kommer det ikke fram at de kan velges, selv om de datoene er i grensesnittet. Samtidig har brukeren skrevet inn 20.09.2023, så det er ikke samme datoene i dateinput og datepicker. 

Jeg lurer på om det kanskje er en annen feil i skjermbildene her?

**Comment by lmfaole** [comment]
Vi har diskutert det litt mer i teamet nå og jeg tror jeg forstår det bedre:

**Bruker har skrevet inn datoen som vises i datepicker, men datoene som vises i selve dropdownen er ikke det samme?**

Det høres ikke helt riktig ut, har du noe informasjon å dele @KenAJoh

**Comment by KenAJoh** [comment]
Takk for tilbakemeldingen! 

Er en litt tricky case siden dropdown-verdiene blir genert basert på fromDate/toDate 
```jsx
<Select
    value={displayMonth.getMonth()}
  >
    {months.map((m) => (
      <option  value={m.getMonth()}>...
    ))}
</Select>
<Select
    value={displayMonth.getFullYear()}
  >
    {years.map((year) => (
      <option value={year.getFullYear()}>...
    ))}
</Select>
```
Så `value` er i dette tilfellet "riktig" (20.09.2023) men er ingen `<option >` som matcher den valuen. Select triggrer da heller ikke en onChange ved valg av samme år/månede.

Kan løse dette ved at den valgte datoen plasseres inn i select slik at man kan velge seg til den gyldige datoen. Eks 
<img width="537" alt="Screenshot 2023-02-09 at 13 30 43" src="https://user-images.githubusercontent.com/26967723/217813491-d42f8c00-210f-4f1c-8420-bd703ed5fb2e.png">
