### ISSUE TITLE
[Tilbakemelding på ikon]: 

### ISSUE THREAD

**Issue by hannahogberg** [navikt/Designsystemet#1799]
### Tilbakemelding

Hei, 

Jeg ønsker stroke på disability ikonen: 

https://aksel.nav.no/grunnleggende/staesj/ikoner?icon=Disability
 Takk :)

**Comment by lmfaole** [comment]
Vi jobber med å få ut stroke variant av alle ikonene. Enn så lenge kan du [hente de ut her](https://www.figma.com/file/UmEVH3pZ71uJPsSz9ilP3Y/branch/K6yhgXNpRikW3oKY4PTT3G/Core-icons?node-id=6967%3A5874&t=OoCx8XFWIcQE2Mtv-1). Si ifra hvis du trenger noe mer 😸
