### ISSUE TITLE
[BUG] knapp får div til å utvide seg når man laster spinner

### ISSUE THREAD

**Issue by hakonph** [navikt/Designsystemet#1800]
## Hva er feilen/problemet?
knapp får div til å utvide seg når man laster spinner

forventet oppførsel:
div rundt knappen er like stor om man har på loading eller ikke.
faktisk oppførsel:
div utvider seg når man setter på loading

## Steg for å reprodusere problemet (valgfri)
https://navikt.github.io/jumping-loding-button/
trykk på knappen "trykk på meg"
trykk igjen for å få tilbake til orgianl tilstand

reprodusert i firefox/safari/chrome på mac

## Eksempel/Tilleggsinformasjon (valgfri)
https://github.com/navikt/jumping-loding-button/blob/main/src/Eksample.tsx

**Comment by kschieren** [comment]
Takk for tilbakemelding!

Dette viste seg å være litt av en nøtt, så har ikke funnet feilen enda. I mellomtiden kan du sette display til f.eks flex på div elementet. Oppdaterer her så fort vi har en fix :)

**Comment by KenAJoh** [comment]
Hei, vi har bestemt å ikke løse dette for nå 😕 

Det kan virke som feilen oppstår siden sentreringen av begge knappene bestemmes av en baseline basert på teksten i selve knappen. Når teksten byttes ut med en SVG (Loader) blir baseline feil. 

Løsningen vi fant for nå var å sette `vertical-align` som overstyrer baseline, men dette vil potensielt brekke alle som har plassert `Button` i inline, inline-block eller table-cell elementer ([MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/vertical-align)) så vi ønsker helst å unngå dette og anbefaler for nå å bare bruke flexbox/grid for dette. 

Ønsker gjerne å høre hvis dere har funnet en god løsning på dette også!
