### ISSUE TITLE
[Nytt ikon]: Kode

### ISSUE THREAD

**Issue by eilifjohansen** [navikt/Designsystemet#1804]
### Navn på ikonet

code

### Eksempel på ikonet

Ikon for å representere kode. </>
Inpspirasjon: [Flaticon Code](https://www.flaticon.com/free-icon/code_3573187?term=code&page=1&position=16&origin=search&related_id=3573187)

**Comment by KenAJoh** [comment]
<img width="516" alt="Screenshot 2023-02-12 at 13 08 18" src="https://user-images.githubusercontent.com/26967723/218310157-d0806093-bdd4-41f4-943b-85ce0e6fd638.png">

Hei 👋 Ikonet er en del av en større ikon-oppdatering som kommer snart. For nå kan man denne SVG-en
```svg
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
	<path d="M14.5 8.5L18 12L14.5 15.5" stroke="#262626" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
	<path d="M9.5 8.5L6 12L9.5 15.5" stroke="#262626" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
</svg>

```
