### ISSUE TITLE
[Innspill til komponent]: <Popover />

### ISSUE THREAD

**Issue by Trent-NAV** [navikt/Designsystemet#1806]
### Tilbakemelding

Plasseringsvariantene finnes ikke i popover demoen men er kun angitt med tekst lengre ned på siden. Merker at folk lett overser komponentvarianter som ikke er vist i demo, særlig nye utviklere som ikke nødvendigvis har Figma referansen av komponentet der varianter er enkle å inspisere.

**Comment by KenAJoh** [comment]
Har lagt til en egen demo for plassering av popover i demo nå 🚀
