### ISSUE TITLE
[NEW] Endre Ikoner til egen kategori i startskjermen

### ISSUE THREAD

**Issue by ivoiv** [navikt/Designsystemet#1808]
## Hva?

I dag er kategoriene Komponenter, Styliing og Stæsj.
Forslår å lage en fjerde kategori, Ikoner og trekke den ut av Stæsj.

## Hva løser dette?

Når jeg går inn på askel.nav.no er som oftest hensikten å finne dokumentasjon til en ds-react komponent eller å finne et ikon.
At ikon-biblioteket er gravd under Stæsj gjør det mer vanskelig å finne frem, for navnet Ikoner ligger bare under detaljbeskrivelsen av hva Stæsj er for noe. Navnet stæsj forteller meg heller ingenting.

**Comment by KenAJoh** [comment]
Hei, vi blir å se på å lage en bedre ikonvisning etterhvert på kanskje `/ikoner`, men for å gjøre ikonsiden enda enklere å finne flyttet vi direktelenken hit nå slik at man ikke trenger å gå til grunnleggende først 😄 

<img width="824" alt="Screenshot 2023-02-14 at 15 24 06" src="https://user-images.githubusercontent.com/26967723/218766325-f4f670d8-33ac-4042-848f-ed617c49bd1d.png">
