### ISSUE TITLE
[Innspill til komponent]: <Button />

### ISSUE THREAD

**Issue by cskrov** [navikt/Designsystemet#1810]
### Tilbakemelding

Legge til støtte for `text-overflow: ellipsis` dersom teksten i knappen er for lang og tekst over flere linjer ikke passer.

En fungerende workaround for nå er å legge til følgende CSS;

```
.navds-label {
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
```

Å basere seg på at interne klasser og intern struktur i en komponent er stabilt er ikke ideelt.

**Comment by lmfaole** [comment]
Takk for innspill! 🙌

Det er to problemer vi fort vil møte på med en sånn løsning:
1. Noen apper på operativsystemer bruker ellipse på knapper allerede. Dette gjøres på Mac for eksempel, og der brukes det for å vise at du som bruker vil møte en dialog når du klikker på den. Dermed vil noen klikke på knappen uten å ta innover seg handlingen de gjør.
2. Å fjerne tekst i en knapp vil jo nødvendigvis bety at alle brukere går glipp av den fullstendige konteksten. Dermed får du samme problem som med punktet over, hvor er bruker ikke vet hva de klikker på.

Vi vet selvfølgelig ikke konteksten til problemet deres, men det finnes forhåpentligvis andre løsninger enn å tillate overflow i knappen. Det vil lage mer rom for feil bruk slik vi ser det.

Vis oss gjerne eksempler, så vi kan komme med noen praktiske løsninger!

**Comment by cskrov** [comment]
Konteksten vår er interne applikasjoner.

<img width="935" alt="image" src="https://user-images.githubusercontent.com/3177301/220164218-aa8a78cc-e186-4909-9fe2-2a70747bf1fc.png">

Vi har jobbet oss rundt problem 2 med `title` på knappene.
Om `title` ikke er nok kan man alltids bruke `Tooltip`.

For oss er det ikke kritisk at bruker ser 100% av teksten umiddelbart, og bruker kommer til å ta seg tiden til å lese hele teksten ved behov.
Det er stort sett snakk om lister av dokumenter i våre tilfeller, der dokumenttittelen er en knapp.

Om problemene dere nevner er uakseptable for `ds-react`, kan vi foreslå en intern versjon av `Button` i `ds-react-internal` med litt mer fleksibilitet?

**Comment by ivoiv** [comment]
@cskrov 
Kan anbefale [react-multiline-clamp](https://www.npmjs.com/package/react-multiline-clamp) biblioteket.
Veldig lett å bruke og det gjør akkurat det du ber om.  Bruker det selv overalt. 

F.eks dette
```
    <Button style={{ width:200px }} >
      <Clamp lines={2}>
        Primary Primary Primary Primary Primary Primary Primary Primary PrimaryPrimary Primary Primary Primary
      </Clamp>
    </Button>
``` 

vil skape dette 
![image](https://user-images.githubusercontent.com/11502345/222145829-60af63f0-ee83-40a3-bf5c-bf717c9254f7.png)

Sandbox demo:
https://codesandbox.io/s/dreamy-perlman-cpsjo4?file=/App.js
