### ISSUE TITLE
[NEW] Unngå enker for bedre typografi

### ISSUE THREAD

**Issue by macbruker** [navikt/Designsystemet#1814]
## Hva?

Noen ganger ser det litt kjipt ut med et enkeltord som står på egen linje. Fagbegrepet for slike ord er «enke». 

![image](https://user-images.githubusercontent.com/1032194/220325155-86e23d2d-c879-4301-8788-107328108c03.png) 
![image](https://user-images.githubusercontent.com/1032194/220325658-955cf04d-8070-4bc4-a40e-f10e28b2bdee.png)

## Hva løser dette?

For å unngå «enker» kan man erstatte det vanlige mellomrommet med et mellomrom som ikke bryter til ny linje. Koden for dette kan skrives selv, eller det er mulig å ta i bruk en pakke. 

## Eksempler/Info

Her er et forslag til pakke: https://www.npmjs.com/package/widont

**Comment by KenAJoh** [comment]
👀 

Testet litt forskjellige npm-pakker, men ser ut som vi evt må lage en custom parser for dette hvis vi ønsker å løse det i React med dataen vi får fra Sanity. Kunne vært kult å fått fikset, men usikker på hvor komplekst det ville vært å løse for alle modulene vi tar inn fra Sanity. Legger det på TODO-lista 👍 

Eks data
```
{
  children: [
    'Litteraturen snakker gjerne om ',
    {
      '$$typeof': Symbol(react.element),
      type: [Function: SpanSerializer],
      key: '2ba4added09f1',
      ref: null,
      props: [Object],
      _owner: null,
      _store: {}
    },
    '. I NAV bruker mange uttrykket ',
    {
      '$$typeof': Symbol(react.element),
      type: [Function: SpanSerializer],
      key: '2ba4added09f3',
      ref: null,
      props: [Object],
      _owner: null,
      _store: {}
    },
    ': folk som av en eller annen grunn står i en sårbar situasjon. Dette kan være mennesker som opplever økte ulemper, stress eller diskriminering på grunn av kjønn, legning, utseende, økonomi, alder, hudfarge, etnisitet, religion, funksjonsevne eller kriminell status. Uavhengig av sårbarheter, kan mange av NAVs brukere stå i vanskelige situasjoner. Derfor snakker vi i dag mye om livshendelser og konkrete brukssituasjoner. Disse kalles ',
    {
      '$$typeof': Symbol(react.element),
      type: [Function: SpanSerializer],
      key: '2ba4added09f5',
      ref: null,
      props: [Object],
      _owner: null,
      _store: {}
    },
    '.'
  ]
}
```
