### ISSUE TITLE
[Ny komponent]: 

### ISSUE THREAD

**Issue by Hallaraker** [navikt/Designsystemet#1815]
### Navn på komponent

Smilefjes til temperaturmåling

### Eksempel på komponenten

Smilefjes til temperaturmåling. Emojis for å hente inn tilbakemelding fra brukere.

**Comment by lmfaole** [comment]
Jeg skal annonsere at vi kommer med ny ikonpakke snart, hvor smilefjes er med! 😻

**Comment by sjur-gr** [comment]
Nye ikoner er ute https://aksel.nav.no/ikoner
