### ISSUE TITLE
[Innspill til komponent]: <HelpText />

### ISSUE THREAD

**Issue by Trent-NAV** [navikt/Designsystemet#1824]
### Tilbakemelding

 I saksbehandlingsmiljøer med tight UI er HelpText veldig utbredt så jeg tenkte jeg skulle være litt føre var her, på Aksel står det "_HelpText er en komponent som skal fases ut på sikt. Vi anbefaler heller å bruke ReadMore, eller lenke til en annen side_." Ser ikke helt hvorfor det er ønske om å fase ut et komponent som brukes såpass mye uten at det finnes noe oppgradert versjon eller høvelig alternativ. Det å linke til annen side er nesten alltid et hardt brudd med saksflyten. ReadMore erstatter ikke HelptText på noe måte og innfrir helt andre brukskontekster.

**Comment by lmfaole** [comment]
Det er en av komponentene vi ser at det er størst sjanse for feil bruk. Det er grunnen til at vi er såpass direkte med å anbefale en annen komponent. 

Vi kan endre teksten så den spesifiserer at den vurderes i det minste å flyttes til interne flater? @sjur-gr

**Comment by Trent-NAV** [comment]
> Det er en av komponentene vi ser at det er størst sjanse for feil bruk. Det er grunnen til at vi er såpass direkte med å anbefale en annen komponent.
> 
> Vi kan endre teksten så den spesifiserer at den vurderes i det minste å flyttes til interne flater? @sjur-gr

Vet ikke helt hva du mener med feil bruk, men husker fra min tid i DS at vi ønsket å formidle at HelpText ikke skulle bli et "sekkekomponent" for all mulig informasjon. Men her tror jeg DS bare burde skrive en bruksanmodning, på samme måte som med andre komponenter, men det vil være de ulike teamenes behov for å bruke HelpText som må trumfe. Når jeg observerer den i kontekst av Pesys så er den brukt riktig og løsningsorientert og det er min oppfatning av den når jeg ser den også i andre saksbehandlingssystemer.  Det finnes ingen reell erstatning, jeg tror den fyller en funksjon og reduserer faren for at folk lager seg andre mindre heldige improviserte løsninger, eller simpelthen en egen HelpText kopi i eget bibliotek, men lokale komponenter er alltid siste utvei da vi jo alle ser fordelen av å ha sentrale komponenter fra Aksel.

**Comment by sjur-gr** [comment]
Vi kan endre teksten her ja. Tror ikke vi får jobbet med en justering eller alternativ med det første. Det finnes sikkert gode argumenter og situasjoner hvor det er helt ok å bruke denne på åpne/innlogga flater også. Dok’en er ganske tydelig på mengde innhold. Vi kan trekke fram flere ting som bør være med i vurderingen om den skal brukes. Eks. lite kontroll på plassering og lukking, utfordringer med scrolling på mobil om popover blir stor. Om jeg skal tenke høyt kan modal eller dynamisk sidepanel være alternativer som gir bruker og oss mer kontroll.

**Comment by sjur-gr** [comment]
Dokumentasjonen er endret. Nå beskrives komponenten som den er, og vi utdyper hva man må være oppmerksom på når man bruker komponenten.
