### ISSUE TITLE
[Innspill til komponent]: <Table> - Støtte for Hyphens og orddeling

### ISSUE THREAD

**Issue by ivoiv** [navikt/Designsystemet#1825]
### Tilbakemelding

Dersom du vil få til ordentlig orddeling ved å bruke hyphens og `&shy;` må du bruke `dangerouslySetInnerHTML` på f.eks. `Table.ColumnHeader` for å manuelt sette inn HTMLen, ellers rendres det som en del av teksten.

Dette går fint, men når man i tillegg har `sortable=true` crasher tabellen med
`Error: Can only set one of children or props.dangerouslySetInnerHTML` 

Dette fordi en `<button>` blir nå satt inn i tabell headeren fremfor tekst/html og den blir tilsendt noe slags `children` i tillegg til `dangerouslySetInnerHTML`, selv om man ikke gir noen children til `Table.ColumnHeader`

Er det noe vi funne tillatt på noen måte?
Ser i dag at knappen er lagt opp slik

```
<button>
   {children}
   <svg>
<button>
```

Kunne vi endret det til noe sånt ?

```
<button>
   {dangerouslySetInnerHTML
       ? <span dangerouslySetInnerHTML={dangerouslySetInnerHTML}/>
       : {children}
   }
   <svg>
<button>
```
Da kan man fremdeles bruke innerHTML på sortable når det er behov for det.

**Comment by KenAJoh** [comment]
Hei, har du noen eksempler på hvordan det ville sett ut hvis det rendres som en del av teksten? Testet dette selv med unicode og virket som det fungerte, men kan hende jeg misforstod problemet.
https://codesandbox.io/s/cranky-shaw-23bo6c?file=/src/App.js

```
  const text = `before\u00ADafter`

  return (
    <div className="App">
      <button style={{maxWidth:60}}>{text}</button>
    </div>
  );
```

**Comment by ivoiv** [comment]
Det var et veldig godt poeng!
`\u00AD` fungerer helt fint! 
Det er bare jeg som er gammeldags som bruker `&shy;`
