### ISSUE TITLE
[Innspill til komponent]: DropDown - prop for open/closed state

### ISSUE THREAD

**Issue by ivoiv** [navikt/Designsystemet#1831]
### Tilbakemelding

Det er per i dag ikke mulig å stille inn om Dropdown menyen er open eller lukket, kun DropDown.Toggle kan endre open/closed state. 
Dette gjør det umulig å få Dropdown til å åpne seg ved en annen hendelse eller starte med den åpen. 

Er det mulig å legge til en `open: boolean` prop som vi kan styre selv?

**Comment by sjur-gr** [comment]
Det gir mening. Vi skal se på det 👍
