### ISSUE TITLE
[Tilbakemelding på ikon]: Nye logiske navn på ikoner

### ISSUE THREAD

**Issue by Camulos** [navikt/Designsystemet#1839]
### Tilbakemelding

Forslag nye navn som beskriver hva ikonene er og ikke hvordan de brukes/tolkes i en enkelt kontekst

Navn i dag -> forslag nytt navn (Synonymer)
•	Disability -> Wheelchair (Disability)
•	Back -> Chevron-left (Back)
•	Collapse -> Chevron-up (Collapse)
•	Next -> Chevron-right (Next, Continue)
•	Expand -> Chevron-down (Expand)
•	Left -> Arrow-left (Left)
•	Up -> Arrow-up (Up)
•	Right -> Arrow-right (Right)
•	Down -> Arrow-down (Down)
•	Home -> House (Home)
•	Email -> Envelope (Email)
•	EmailOpened -> Envelope-open (Email-opened, Open-envelope)
•	Data -> Bar-chart (Data, Data1)
•	Divide -> Pie-chart (Data-alt, Data2)
•	Search -> Magnifying-glass (Search)
•	SocialAid -> Hand-holding-heart (Social-aid, Volunteer, Give-heart)
•	Add -> Plus (Add)
•	AddCircle -> Plus-circle (Add-circle)
•	Close ->  X-mark (Close, Times)
•	Minus (Subtract)
•	MinusCircle (Subtract-circle)
•	Helptext -> Question-circle (Helptext, Questionmark-circle)
•	NorwegianFlag -> Cross-flag (Norwegian-flag, Swedish-flag, Danish-flag, Finish-flag, Icelandic-flag, ETC...)
•	People -> Person (People, One-person, Profile)
•	PeopleInCircle -> Person-circle (People-in-circle, Profile-circle)
•	Selection -> Finger-pointing-up (Selection)
•	SelfService -> Finger-push (Finger-button, Self-service)
•	Settings -> Cog (Settings, Cogwheel)
•	System -> Waffle (System, Settings2, Settings-alt, Menu2, Menu-alt)
•	Translate -> Language (Glyph, Translate, Language-select)
•	Attachment -> Paperclip (Attachment)
•	Bell (Notification)
•	Picture (Image)
•	Applicant -> Person-letter (User-envelope)
•	Caseworker -> Person-pencil (User-pencil)
•	CoApplicant -> Person-group (User-group)
•	Decision -> Person-gavel (User-gavel)
•	DecisionCheck -> Person-check (User-check)
•	DecisionCross -> Person-cross (User-cross)
•	Emplyer -> Person-suit (User-suit)
•	Service -> Person-headset (User-headset)
•	SingleParent -> Adult-child
•	Locked -> Padlock-locked (Locked)
•	Unlocked -> Padlock-unlocked (Unlocked)

**Comment by sjur-gr** [comment]
I den nye ikonpakka vi jobber med bruker vi sånne navn. Vi skal ta med oss navnene du bruker her 👍

**Comment by sjur-gr** [comment]
Ny ikonpakke er ute 🎉
