### ISSUE TITLE
[Tilbakemelding på ikon]: Ikoner som savnes

### ISSUE THREAD

**Issue by Camulos** [navikt/Designsystemet#1842]
### Tilbakemelding

Savner noen ikoner, for å unngå at jeg lager svg-ene for dem som andre allerede holder på med, så ville det vært fint å vite hvilke som blir laget av dere i NAV og hvilke jeg kan ta å så sende inn som Pull-requests. Har dere noen slik oversikt?

•	Caret-left/up/right/down
•	Caret-filled-left/up/right/down
•	Sort
•	Sort-up/down
•	Sort-up-mark
•	Sort-down-mark
•	File-PDF
•	File-word
•	File-spreadsheet
•	File-code (filikon med <> e.l.)
•	File-csv
•	File-json
•	File-rotate
•	File-reset
•	X-mark-circle
•	Spinner (loading, loader)
•	File-import
•	File-export
•	Mediakontrollere (play, pause, fast-forward, step-forward, etc...)
•	Envelope-money (med kr og med $)
•	Left-right-arrow (tilsvarer UpDown)

**Comment by sjur-gr** [comment]
Vi har lagd disse ikonene i den nye pakka. De er klare i Figma nå. Klare i kode snart.

**Comment by lmfaole** [comment]
[Lenke her](https://www.figma.com/community/file/1214869602572392330) 😸

**Comment by Camulos** [comment]
Tar en ny gjennomgang og ser om ikonsettet nå dekker behovene her i BR :) 
Btw: Ville vært veldig hjelpsomt om det i Figma-fila var en ferdig komponent med alle ikonene i.

**Comment by lmfaole** [comment]
Å legge til en komponent i Core UI Kit som var en platehilsen som lar deg velge mellom ikonene tenkte du? 💡

**Comment by Camulos** [comment]
Figma-komponent med alle ikoner som nestede varianter, nå er hvert ikon sin egen komponent men det er ingen som samler dem for enkel bruk i andre skisser og komponenter.

**Comment by lmfaole** [comment]
Det høres for meg ut som en litt komplisert rigg, når det egentlig [kan gjøres med swapping av instances](https://help.figma.com/hc/en-us/articles/360039150413-Swap-components-and-instances). 

Er det noen fordeler jeg ikke ved om med denne typen rigg, mot det Figma beskriver i den artikkelen?

**Comment by Camulos** [comment]
Fungerte ikke veldig bra sist jeg testa det, men det ser ut til å være litt bedre nå. Noen ikoner er ikke forhåndssatt for scaling (de har feks mixed istedet) opplevde jeg nå, men det er kanskje ikke så mange av dem det gjelder.
Takk for tips.

**Comment by Camulos** [comment]
Har sjekket på nytt hvordan ikonene i pakken passer med behovene våre og det er nå kun en liten håndfull som savnes:
* Filled versjon av Sort / Caret typene, inkl at kun opp eller ned er filled for CaretDownUp
* Kan hende vi trenger sirkelversjoner av utropstegn og Info.
* Denne er litt tricky, vi trenger et symbol for "sak er på vent" stoppeklokke og venterom er begge i ballparken, men ikke helt.
* Vi trenger en variant av "copy" for "lag sladdet kopi/versjon av dokument"
* Download / Upload versjoner for Cloud og for Harddrive

Noen konkrete:
* Inbox
* ShoppingBasket
* FileXml
* FileJson

Noen av disse på vei eller allerede lagt til siste dagene?

**Comment by lmfaole** [comment]
Vi kommer ikke til å tilby sirkelversjoner av statusikonene våre. Bakgrunnen for dette er beskrevet i [bloggposten som kunngjør ikonene](https://aksel.nav.no/produktbloggen/vi-lanserer-ny-ikonpakke). @sjur-gr kan fylle på med informasjon om de andre ikonene du nevner 😸

**Comment by sjur-gr** [comment]
Yes. Vi får ut disse ikonene straks:

- CaretUpDownFilledDown
- CaretUpDownFilledUp
- CloudDown
- CloudUp
- HddDown
- HddUp
- Inbox
- InboxDown
- InboxUp
- ShoppingBasket

Ikon for "sak er på vent" og "lag sladdet kopi/versjon av dokument" må vi sjekke internt før vi lager.

**Comment by sjur-gr** [comment]
Avslutter saken nå. Om vi får opp saken om ikonene som mangler internt så oppdaterer vi ikonpakka.
