### ISSUE TITLE
[Innspill til komponent]: <Search> ny onSearch prop

### ISSUE THREAD

**Issue by ivoiv** [navikt/Designsystemet#1843]
### Tilbakemelding

Akkurat nå har <Select> bare onChange som trigges hvert tastetrykk.

Kan vi få et event, onSearch som trigges når man clicker på søk-knappen med verdien fra feltet som parameter?

Alternativene i dag er enten å ha en form rundt Search knappen og fange opp send hendelsen der, eller ha en custom wrapper rundt Search, en custom knapp, koble knappen til Search via en Ref og så hente ut value ved trykk på knappen.
Begge synes jeg er litt tungvinte løsninger.

**Comment by KenAJoh** [comment]
Hei, man kan løse dette med en `useState` i dagens løsning slik: https://codesandbox.io/s/friendly-sammet-e7m2d1?file=/App.js 🤞

**Comment by ivoiv** [comment]
Slik jeg anser det er hovedfunksjonen i Search å trigge et søk med verdien i text-feltet når man trykker på Søk-knappen.

At man må implementere useState, onChange, onClear og onClick funksjoner, for å kunne fange opp innholdet i text-feltet ved trykk på Søk, synes jeg går imot intensjonen med komponenten, introduser unødvendig kodestøy og gjør det tungvint å jobbe med.

Hva er fordelen med Search kontra en TextField, dersom alt dette må til for å få den til å fungere?

Alt jeg har lyst til å gjøre er
`<Search label="Søk" onSearch={(value => handleSearch(...))} />`

**Comment by KenAJoh** [comment]
Fikset i 2.6.1 🚀 
https://github.com/navikt/aksel/releases/tag/%40navikt%2Fds-react%402.6.1
