### ISSUE TITLE
Vise en til flere hendelser for samme periode i samme rad: <Timeline />

### ISSUE THREAD

**Issue by shamilmagamt** [navikt/Designsystemet#1844]
### Tilbakemelding

Eksempel på stack av hendelser som har skjedd i samme periode i samme rad: 
![image](https://user-images.githubusercontent.com/107405413/223426824-368a3752-31b3-4ff2-9d42-ce43948c7647.png)

Nå vil hendelser som har skjedd i samme periode på samme rad overskrive hverande (ligge på toppen av hverandre)

**Comment by Lilyngs** [comment]
Takk for innspill på dette behovet for tidslinjen. Vi vil vente med å utforske denne muligheten til vi har mer innsikt rundt komponenten. Men vi tar med oss innspillet og vurderer muligheten for å bygge den ut videre hvis flere har lignende behov.
