### ISSUE TITLE
[Nytt ikon]: Felgen

### ISSUE THREAD

**Issue by eilifjohansen** [navikt/Designsystemet#1854]
### Navn på ikonet

Felgen

### Eksempel på ikonet

Felgen, NAV IT-snarveier trenger et ikon / logo til oppføringen i webapps.nav.no. Kan dere hjelpe oss med å lage denne?

Ide 
- Felgen til et bildekk med Aksel stil

**Comment by Lilyngs** [comment]
Vi hjelper til :) Sender en pm

**Comment by KenAJoh** [comment]
Felgen har eget ikon nå, så lukker denne.
