### ISSUE TITLE
[Innspill til komponent]: <Popover />

### ISSUE THREAD

**Issue by Trent-NAV** [navikt/Designsystemet#1857]
### Tilbakemelding

Tekststørrelsen på Popover burde ha en Small variant for interne flater med BodyLong/Small (16px) og ikke kun BodyLong/Medium slik det er nå. Med 18px tekst fremstår den ubalansert og dominerende i UI som kun benytter BodyShort/Small som body type.

**Comment by KenAJoh** [comment]
Hei :wave: Når det kommer til komponenter som ikke har en size-prop for medium/small, ønsker vi å unngå å legge til dette bare for typografi. I de fleste tilfellene vil utvikler kunne enkelt wrappe alt innholdet for den størrelsen de ønsker. Er dette for det meste et figma-problem eller figma + kode?
```
<Popover>
  <BodyLong size="small">
    ...alt innhold
  </BodyLong>
<Popover>
```

**Comment by Trent-NAV** [comment]
> Hei 👋 Når det kommer til komponenter som ikke har en size-prop for medium/small, ønsker vi å unngå å legge til dette bare for typografi. I de fleste tilfellene vil utvikler kunne enkelt wrappe alt innholdet for den størrelsen de ønsker. Er dette for det meste et figma-problem eller figma + kode?
> 
> ```
> <Popover>
>   <BodyLong size="small">
>     ...alt innhold
>   </BodyLong>
> <Popover>
> ```

Jeg skal ikke si for sikkert men om det ikke finnes en size-prop for Small på et komponent så er mitt inntrykk at utviklerne bruker det som ligger tilgjengelig default, det er ikke alltid ting itereres i felleskap i Figma i forkant. Om det derimot er felles iterasjon mellom designer og utvikler så er det fint å vite at en Medium prop på typografi enkelt kan endres til Small på eget initiativ uten at dette påvirker det systemorienterte konseptet med DS. Om det ikke finnes Small versjon i DS native utrykket så kan det fort bli implementert uten om det er selvstendig produksjon av noe av en utvikler. Jeg er ikke så kjent med way of work for endring av dette i kode, men det er også mitt inntrykk at utviklerne aller helst vil ha alle komponentvariantene tilgjengelig "rett fra boksen", men det kan være tekniske faktorer eller premisser her som jeg ikke kjenner.

Når det gjelder det som angår Figma er vi nødt til å ha Small variantene for IF får å unngå at det blir for mange selvstendige versjoner, det er derfor jeg etterlyser Small varianter og etterspør Small typografi etc. der dette ikke finnes. Et Figma komponent må være utstyrt med alle props som DS har tiltenkt komponentet, da kan vi også enklere kommunisere med DS med opphav i  autentisk data. Jeg syns at komponent strukturen i Figma og DS/Aksel burde speile hverandre mest mulig.

**Comment by sjur-gr** [comment]
Popover har ingen strenge regler for innhold annet enn å unngå mye informasjon. I Figma har vi lagd den med suffix [detachable], som betyr at du kan frakoble komponenten og styre innholdet selv. Jeg ser at vi kan skrive noe om det i dokumentasjonen. Det er ikke noe problem at du endrer til BoadyLong.Small (da trenger du heller ikke detache komponenten)
