### ISSUE TITLE
Tab-komponent: Ekstra steg ved tastaturnavigasjon gjør at fokus tilsynelatende forsvinner

### ISSUE THREAD

**Issue by terjeofnorway** [navikt/Designsystemet#1859]
## Hva er feilen/problemet?

Ved tab-navigasjon til Tab-komponent settes fokus på første fane-tab. Dersom man trykker tab-tasten én gang til så forsvinner fokusmarkeringen. For å komme til neste opplagte interaktive eller fokuserbare element, enten inne i fanen eller lenger ned så må man taste tab én gang til.

Ved å inspisere elementene ser jeg at fokus er satt på selve fane-innholdet (se screenshot). Dette gjelder også selv om det ikke finnes noen interaktive elementer (dvs kun paragrafer med tekst) inne i panelet.

Det kan hende at dette er nødvendig oppførsel for at skjermleser skal formidle kontekst korrekt, men for meg som seende og som allikevel ønsker å bruke tastaturnavigasjon så virket det rart at fokus tilsynelatende forsvinner og at jeg må tabbe én ekstra gang.

## Steg for å reprodusere problemet
1. Tast tab til første fane.
2. Tast tab én gang til.
3. Visuelt fokus har forsvunnet, men man kan se at hele fanen er i fokus ved å sjekke document.activeElement i console.

## Eksempel/Tilleggsinformasjon 
<img width="1115" alt="Screenshot 2023-03-15 at 16 08 29" src="https://user-images.githubusercontent.com/1443997/225352950-8a10cf15-6e8d-429f-afde-dda8471495b9.png">

**Comment by it-vegard** [comment]
Her vil jeg hevde at oppførselen (tab-stops) er korrekt, men at feilen er at vi ikke har fokusmarkering på tabpanelet.

Ser beskrivelse av forventet oppførsel hos MDN: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tab_role#keyboard_interaction

Skal få ordnet fokusmarkering i løpet av dagen.

**Comment by it-vegard** [comment]
Hei @terjeofnorway!

Nå har vi fikset fokusmarkering for tab-panelet. 

Endringen er allerede ute på [Aksel.nav.no](https://aksel.nav.no/komponenter/core/tabs), og er inkludert i versjon 2.7.8 av npm-pakkene, som er ute i GitHub Package Registry, og snart er rullet ut i npmjs.com/yarnpkg.com. 

Oppførselen for komponenten er altså at man får en tab-stopp for tab-listen (knappene), og en for tab-panelet, men nå med skikkelig fokusmarkering. Bytte av tab styres med piltaster.

Takk for at du gjorde oss oppmerksom på denne feilen!
