### ISSUE TITLE
[Innspill til komponent]: <Accordion />

### ISSUE THREAD

**Issue by EspenSteinum** [navikt/Designsystemet#1860]
### Tilbakemelding

Denne komponenten har i Figma en border på topp av den øverste panelet i en liste. Dette mangler i dokumentasjonen i Aksel, og muligens også i koden.

**Comment by sjur-gr** [comment]
Ja, den har sneket seg ut litt tidlig. Sorry for det. Vi skal justere Accordion litt nå samtidig som vi får ut ExpansionCard. Da blir det likt på Aksel, i Figma og i kode.

**Comment by sjur-gr** [comment]
Nytt design er ute nå
