### ISSUE TITLE
[Innspill til komponent]: <HelpText />

### ISSUE THREAD

**Issue by Trent-NAV** [navikt/Designsystemet#1861]
### Tilbakemelding

HelpText kunne hatt Small variant med BodyShort/Small og 16x16px ikonstørrelse, det gjør den mer plasseringsvennlig. Her er en reel kontekst hvor ikonstørrelsen er endret fra 24x24px til 16x16px men teksten bevisst beholdt default for å demonstrere utfordringen i denne henvendelsen. I compact UI settinger er det alltid praktisk med Small varianter og igjen er det best å ha det sentralt i DS istedenfor å lage lokale justeringer.  

![helptxt_active](https://user-images.githubusercontent.com/86958516/225619179-7b132da6-01dd-471c-9d14-430c8c8f8514.png)

![helptxt_default](https://user-images.githubusercontent.com/86958516/225619183-f2525998-ec10-4752-a9b6-5aaac60f0e53.png)

---------------------------------------------------------------------------------------------------------------------------

Her er originalutrykket på HelpTxt i samme kontekst. Det blir for dominant med våre Small tables, så det hadde vært fint med en Small variant av komponentet 😀 

![helptxt_active_default](https://user-images.githubusercontent.com/86958516/225628464-f457f282-5ddb-4c61-a6c4-07e7c17c4e40.png)

**Comment by sjur-gr** [comment]
UU-kravet er i minimum 24x24 px for et target, men det er unntak. Om target (ikonet) er 16x16px må avstanden til andre klikkbare ting være minst 8px. Kan du teste det ut og se om det funker for brukerne?

**Comment by Trent-NAV** [comment]
> UU-kravet er i minimum 24x24 px for et target, men det er unntak. Om target (ikonet) er 16x16px må avstanden til andre klikkbare ting være minst 8px. Kan du teste det ut og se om det funker for brukerne?

Setter alltid hit area litt opp i forhold til elementet. Det går fint i 32px table header. Når det gjelder spacing går det greit med 8px. I eksemplet er det vel 6px men går fint å øke. En Small versjon som beskrevet vil passe bra 👍

### Litt produktinfo
Brukerne i Pesys er vant til enda mindre elementer og mer kompakt UI enn det jeg designer i nå, de må nemlig forholde seg til to versjoner samtidig grunnet plattform avhengigheter. Den delen av systemet som ligger på JSF plattform er ikke React kompatibel. Det originale designet som ligger der ble laget i 2009 og er myntet på fordums skjermoppløsninger, når det brukes i dag på høyere skjermoppløsning så er det små interaksjonselementer å forholde seg til. Såkalt "nytt design" skjer på den delen av systemet som har React kompabilitet. Vi har stegvis fornyet skjermbildene på plattformen som gjør det mulig å koble på DS og vi prioriterer designfornyelse kun på den. Brukerne våre (snaut 800 saksbehandlere) må dog forholde seg til nytt og gammelt design om hverandre i overskuelig fremtid inntil hele Pesys re-designes totalt på felles plattform.  

Det "nye designet" med DS komponenter blir oppfattet som stort for mange saksbehandlere av overnevnte årsak, tabellene er større enn i den eldre eksisterende versjonen selv i Small variant, bodyteksten er større etc. Det er en tilvenningssak for dem å akseptere mer scroll og mer luft, men vi ser kun fremover og forsøker å være apostler for systemdesign og kommunisere gevinstene for bedre UU m.m. Jeg tror mantraet bør være å lage Small versjoner av alle DS komponenter, vi jobber for WCAG 2.1 AA kompabilitet også i Pesys, hadde vært supert om vi kunne være helt DS native på komponentnivå og da trengs kompakte varianter. Skriv gode brukstekster i Aksel så sikres god implementasjon. Vi forsøker å trekke veksler på felles UU ressurser som UU teamet så ofte vi kan også 😀

**Comment by Trent-NAV** [comment]
@sjur-gr Plukker opp tråden fra mars. Vi håper fortsatt at komponentet kan få en Small variant i Aksel istedenfor at vi fristiller den. 16x16 vector size i en 24x24 container fungerer bra med compact UI brukerne for flere andre funksjonelle ikoner vi benytter i dag.

**Comment by sjur-gr** [comment]
Ikke noe nytt dessverre. Jeg legger den på tavla til neste uke.

**Comment by KenAJoh** [comment]
@sjur-gr Small-variant demo: https://5f801fb2aea7820022de2936-epcyjttily.chromatic.com/?path=/story/ds-react-helptext--sizes
PR: https://github.com/navikt/aksel/pull/2376
Spm jeg har her er om man ikke bør tilby en prop "size" men heller bare sette 20x20px icon som default for alle? 🤔

**Comment by Trent-NAV** [comment]
@KenAJoh BodyshortSmall i active state krever vel en egen Small prop for text size?

**Comment by KenAJoh** [comment]
> @KenAJoh BodyshortSmall i active state krever vel en egen Small prop for text size?

Dette blir styrt av utvikler ved å endre wrapper inne i HelpText
```tsx
<HelpText>
    <BodyLong size="small">
        Innhold
    </BodyLong>
</HelpText>
```

**Comment by Trent-NAV** [comment]
> > @KenAJoh BodyshortSmall i active state krever vel en egen Small prop for text size?
> 
> Dette blir styrt av utvikler ved å endre wrapper inne i HelpText
> 
> ```tsx
> <HelpText>
>     <BodyLong size="small">
>         Innhold
>     </BodyLong>
> </HelpText>
> ```

Men i Figma blir det mest praktisk å kunne prototype med autentisk tekststørrelse med en size variant. Mulig jeg misforsto deg, for jeg tenker på Figma versjonen av komponentet. Så hvis ikonet er felles 20x20 så har den en size prop / variant med BodyshortSmall for active text, slik at rett tekstørrelse blir brukt i prototypene og at dette også fremkommer når utviklerne bruker Devmode i Figma og inspiserer skisser og prototyper der.
