### ISSUE TITLE
[Innspill til komponent]: <ExpansionCard />

### ISSUE THREAD

**Issue by Trent-NAV** [navikt/Designsystemet#1869]
### Tilbakemelding

Fint at det er laget en Small variant men ser at den kun reduserer paddingen noe, savner redusert bodytekst størrelse. Vi bruker ikke BodyLong/Medium til noe men har BodyLong/Small som standard, det er det mange saksbehandlingssystemer som har. Ser det er innebygget component variant på Title til Heading/Desktop/Small, så for å følge opp logikken der burde BodyLong/Small være en egen variant for bodytype eller description om den ikke inkluderes automatisk i Small varianten for hele komponentet.

**Comment by sjur-gr** [comment]
Godt poeng. Det fikser vi.

**Comment by sjur-gr** [comment]
Endringen er publisert i Figma

**Comment by Trent-NAV** [comment]
Supert, takk 😀
