### ISSUE TITLE
[Ny komponent]: Skeleton / Progress bar

### ISSUE THREAD

**Issue by ivoiv** [navikt/Designsystemet#1873]
### Navn på komponent

Skeleton / LinearLoader

### Eksempel på komponenten

Hadde vært kult med en sånn "progress bar", en blanding mellom MUI sine [Skeleton](https://mui.com/material-ui/react-skeleton/) og [LinearProgress](https://mui.com/material-ui/react-progress/#linear) som kan stå som en placeholder for datafelter som lastes inn.

Det hadde passet godt til innhold som kommer fra forskjellige API, slik at man slipper å skjule hele komponenten bak en felles Loader mens data lastes inn, men heller vise til ting fortløpende.
Man kan også sørge for at innholdet skifter minst mulig på nettsiden under/etter innlasting.

Man kan teknisk sett oppnå det samme med dagens Loader, bare at det ikke er like pent med en sirkel kontra en rett linje

**Comment by sjur-gr** [comment]
Vi har noen løse tanker på det her https://github.com/navikt/aksel/pull/1821

**Comment by ivoiv** [comment]
Supert, gleder meg til å se resultaten etterhvert. :)

**Comment by KenAJoh** [comment]
Her er forresten også demo: https://skeleton-komponent--5f801fb2aea7820022de2936.chromatic.com/?path=/story/ds-react-skeleton--shapes

**Comment by KenAJoh** [comment]
Skeleton er publisert 🎉 
https://aksel.nav.no/komponenter/core/skeleton
