### ISSUE TITLE
[BUG] Select får blå text color på iPhone

### ISSUE THREAD

**Issue by otenav** [navikt/Designsystemet#1878]
## Hva er feilen/problemet?
`<Select>` får blå tekstfarge når jeg bruker iPhone. Jeg forventet at Select fikk samme tekstfarge som `--a-text-default`.

Når jeg inspiserer select-boksen i egen applikasjon, så har den fått `color: fieldtext;` og dette kommer fra `user agent stylesheet`.

Derimot, når jeg sjekker select-boksen på https://aksel.nav.no/eksempler/select/default, så er det `color: inherit;` og denne ser ut til å komme fra en tailwind.css reset fil.

For meg ser det ut som at ds-css inkulderer normalize.css. Og de har et github issue som ligner. I det tilfellet gjelder det button, men jeg regner med at det er samme løsning for select.

## Steg for å reprodusere problemet
- Åpne https://arbeidsplassen.nav.no/stillinger på iPhone
- Sjekk Select-boksen kalt Sortér etter
- Se at select-boksen har blå tekst-farge

## Skjermbilde av hvordan det ser ut på iPhone i stillingsøket

![IMG_1090](https://user-images.githubusercontent.com/29566394/228471124-23951173-385b-4070-b22d-9c348379e8e6.png)

## Skjermbilde av hvordan det ser ut på iPhone på Aksel
![IMG_1091](https://user-images.githubusercontent.com/29566394/228471349-eda623ec-e056-476c-9861-da955d686b75.png)

**Comment by KenAJoh** [comment]
Hei, bør være fikset i v2.8.5 da 🤞 
La også til noen tokens for accordion-header for lettere styling av dem (så dere brukte accordion på arbeidsplassen)

```
--ac-accordion-header-bg: --ac-surface-transparent
--ac-accordion-header-bg-hover: --ac-surface-transparent
--ac-accordion-header-bg-open: --ac-accordion-item-bg-open
--ac-accordion-header-bg-open-hover: --a-surface-action-subtle
```
