### ISSUE TITLE
[Innspill til komponent]: <Radio />

### ISSUE THREAD

**Issue by macbruker** [navikt/Designsystemet#1881]
### Tilbakemelding

Ser at **description** i spørsmål og **description** i hvert svaralternativ har ulik linjeavstand. Dette gjelder både Figma og kode.

* _BodyLong/Small_ i spørsmål
* _BodyShort/Small_ i svaralternativ

Jeg foretrekker BodyLong/Small i begge. Om det skal gjøres endringer, er det sikkert lurt å sjekke Checkbox også 🙂 

---

Savner også et eksempel i dokumentasjonen med **description** i svaralternativene.

**Comment by KenAJoh** [comment]
Bør være fikset i v2.8.7 snart da 🚀
