### ISSUE TITLE
[BUG] Tekstfarge på Chip.Toggle lar seg ikke overstyre med token

### ISSUE THREAD

**Issue by otenav** [navikt/Designsystemet#1882]
## Hva er feilen/problemet?

Tekstfarge på `Chip.Toggle` lar seg ikke overstyre med tokens. Dette gjelder kun når toggle ikke er valgt. Når toggle er valgt, da kan man overstyre tekstfarge med `--ac-chip-toggle-pressed-text`. 

Ønsker å unngå å måtte overstyre på denne måten
```
.navds-chips__toggle[aria-pressed="false"] {
  color: var(--arb-blue-500) !important; 
}
```
Men heller si noe sånn som dette
```
--ac-chip-toggle-default-text: var(--arb-blue-500)
```

**Comment by KenAJoh** [comment]
La til token `--ac-chip-toggle-text` 🚀 (default `--a-text-default`) i v2.8.6

**Comment by otenav** [comment]
Tusen takk, fungerer fint!
