### ISSUE TITLE
[Innspill til komponent]: Overstyre farge på ikonene i Alert

### ISSUE THREAD

**Issue by otenav** [navikt/Designsystemet#1883]
### Tilbakemelding

På https://arbeidsplassen.nav.no/ har vi valgt en annen bakgrunnsfarge på `Alert`, og ønsker også å endre fargen på varsel-ikonene. Ønsket er derfor å få en token for å overstyre fargen på disse ikonene.

Dette gjør vi i dag, men ønsker helst å unngå en slik overstyring:
```
.navds-alert--info .navds-alert__icon path {
.navds-alert--info .navds-alert__icon path {
    fill: var(--arb-blue-400);
}
.navds-alert--success .navds-alert__icon path {
    fill: var(--arb-green-600);
}
.navds-alert--warning .navds-alert__icon path {
    fill: var(--arb-orange-500);
}
.navds-alert--error .navds-alert__icon path {
    fill: var(--arb-red-500);
}
```

Vi ønsker heller å kunne skrive cirka noe slikt:
```
--ac-alert-info-icon-color: var(--arb-blue-400);
--ac-alert-succes-icon-color: var(--arb-green-600);
--ac-alert-warning-icon-color: var(--arb-orange-500);
--ac-alert-error-icon-color: var(--arb-red-500);
```

Slik ser alerts ut på Arbeidsplassen:

<img width="850" alt="Skjermbilde 2023-03-29 kl  12 52 49" src="https://user-images.githubusercontent.com/29566394/228511832-8438b0b4-5bda-480c-bd9a-b8c355f3887b.png">

**Comment by KenAJoh** [comment]
La til tokens i v2.8.6 🚀  
```
--ac-alert-icon-info-color: --a-icon-info
--ac-alert-icon-success-color: --a-icon-success
--ac-alert-icon-error-color: --a-icon-danger
--ac-alert-icon-warning-color: --a-icon-warning
```
