### ISSUE TITLE
[Innspill til komponent]: Farge på punktmerke i ErrorSummary

### ISSUE THREAD

**Issue by otenav** [navikt/Designsystemet#1884]
### Tilbakemelding

Ønsker å kunne overstyre fargen på punktmerket i `ErrorSummary`.  Grunnen til dette er at vi på Arbeidsplassen har en mørkere blåfarge på lenker, og da ser man forskjell på punktmerket og lenketekst.

 I dag er dette satt til å være `--a-blue-500` i koden fra Aksel:
```
.navds-error-summary__list>* { 
    color: var(--a-blue-500);
}
```

Mulig default token er kanskje `--a-text-action`, med en custom token i tillegg?

Det er dette punktmerket det gjelder, skjermbilde fra med Arbeidsplassen:
<img width="867" alt="Skjermbilde 2023-03-29 kl  13 03 08" src="https://user-images.githubusercontent.com/29566394/228514352-b88ae275-d4f1-4b64-abdf-0a5f4b3b6af8.png">

**Comment by KenAJoh** [comment]
La til token `--ac-error-summary-list-dot` i v.2.8.6 🚀  Er default `--a-text-action` nå, så tror ikke man vil trenge å måtte overstyre den manuelt lengre 🤞
