### ISSUE TITLE
[Nytt ikon]: VideoSlashIcon

### ISSUE THREAD

**Issue by otenav** [navikt/Designsystemet#1897]
### Navn på ikonet

VideoSlashIcon

### Eksempel på ikonet

Vi ønsker oss et `VideoSlashIcon`, som ser likt ut som `VideoIcon`, men med skråstrek over. For å vise at kamera er skrudd av, tilsvarende som at `MicrophoneSlashIcon` viser at mikrofon er skudd av.

Vi ønsker dette ikonet fordi vi har videopresentasjon av en bedrifter på Arbeidsplassen Jobbtreff

**Comment by lmfaole** [comment]
Da kommer følgende ikoner! Håper det er dekkende, så er det bare å si ifra om du trenger flere ✨ 
![Variant=Fill](https://user-images.githubusercontent.com/37940048/228767037-fac91275-734e-47b9-8c56-f466f4db0672.svg) ![Variant=Stroke](https://user-images.githubusercontent.com/37940048/228767075-681b8c79-0c97-445c-bb4f-f1e5c5b98577.svg)

**Comment by KenAJoh** [comment]
[Er tilgjengelig i siste versjon nå](https://aksel.nav.no/ikoner/VideoSlash) v2.8.8
