### ISSUE TITLE
[Innspill til ikon]: ArrowCirclepath

### ISSUE THREAD

**Issue by macbruker** [navikt/Designsystemet#1910]
### Tilbakemelding

Dette ikonet skalerer ikke helt riktig når det brukes i liten eller ekstra liten variant av knapp i Figma.

<img width="510" alt="image" src="https://user-images.githubusercontent.com/1032194/229472441-90f974f8-f279-4f16-bb1b-172c6fe06b45.png">

**Comment by JorgenMaristuen** [comment]
Skal være fikset nå
