### ISSUE TITLE
[BUG] Feil på nøytral knapp i Figma

### ISSUE THREAD

**Issue by macbruker** [navikt/Designsystemet#1911]
Det ser ut som det er noe muffins med interaktiviteten til nøytral knapp i Figma. I dette skjermopptaket ser det ut som active state henger igjen.

https://user-images.githubusercontent.com/1032194/229476224-0e7c81c1-fd7a-4579-8b78-60851fdcbce5.mov

**Comment by JorgenMaristuen** [comment]
Takk for beskjed! Dette er en kjent bug i Figma som gjelder bruk av while pressing state og overlays. Har fiksa det med en work around som er beskrevet i [Figma forum](https://forum.figma.com/t/while-pressing-state-doesnt-reset-after-overlay-is-closed/3226).
