### ISSUE TITLE
[Innspill til komponent]: <TextField />

### ISSUE THREAD

**Issue by macbruker** [navikt/Designsystemet#1917]
### Tilbakemelding

For meg ser det ut som description er nærmere input-feltet under, enn label over. Dette synes jeg ser litt rart ut. Satte opp en skisse som illustrerer dagens ulike avstander og to forslag til justering.

**A**: Dagens oppsett
**B**: Like mye luft over og under description
**C**: Mindre luft over description og mer luft under

![image](https://user-images.githubusercontent.com/1032194/231733740-568f9b79-294b-4672-ab23-d6ea04281ade.png)

**Comment by KenAJoh** [comment]
Oppdatert i #1967
