### ISSUE TITLE
[Innspill til komponent]: <ExpansionCard />

### ISSUE THREAD

**Issue by Trent-NAV** [navikt/Designsystemet#1918]
### Tilbakemelding

Stor kudos for veldig kreativt anordnet Figma komponent og god Aksel dokumentasjon! 😍

Lite innspill: Som Figma komponent kunne border også vært en prop variant da det på IF kan være god nok kontrast til bakgrunn også uten border, eller når card bakgrunnen er en annen enn hvit. Ser at Custom varianten i kode også har border selv med annen bakgrunnsfarge. 

https://nav-it.slack.com/archives/C7NE7A8UF/p1681381676432609

**Comment by sjur-gr** [comment]
Takker! Med custom-varianten er det ganske enkelt å ta bort border ved å endre token til `var(--a-transparent)`. I Figma er det for øyeblikket litt mer vrient. Om vi lager en prop uten border må vi samtidig legge på alle «riktige» bakgrunnsfarger slik at man ikke kan ende opp med hvitt mot hvitt uten border. Vi krysser fingra for at design tokens Figma jobber med vil gi samme custom-muligheter som i kode.
