### ISSUE TITLE
[Nytt ikon]: reminder

### ISSUE THREAD

**Issue by karihamnes** [navikt/Designsystemet#1919]
### Navn på ikonet

reminder

### Eksempel på ikonet

<img width="19" alt="reminder-ikon" src="https://user-images.githubusercontent.com/61583515/232445529-550a866c-be84-4ada-8ec0-68c49ba3fbbb.png">

Ønsker meg et slikt ikon fordi det er litt mer personlig (mer "note to self"), og ikke like "hardt" som å bruke f.eks. timer eller noe annet tidsrelatert for å minne noen på noe. Bruke for ting som det ikke er satt en hard deadline for. I vårt case tenkt brukt på interne flater, men kan sikkert være aktuelt eksternt også.

**Comment by sjur-gr** [comment]
Funker dette @karihamnes 
![HandKnot](https://user-images.githubusercontent.com/82579704/232788531-84fea24d-82c4-45fe-9cb0-d4d04de5eb47.png)

**Comment by karihamnes** [comment]
Beklager treg tilbakemelding, tror det kommer til funke som fjell👍

**Comment by sjur-gr** [comment]
Cool 🤘 @KenAJoh denne er klar for kode
