### ISSUE TITLE
Alpha UI Kit respons

### ISSUE THREAD

**Issue by Trent-NAV** [navikt/Designsystemet#1922]
### Tilbakemelding

Av det som ligger i Alpha UI Kit håper jeg Toast, Combo Button og Notification flyttes frem i prioritet da et par av disse allerede freestyles i PO Pensjon. Vet at de også er tiltrengt i andre IF miljøer. Lookup komponentet er også relevant og nyttig, så her treffer dere godt 👍

**Comment by sjur-gr** [comment]
Cool. Vi er usikre på når disse vil havne i pipeline. Supert om dere kan teste de og høste noe erfaring først.

**Comment by Trent-NAV** [comment]
**Følger opp med litt høstet erfaring fra Pesys ca 2 1/2 mnd etter innlegget.**


**Toast**
Utviklerne har brukt en egenutviklet toast som er basert på alert metaforene, på samme måte som DS toasten i Alpha UI kit. Så langt jeg har observert helt uten link, regner med at link eventuelt er tenkt som en variant? I vår kontekst så er det kun benyttet kvitteringstekst og så langt jeg kan se information og success type, men godt mulig det ligger warning type i systemet også, jeg har ikke avdekket det. Toasten "slukker" etter noen ms delay. Vi har ikke etterspurt noe brukerrespons men har i allefall ikke fått noe negativ respons på det enda og toasten sirkulerer ganske bredt.

**Notification**
Hadde det til uformell diskusjon igjen. Når vi ser på det i felleskap internt så scorer den konvensjonelle bjella med rød badge bra. Et tenkt brukseksempel vi tok opp nå sist var å eventuelt benytte notification i system menyen når / om det dukker opp nytt menypunkt. Det er mao en sjelden sak. Man kunne også tenke seg en type global notification et sentralt sted i UI'et tilknyttet et type infopanel som kommuniserer noe til saksbehandlerne. Ikke sikkert sistnevnte er gjennomførbart globalt med det første men det er veldig interessant mht vår kommunikasjon med brukerne. Hotjar er ikke mulig å bruke lengre pga GDPR breach.  

**Lookup**
Vi har ikke implementert noe lokal versjon av denne men bruker HelpText mye. Jeg observerer at flere IF miljøer har etterspurt et slikt komponent for sine kontekster, bare 1 uke etter at jeg postet henvendelsen her dukket det opp en [konkret forespørsel](https://nav-it.slack.com/archives/C7NE7A8UF/p1682492762400699).  

For Pesys del er det en del intern lingo i systemet som nye saksbehandlere ikke nødvendigvis forstår i startfasen, og det er mye kompleks saksgang. Lookup kan redusere kognitiv last i slike tekster. Det er kontekster med lengre tekstpassasjer der Lookup passer bedre enn HelpText, sistnevnte bruker vi mest inline i saksflyt og i funksjonelle kontekster som krever interaksjon, der fungerer den fint. 

**Combo Button**
En BTN som trigger dropdown komponentet er implementert, det er referert til i [denne posten](https://github.com/navikt/aksel/issues/2064). Så ved å koble flere DS komponenter sammen kan man simulere en combo button, men selvsagt interessant om den ble rendyrket som **ett** komponent i DS av den typen som ligger til iterasjon i Alpha UI Kit.
