### ISSUE TITLE
[Innspill til komponent]: <DatePicker />

### ISSUE THREAD

**Issue by erlend-axelsson** [navikt/Designsystemet#1926]
### Tilbakemelding

Datepicker dropdown på iPhone 13 mini med Safari kutter det siste sifferet i årstallet.

![EAE7A318-E084-434C-BEB9-470747D5A758](https://user-images.githubusercontent.com/32471637/233341346-93add7a0-ac4c-4675-8dd5-1825c284a3d1.png)

**Comment by KenAJoh** [comment]
Hei, takk for innspill! Tror dette skyldes padding + layout-modell som er brukt for eksemplene og hvis riktig implementert ikke vil være et problem i bruk.
