### ISSUE TITLE
[Innspill til komponent]: <ExpansionCard />

### ISSUE THREAD

**Issue by karl-run** [navikt/Designsystemet#1931]
### Tilbakemelding

Jeg vil kunne provide a11y label via `aria-labelledby` isteden for å bli tvunget til å bruke `aria-label`.

Eksempel:
```
const headerId = `minUnikeId-${sykmeldingsId}`

<ExpansionCard aria-labelledby={headerId}>
    <ExpansionCard.Header id={headerId}>
        En tittel
```

Dagens props krever at `aria-label` er satt:
![image](https://user-images.githubusercontent.com/1507032/233629526-85c7e6f0-517e-4bc7-a2c8-8cddde7b6318.png)

**Comment by KenAJoh** [comment]
[Ser ut som det er godkjent syntax, så ser ikke noe i veien for det](https://www.scottohara.me/blog/2021/07/16/section.html)
@mortentollefsen Vet du om noen ulemper med `aria-labelledby` vs `aria-label` for section-elementer?

**Comment by mortentollefsen** [comment]
Aria-labelledby skal fungere like bra.


Mvh: Morten
90 89 93 05

Fra: Ken ***@***.***>
Sendt: fredag 21. april 2023 14:00
Til: navikt/aksel ***@***.***>
Kopi: Tollefsen, Morten ***@***.***>; Mention ***@***.***>
Emne: Re: [navikt/aksel] [Innspill til komponent]: <ExpansionCard /> (Issue #1931)


Ser ut som det er godkjent syntax, så ser ikke noe i veien for det<https://urldefense.com/v3/__https:/www.scottohara.me/blog/2021/07/16/section.html__;!!M12l6qNq_w!p5TpeEd2lPDTsH7VqXbb5U0AZ-hRDphPx7m1pCBqlietP-04XGM5jZkArwrUUaOTxOOIwHhK8UDiEabUScw8Rxbqb7Sn3Q$>
@mortentollefsen<https://urldefense.com/v3/__https:/github.com/mortentollefsen__;!!M12l6qNq_w!p5TpeEd2lPDTsH7VqXbb5U0AZ-hRDphPx7m1pCBqlietP-04XGM5jZkArwrUUaOTxOOIwHhK8UDiEabUScw8RxZjzer8pw$> Vet du om noen ulemper med aria-labelledby vs aria-label for section-elementer?
