### ISSUE TITLE
[Nytt ikon]: nummerert liste

### ISSUE THREAD

**Issue by Karroholm** [navikt/Designsystemet#1937]
### Navn på ikonet

Nummerert liste

### Eksempel på ikonet

![image](https://user-images.githubusercontent.com/131680187/234010739-24fbc24f-efc7-4a75-9225-b35711f17551.png)

Lik som punktliste-ikonet, men med nummerert liste. Trengs for ny brevredigeringsklient for saksbehandlere. 

tysm

**Comment by sjur-gr** [comment]
Ikonendringer er klare i Figma @KenAJoh
