### ISSUE TITLE
[Innspill til komponent]: <Textarea />

### ISSUE THREAD

**Issue by havstein** [navikt/Designsystemet#1945]
### Tilbakemelding

Doc-en til maxLenght: det er vel en visuell indikator, ikke en visuell validator ☺️

**Comment by KenAJoh** [comment]
🙌 Fix på tur ut

**Comment by havstein** [comment]
Jeg tenkte etterpå at prop-en kunne hatt et annet navn enn `maxLength` - for eksempel `characterCount`eller noe. Det blir vel en breaking change og dermed ikke så fristende..

**Comment by KenAJoh** [comment]
Stemmer, er breaking så terskelen er litt høyere. Men tenker det var et godt forslag for å kommunisere bedre, så tar det med videre 🙌
