### ISSUE TITLE
[Innspill til komponent]: <GuidePanel />

### ISSUE THREAD

**Issue by EspenSteinum** [navikt/Designsystemet#1958]
### Tilbakemelding

Fåreslår på GuidePanel å bruke Poster variant på mobil, helst at det byttes automatisk i brekkpunktene xs og sm.

I tillegg foreslår jeg en small poster variant som egner seg bedre på mobil:
- Redusere padding til 1 rem (16px)
- Redusere illustrasjonen til ca 4x4 rem (64px)

Komponenten tar mye plass på mobil, spesielt default-varianten som okkuperer mye plass i venstre marg.

Ellers kan jeg nevne at jeg liker komponenten, og bruker den ofte ved tips til bruker som skal fremstå litt hyggelig.
![GuidePanel-small](https://user-images.githubusercontent.com/128036933/236219565-027abdfe-af47-4949-8c00-66eade53571f.png)

**Comment by KenAJoh** [comment]
Blir fikset i aksel#203
