### ISSUE TITLE
Innspill til Button og Link komponenter: 

### ISSUE THREAD

**Issue by navperbirg** [navikt/Designsystemet#1963]
### Tilbakemelding

Vi i produktområde Utbetaling jobber med å lage nye skjermbilder for saksbehandlere. Våre brukere etterspør tastatursnarveier på knapper og linker. 

Vi ønsker oss derfor at Button og Link utvides med mulighet for å angi accessKey.

**Comment by KenAJoh** [comment]
Hei, etter å ha undersøkt accessKey litt er denne noe vi tenker burde unngås i de fleste tilfeller. Navigering med voiceover vil eksempelvis kunne bli problematisk ved bruk av accessKey

Eslint:
> No access key attribute allowed. Inconsistencies between keyboard shortcuts and keyboard commands used by screenreaders and keyboard-only users create a11y complications.

[MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/accesskey#accessibility_concerns)
>An accesskey value can conflict with a system or browser keyboard shortcut, or assistive technology functionality. What may work for one combination of operating system, assistive technology, and browser may not work with other combinations.

>Certain accesskey values may not be present on certain keyboards, especially when internationalization is a concern. So adapting to specific languages could cause further problems.

>accesskey values that rely on numbers may be confusing to individuals experiencing cognitive concerns, where the number doesn't have a logical association with the functionality it triggers.

>Informing the user that accesskeys are present, so that they are aware of the functionality. If the system lacks a method of notifying the user about this feature, the user might accidentally activate accesskeys.


(dette sagt, så fungerer `accessKey`-prop på de fleste komponentene våre som eks Button og Link nå da vi sender videre alle props)
