### ISSUE TITLE
[Innspill til komponent]: <Chat />

### ISSUE THREAD

**Issue by hakonph** [navikt/Designsystemet#1969]
### Tilbakemelding

Legge til rette for automatisk grupering av meldingene.
Sån at man løser det likt på tvers av aplikasjonene.

**Comment by KenAJoh** [comment]
Hei, har du noen eksempler på hvordan automatisk grupering ville sett ut/fungert?

**Comment by hakonph** [comment]
vile sett ut som eksempelet i dag.
Men i stedet for at vi som konsumenter må tenke på gruperingen ville det vert løst av komponenten.
Eks alle meldinger som er sendt fra en person på rad innen et git tidsrom (default sat av komponenten) ville blitt grupert.

**Comment by KenAJoh** [comment]
Vi har gjort noen oppdateringer til Chat i det siste: https://aksel.nav.no/komponenter/core/chat
Relatert til "Automatisk grupering av meldingene" har vi valgt å ikke ta dette inn i systemet i denne omgang. Men vi har det på listen over forbedringer vi kan utføre i fremtiden på komponenten 👍
