### ISSUE TITLE
[Innspill til komponent]: <Textarea />

### ISSUE THREAD

**Issue by hakonph** [navikt/Designsystemet#1975]
### Tilbakemelding

Når skjemleser hjelpeteksten skrives med
```html
<span id="R1mH1" class="navds-sr-only">"Tekstområde med plass til" <!-- -->"100"<!-- --> "tegn."</span>
```
leser skjermelsern 
Tekstområde med plass til
pause
100
pause
tegn

et annet spørsmål er trenges denne når man allerede har "100 tegn igjen"

**Comment by mortentollefsen** [comment]
Hvilken skjermleser er det som leser teksten på denne måten?
Teksten er faktisk ganske fin fordi den kobles mot felte med aria-describedby. Det betyr at hvis du feks. Tabber til feltet får du beskjed om hvor mye tekst du kan legge inn. Dette er det selvsagt også mulig å finne ut ved å lese antall tegn igjen, men da må du ut av feltet med skjermleser, pile eller sveipe til antall tegn igjen og så gå tilbake og inn i feltet igjen. Du må i tillegg til at dette er litt tungvint også aktivt sjekke, dvs. ikke få en mer eller mindre automatisk reminder slik alle som ser jo får fordi teksten står rett under feltet. Hos meg med Jaws/NVDA leses teksten helt fint, men har ikke Mac på jobben i dag - mulig det er litt annerledes der (og VO er det faktisk mye rart med på nett, spør du meg, hehe). Det at det er en pause er kanskje heller ingen kjempestor krise???
Måten antall tegn leses på er super synes jeg: dette må absolutt ikke leses hele tiden, men særlig i lange tekstfelt er det fint å få en reminder når du begynner å nærme deg maks antall tegn.
