### ISSUE TITLE
[Innspill til komponent]: <Chat />

### ISSUE THREAD

**Issue by karihamnes** [navikt/Designsystemet#1978]
### Tilbakemelding

I flere fagsystemer diskuteres muligheten for direkte og sikker dialog mellom NAV-ansatte fagpersoner, i selve fagsystemene, f.eks. i forbindelse med ulike totrinnsprosesser (kvalitetssikring, beslutterprosesser). 

En slik dialogløsning er implementert i f.eks. § 14 a vedtaksløsning som snart skal lanseres, men som på grunn av "legal wrangling" har vært i pilot i over 2 år. Dialogløsningen der ble laget før chat-komponenten eksisterte, og er foreløpig ikke byttet ut. Vi ser på muligheten nå for å få gjort redesign og komme over på nytt designsystem.

Da hadde det vært gunstig med en chat-komponent som også egner seg for interne flater, altså en "small"-variant som bygger minst mulig i høyden (som er det som er mest sensitivt). 

Ta gjerne kontakt om det er noe dere lurer på.

**Comment by KenAJoh** [comment]
Hei 👋 Chat tilbyr nå en mindre versjon (small): https://aksel.nav.no/komponenter/core/chat#chatdemo-small
