### ISSUE TITLE
[Innspill til komponent]: <Tag />

### ISSUE THREAD

**Issue by daghelgescott** [navikt/Designsystemet#1979]
### Tilbakemelding

Skulle ønske «Tag Small» brukte Body Small istedenfor detail. 

### Forslag

**Størrelse**

- Tag Medium: Body Medium
- Tag Small: Body Small
- Tag Xsmall: Detail

**Varianter**

- Border (som i dag)
- Fill Subtle (Ny!)
- Fill Strong (som i dag)

**Comment by KenAJoh** [comment]
Alle tag-varianter har nå en "moderate"-versjon + alle har oppdatert typografi 🚀 
https://aksel.nav.no/komponenter/core/tag#tagdemo-success
