### ISSUE TITLE
[Innspill til ikon]: FileXMark

### ISSUE THREAD

**Issue by karihamnes** [navikt/Designsystemet#1980]
### Tilbakemelding

Ikke et innspill til dette fil-ikonet spesifikt, men til kolleksjonen av fil-ikoner. Jeg savnet "Lag nytt dokument"-ikon, gjerne fil-ikon med en pluss. Det er ikke det samme som redigér (der man sikkert kan bruke DocPencil, og det er ikke det samme som kopier).

Så det ønsker jeg meg. Noe á la et fil-ikon, men med en pluss et eller annet sted? Slik at det kan brukes i en suite av fil-ikoner.

**Comment by KenAJoh** [comment]
[Ikon er tilgjengelig i nyeste versjon](https://aksel.nav.no/ikoner/FileXMark) 🎉
