### ISSUE TITLE
[Innspill til ikon]: FileText

### ISSUE THREAD

**Issue by karihamnes** [navikt/Designsystemet#1981]
### Tilbakemelding

Jeg ønsker meg et liknende ikon som dette som kan representere et vedtak. F.eks. et fil-ikon men med et paragraf-tegn inni?

**Comment by karihamnes** [comment]
Noe som dette
<img width="67" alt="image" src="https://github.com/navikt/aksel/assets/61583515/bab61834-1cc7-4e87-a1bc-f1bfddcbe254">

**Comment by KenAJoh** [comment]
[Ikon er tilgjengelig i nyeste versjon](https://aksel.nav.no/ikoner/FileParagraph) 🎉
