### ISSUE TITLE
[Innspill til komponent]: <Chips />

### ISSUE THREAD

**Issue by macbruker** [navikt/Designsystemet#1983]
### Tilbakemelding

Ved bruk av flere chips etter hverandre, er det uheldig at bredden endres i "valgt" state. Det gjør at flere andre chips flytter på seg. Noen ganger bare litt til siden, men også at de kan hoppe ned på neste linje 😬

**Comment by KenAJoh** [comment]
Helt enig i at dette er litt kjipt! Hvordan kunne du sett for deg vi løste dette? 
Alternativ (av sikkert mange muligheter): 
> Chips har default mer padding-inline, ved selected-state så minimeres padding og ikonet tar opp plassen

**Comment by macbruker** [comment]
I mitt brukstilfelle er det aldri mer enn en Chip som kan være "aktiv/valgt", dermed er det ikke like stort behov for ikon. Kjenner ikke til andre implementasjoner av denne komponenten, så det er vanskelig å vurdere om den fungerer bra eller dårlig med ikonet ellers.

**Comment by KenAJoh** [comment]
Chips har nå prop for versjon uten checkmark https://aksel.nav.no/komponenter/core/chips#chipsdemo-toggle-no-checkmark
