### ISSUE TITLE
[Innspill til komponent]: <TextField />

### ISSUE THREAD

**Issue by aflaten** [navikt/Designsystemet#1986]
### Tilbakemelding

Hei. Vi driver å lager skjermbilder til internt bruk. Den minste størrelsen på denne komponenten er small, men jeg syntes den blir for stor. Har dere mulighet til å tilrettelgge slik at vi kan få mindre utgave av denne?

**Comment by sjur-gr** [comment]
Yo! Har du et skjermbilde av løsningen du kan dele? (send på Slack om det er sensitivt) Utgangspunktet for TextField Small (32px høy) er at det skal være mulig å ha Chips (og slikt) inni. Minste str på Chips (alt klikkbart egentlig) som er lov er 24px høy.

**Comment by KenAJoh** [comment]
Hei, lukker denne da vi ikke blir å legge til denne muligheten med det første.
