### ISSUE TITLE
[BUG] DatePicker.Input åpner ikke dato-modalen igjen etter første valg

### ISSUE THREAD

**Issue by ivoiv** [navikt/Designsystemet#1987]
## Hva er feilen/problemet?

Det skjer man bruker DatePicker.Input sammen med en "popup" datepicker som åpner seg når man trykker på det.
Når du først velger dato lukker modalen seg riktig.
Men når du trykker på input-feltet igjen etterpå skjer det ingenting.
Du må manuelt ta fokus bort fra input feltet og så trykke inn på det igjen for at Dato-modalen skal åpne seg.

## Steg for å reprodusere problemet (valgfri)

1. Åpne eksempel.
2. Trykk inne på input-feltet.
3. Velg en dato. (modalen lukker seg og dato velges)
4. Trykk på input-feltet en gang til.
5. Ingenting skjer

## Eksempel/Tilleggsinformasjon (valgfri)

[https://codesandbox.io/s/3rrjdd?module=App.js](https://codesandbox.io/s/3rrjdd?module=App.js
)

**Comment by KenAJoh** [comment]
Hei, dette er siden popover åpnes `onFocus`. Usikker på konsekvensene av å potensielt legge på en onClick, men kan legge det på lista med QOL-oppdateringer for Datepicker ☑️
