### ISSUE TITLE
[Innspill til komponent]: <Select />

### ISSUE THREAD

**Issue by navperbirg** [navikt/Designsystemet#1991]
### Tilbakemelding

Hei, jeg lurer på om det er mulig å sende med en array med options til denne komponenten, istedet for å liste opp en og en option?

**Comment by KenAJoh** [comment]
Hei 👋 Vi har prøvd å unngå bruk av arrays for option (eller andre typer opplisting) så langt det lar seg gjøre. Dette for å gi et litt enklere API for setting av props på f.eks options. 
```jsx
<Select>
	{myoptions.map(x => 
		<option value={x.value} key={x.value}>{x.label}</option> // Tilgang til alle navtive-props
	)}
</Select />
```

Ønsker gjerne å høre hvis array har noen fordeler vi ikke har tenkt på!
