### ISSUE TITLE
[Innspill til komponent]: <Switch />

### ISSUE THREAD

**Issue by Trent-NAV** [navikt/Designsystemet#2004]
### Tilbakemelding

Bare en liten Figma sak. Når Switch står i position right så følger ikke label på med text align right men blir stående igjen på left. 

![switch_txt_alignment](https://github.com/navikt/aksel/assets/86958516/720cabfc-974e-40d4-b61c-d312e5cb7919)

**Comment by sjur-gr** [comment]
Det er "by design" for at switch'ene skal aligne om man har flere i en liste. Typisk settings pattern. Har du en situasjon hvor dette ikke funker?

**Comment by Trent-NAV** [comment]
Man kan selvsagt bare justere containeren for å kompensere for at teksten ikke er align right når komponentet er i position right. Tenkte det kanskje kan bidra til litt kluss ved updates at label ikke er identisk posisjonert i forhold til switchen på begge komponent variantene, men at den da er motsatt på position right. I vår kontekst brukes den kun alene forøvrig.

https://github.com/navikt/aksel/assets/86958516/7e77fdb8-45a3-4162-99ef-609267fedb33

**Comment by Trent-NAV** [comment]
Som et apropos til Switch så er ikke den gamle versjonen byttet med ny der jeg har brukt den i Figma skissene, den er tilgjengelig i Core UI Kit, alle library koblinger er riktig og jeg har akseptert alle update requests, har heller ingen pending updates i Figma. Det samme gjelder også Alert forøvrig, så det er ikke kun Switch, men tenkte jeg skulle nevne det.

**Comment by Trent-NAV** [comment]
Følger opp meg selv litt her, jeg nevnte sist uke at vi kun bruker Switch alene, det var sant helt frem til nå da vi planlegger en egen feature toggle side og da blir det brått et liste oppsett. 😀
