### ISSUE TITLE
[Innspill til komponent]: <Table />

### ISSUE THREAD

**Issue by navperbirg** [navikt/Designsystemet#2008]
### Tilbakemelding

Hei, det hadde vært kjekt å ha støtte for filtrering på felt-verdier i Table-komponenten.

**Comment by KenAJoh** [comment]
Hei, takk for innspill! Satt opp en demo opp på hvordan dette kan løses i dag. Men kan hende jeg misforstod problemet, så kom gjerne med noen eksempler hvis dere har det 😃 
https://codesandbox.io/s/pedantic-noyce-w40h10?file=/App.js
