### ISSUE TITLE
Manglende 'type'-attributt i sorterbare tabel i: <Table />

### ISSUE THREAD

**Issue by dipeshpradhan** [navikt/Designsystemet#2011]
### Tilbakemelding

Jeg har oppdaget et problem med <Table.ColumnHeader> komponenten i @navikt/ds-react biblioteket.

Når jeg forsøker å sortere en tabell som bruker denne komponenten, oppstår det en advarsel som sier: "Warning: You submitted a Formik form using a button with an unspecified `type` attribute.  Most browsers default button elements to `type="submit"`. If this is not a submit button, please add `type="button"`.

Dette skjer fordi sorteringen utføres ved å trykke på en <button>-element i <Table.ColumnHeader> komponenten, som ikke har en spesifisert type-attributt. Når en knapp ikke har en type-attributt, behandler nettlesere dette som type="submit" som standard, noe som fører til at Formik-skjemaet sendes inn.

Jeg vil foreslå å legge til en type-attributt til <button>-elementet i <Table.ColumnHeader> komponenten, eller å eksponere en prop for å gjøre det mulig å angi knappetypen. 

Jeg testet en CustomTable med CustomTableColumnHeader med button typ og den funkert.

**Comment by KenAJoh** [comment]
Hei, takk for tilbakemeldingen!
Gravde litt i [koden](https://github.com/navikt/aksel/blob/812a2347a05ae1976b325f5f562a82e531f29800/%40navikt/core/react/src/table/ColumnHeader.tsx#L51) og ser ut som dette er noe som allerede er fikset 🔨 
```jsx
{sortable ? (
  <button
    type="button"
    className="navds-table__sort-button"
    ...
```
Ble fikset i versjon 2.0.10 av @navikt/ds-react, så alle nyere versjoner bør fungere 🚀

**Comment by dipeshpradhan** [comment]
Supert. Takk!
