### ISSUE TITLE
[Innspill til komponent]: <Radio />

### ISSUE THREAD

**Issue by macbruker** [navikt/Designsystemet#2013]
### Tilbakemelding

Det ser ut som gråfargen på radioknapper ikke blir mørkere om de legges på grå bakgrunn. Jeg tror dette skyldes at fargen alltid ligger på hvit bakgrunn (box-shadow med inset). 🤔

**Comment by KenAJoh** [comment]
Tror dette kan være en 'ok' fiks for dette:
```
    box-shadow: 0 0 0 2px var(--ac-radio-checkbox-border,var(--a-border-default));
    height: calc(1.5rem - 2px);
    width: calc(1.5rem - 2px);
    margin: 2px;
```
beholder da hvit bakgrunn som standard, men border blir mørkere. 
Tror vi ønsker å beholde hvit bakgrunn som standard, men ikke 100% på om det

**Comment by macbruker** [comment]
Ja, det var noe sånt jeg testet i devtools. Prøvde å sikre riktig oppførsel ved :hover og :focus også, men det ble klønete å hacke i nettleseren.
