### ISSUE TITLE
[Innspill til komponent]: <GuidePanel />

### ISSUE THREAD

**Issue by aflaten** [navikt/Designsystemet#2023]
### Tilbakemelding

Hei, er det mulig å vise liste (```<ul>```) i dette panelet?

```
  <GuidePanel poster>
              Her kan du søke opp posteringer. Påkrevede felter er:
              <ul>
                <li>Utbetalingsmottaker eller Rettighetshaver</li>
                <li>Periodetype og periode</li>
              </ul>
            </GuidePanel>
```

**Comment by aflaten** [comment]
Viser ikke punktliste som jeg ønsker:

<img width="716" alt="image" src="https://github.com/navikt/aksel/assets/16606982/406b8bd6-abbe-4ef4-8f3b-559c8afe39c0">

**Comment by KenAJoh** [comment]
Hei, tror det er noe i koden deres som fører til dette 👨‍💻 Satte opp en demo her med fungerende eksempel.  https://codesandbox.io/s/hopeful-gould-muprj3?file=/App.js
