### ISSUE TITLE
[BUG] Search bommer en del på søk

### ISSUE THREAD

**Issue by JulianNymark** [navikt/Designsystemet#2033]
## Hva er feilen/problemet?

Feks, jeg vil søke etter info om CSS generelt, vi har en artikkel som heter `CSS Imports` og burde komme øverst i søket, men slik den er i dag dukker den ikke opp i det hele tatt når man søker `CSS`.

- matcher ikke på tekst i article title?
- matcher ikke på tvers av `CSS.`, `CSS`, `CSS,` etc... (punctuation / lemmatization)

Søker jeg på `Styling` så får jeg urelevante `beste treff`

![image](https://github.com/navikt/aksel/assets/819074/c4a80f69-1a8d-4fa4-b4d3-bddc3b728ebb)

## Steg for å reprodusere problemet (valgfri)

noen søk.

![image](https://github.com/navikt/aksel/assets/819074/0573d5e7-31ec-4568-843d-135356e5aae4)

![image](https://github.com/navikt/aksel/assets/819074/5c8d4ae7-cfe7-4742-897f-13da86ecd8bb)

Søker jeg etter komponenter som er gruppert under en felles dokumentasjons side, for eksempel `Heading`. Så vil jeg at `Typography` siden skal komme øverst i søket (`beste treff`)

![image](https://github.com/navikt/aksel/assets/819074/0742ff00-7a15-4baf-9ac2-0d6ed7f6f25e)

**Comment by KenAJoh** [comment]
Fikset 🐛
