### ISSUE TITLE
[Innspill til komponent]: <ToggleGroup />

### ISSUE THREAD

**Issue by runska** [navikt/Designsystemet#2037]
### Tilbakemelding

Hei!

Ved bruk av tab-knappen er det kun mulig å fokusere på knappen som _allerede er aktiv_ i en `ToggleGroup`. I eksempelet på [Aksel](https://aksel.nav.no/komponenter/core/toggle-group) klarer jeg å velge “Leste”-knappen ved tabbing, men ikke “Ulest” eller “Sendt” (men det funker med piltastene). Jeg ville forventet at også de inaktive valgene i ToggleGroup skulle kunne bli tabbet gjennom.

**Comment by KenAJoh** [comment]
Hei, takk for tilbakemeldingen! 
Vi lar ikke bruker "tabbe" til ikke valgte knapper siden den er implementert med "Roving tabindex"
- https://www.stefanjudis.com/today-i-learned/roving-tabindex
- https://www.w3.org/WAI/ARIA/apg/patterns/radio/examples/radio/

Dette er noe vi bruker på `ToggleGroup`, `Tabs` og `Radio` (er native der)
