### ISSUE TITLE
Mulighet for å vise overordnet veivalg som nodestruktur / tre : <Stepper /> ?

### ISSUE THREAD

**Issue by Hallaraker** [navikt/Designsystemet#2045]
### Tilbakemelding

Jeg er litt usikker på om det burde være under stepper eller kanskje noe eget, men det hadde vært fint med en komponent som kan vise en oversikt som en nodestuktur / tre.  

![image](https://github.com/navikt/aksel/assets/55539152/9aee64bc-b03e-4120-bd78-85197c932e5f)

**Comment by KenAJoh** [comment]
Hei, vi har tatt en runde på dette med teamet og dette mønsteret er ikke noe vi kommer til å se på med det første.
