### ISSUE TITLE
[Innspill til komponent]: <Dropdown />

### ISSUE THREAD

**Issue by Trent-NAV** [navikt/Designsystemet#2064]
### Tilbakemelding

Det er null margin space fra triggeren til dropdown og det er ikke så heldig. Når jeg lager skisser med den i Figma har jeg brukt spacing S3 i den tabellkonteksten jeg legger ved som eksempel her men dette blir jo ofte kontekstavhengig, utviklere må slik jeg forstår uansett lage egne margin regler for den om de ikke bruker den "rett fra boksen" og siden det ikke gjøres må vi gjerne akseptere manglende avstand. Jeg ser også i Aksel dokumentasjonen at den er demonstrert slik, helt uten margin mellom triggeren og dropdown elementet. Håper dere kan se på dette og eventuelt lage en spacing variant i komponentet? Type tight vs loose etc. 

Hvis det er implementeringsråd jeg kan ta med til utvikler som løser dette uten å måtte fristille seg fra DS så del gjerne det. Jeg gjengir et situasjonsbilde :) 

Venstre Figma eksempel er justert. 
![dropdown_space](https://github.com/navikt/aksel/assets/86958516/18096103-8cbc-4edc-a37f-77326b8ae93c)

**Comment by KenAJoh** [comment]
Som standard utrykk legger Dropdown seg 4px overlappende over trigger (Button) i kode
![Screenshot 2023-08-11 at 15 47 49](https://github.com/navikt/aksel/assets/26967723/4451cd3a-f568-414a-b4d8-3cb1c80553ea). 

Hvis man manuelt ønsker å ha annen spacing må man evt ta i bruk vanlig `Popover` og sette `offset` til ønskelig verdi. Men for standard `Dropdown` ønsker vi at avstanden ikke skal være fleksibel.
