### ISSUE TITLE
[Innspill til komponent]: <Checkbox />

### ISSUE THREAD

**Issue by Trent-NAV** [navikt/Designsystemet#2065]
### Tilbakemelding

I group error for checkbox group er error label bunnstilt. Når man feks har mange checkboxer og dermed en lang liste så hender det at det settes en overflow regel som gir scrollbar, et eksempel kan være et innholdsrikt filter med dropdown i tight UI der saksbehandlerne heller vil scrolle inline enn å få en svært lang åpen liste som genererer page scroll og potensielt en interaksjon som går ut av viewport.  Om det ikke er harde utformingskrav på error label plassering i forhold til WCAG så kunne error hatt posisjonsvariant top/bottom kanskje? Det er godt mulig det er flere hensyn å ta her men umiddelbart virker det fleksibelt. En toppstilt error som ikke er sticky vil også gå utenom viewport i denne settingen om det scrolles inline, men syns kanskje likevel at en posisjonsvariant kunne vært greit.  

 ![checkbox group_error state](https://github.com/navikt/aksel/assets/86958516/993b6a2b-0871-4212-b05a-d1f9088f2ad8)

**Comment by KenAJoh** [comment]
Hei, tok en runde med teamet og kom frem til at vi ikke ønsker å tilby denne muligheten i skjemakomponentene våre. Vi anbefaler i dokumentasjonen på det meste ~7 checkbokser og ser på [Combobox](https://aksel.nav.no/komponenter/core/combobox) som et ok alternativ i noen av disse tilfellene
