### ISSUE TITLE
[Innspill til komponent]: <Textarea />

### ISSUE THREAD

**Issue by Trent-NAV** [navikt/Designsystemet#2068]
### Tilbakemelding

Clear prop på text area kan være praktisk i visse kontekster, feks når den står alene som et responspanel der bruker kanskje har kopiert inn mye tekst fra ekstern fil og vil tømme feltet hurtig og starte på nytt. Ikke alle er kjent med CTRL+A :)   

Når clear er prop på Aksel search som kun har noen få characters burde den være enda mer formålstjenlig på Text area.

**Eksempel**
https://vuetifyjs.com/en/components/textareas/

<v-textarea clearable label="Label"></v-textarea>

**Comment by KenAJoh** [comment]
Hei, vi har sett litt på denne og er ikke noe vi kommer til å ta inn i komponenten med det første. Det vil kunne være noen problematikk hvis man f.eks sletter ved et uhell da `ctrl + z` ikke vil fungere.

Vet ikke om det vil fungere i konteksten deres, men har sett denne varianten litt rundt i NAV.
<img width="336" alt="Screenshot 2023-08-11 at 14 56 47" src="https://github.com/navikt/aksel/assets/26967723/3f99b150-e31a-40ee-864c-2a92043ab53f">
