### ISSUE TITLE
[Innspill til komponent]: <Switch />

### ISSUE THREAD

**Issue by karihamnes** [navikt/Designsystemet#2076]
### Tilbakemelding

Switcher/toggles er notorisk vanskelige. I demoen/eksemplet så benytter dere labelen "Slå på notifikasjoner" og henspeiler på at en switch, det er noe som man slår på eller av. Aktiverer eller deaktiverer. Men hva med når den _er_ slått på? Da står det fortsatt "Slå **på** notifikasjoner". Men det er jo ikke det som switchen da vil gjøre, for den vil slå AV notifikasjoner.

Det illustrerer noe av problemet med switcher. Jeg mener lablene burde være litt nøytrale, en representasjon av hva det er som skrus på/av. I dette tilfellet "Notifikasjoner". Ikke en aksjon, fordi den vil endre seg avhengig av tilstand for togglen.

Dette har ikke noe med selve funksjonaliteten å gjøre, men med bruken av komponenten. 

<img width="266" alt="image" src="https://github.com/navikt/aksel/assets/61583515/e38de63a-97d4-4c4c-84a4-18eba4b4ff22">

**Comment by finiteattention** [comment]
Enig med Kari om at dette ikke er helt optimalt ennå. Slik jeg oppfatter det er det to behov her som begge to burde vært like tydelig og eksplisitt: du må forstå hva som er nåværende status *og* forstå hvilke handlingsmuligheter du har. 

Hvis man tenker på "[Perceivable, Understandable, Operable](https://webplatform.github.io/docs/concepts/accessibility/pour/)", oppstår det noen spørsmål:

PERCEIVABLE:
- Hvordan tolkes ikonet i "on-state" blant de med nedsatt syn, enten det gjelder grønnfarge, små features (ikon), eller begge deler?

UNDERSTANDABLE:
- Forstår alle hva grønt betyr i denne sammenhengen?
- Vil alle forstå hva som check-ikon betyr i denne sammenhengen? 
- Selv om man skjønner at grønt betyr "på" eller "bra", hva er det som egentlig _er_ på eller bra? Er dette _mulighet_ for å slå på notifikasjoner som nå er enablet? (ref punktet under)
- Hvordan tolkes det når ikonet viser "på" mens call to action kan leses som at komponenten foreløpig ikke er på, at du fortsatt må handle for at den skal bli på?

OPERABLE:
- Er det åpenbart at "Slå på notifikasjoner" egentlig er en call to action når selve label-teksten ikke bærer åpenbare preg av klikkbarhet? Du må først over den med musa før den lyser blå. 
- Hvis du ikke har skjønt at du også kan klikke på label, blir det noen som sliter med å treffe selve switch-ikonet med musa/fingeren? (Typ, skjelving, nedsatt finmotorikk, sitter på lokaltog 😁) (Jf. checkbox hvor folk gjerne prøver å treffe selve checkbox-ikonet, selv om også labelen kan velges)
- Er det åpenbart at man opererer switchen ved å trykke på den? Vi bruker en komponent som har opphav i den fysiske verden, men selve gesten man er ikke lik. Hvis man prøver å dra musa/fingeren bortover komponenten, skjer det ikke noe.

Det var det jeg hadde for nå 😆

**Comment by finiteattention** [comment]
Gunstig sommeroppdagelse: Office 365 som har switch til av og på med automatiske svar. 

Ikonet viser "av"-state: label er "Slå på automatiske svar", nemlig en call to action. 

Ikonet viser at switchen er på: label er  "Automatiske svar er slått på", nemlig state og ikke CTA.

Det var noe interessant her med at label-en bare er en call to action når den er av 🤔 Muligens skyldes denne skjevheten at "av" er defaulten, at automatiske svar bare gjelder unntaksvis? Artig.

<img width="284" alt="Skjermbilde 2023-06-23 kl  16 55 28" src="https://github.com/navikt/aksel/assets/6875491/ef75b3f2-7099-41e0-9806-6d196c8d5f16">

<img width="253" alt="Skjermbilde 2023-06-23 kl  16 55 21" src="https://github.com/navikt/aksel/assets/6875491/d5c2ce81-2ec3-4237-8ecd-66d6dc70b0af">

**Comment by finiteattention** [comment]
(Og så kommer en popup-melding etter hvert som man har kommet ut av innstillingene, der det står "Automatiske svar er slått på i øyeblikket" og *så* call to action "Slå av". Verdenen er ikke jevnt distribuert 🙃

**Comment by KenAJoh** [comment]
Hei 👋 Tusen takk for innspill! Vi har gått gjennom dokumentasjonen til Switch nå å oppdatert: https://aksel.nav.no/komponenter/core/switch
