### ISSUE TITLE
[BUG] Textarea i18n prop oppfører seg motsatt av forventet

### ISSUE THREAD

**Issue by sedrickvarnes** [navikt/Designsystemet#2081]
## Hva er feilen/problemet?

Når man lager et `Textarea` komponent og bruker i18n propen blir counterTooMuch-stringen teksten for når du har tegn igjen og counterLeft-stringen teksten for når du har for mange tegn, altså motsatt enn det vi forventet. 

Forventer at det oppfører seg slik som det er dokumentert i typingen:
```ts
  i18n?: {
    /** @default Antall tegn igjen */
    counterLeft?: string;
    /** @default tegn for mye */
    counterTooMuch?: string;
  };
```

Men ser i koden at verdiene brukes motsatt av det som er dokumentert:
 (https://github.com/navikt/aksel/blob/main/%40navikt/core/react/src/form/Textarea.tsx#L206):
```
 {difference < 0
        ? `${Math.abs(difference)} ${i18n?.counterLeft ?? "tegn for mye"}`
        : `${difference} ${i18n?.counterTooMuch ?? "tegn igjen"}`}
```

## Steg for å reprodusere problemet (valgfri)

1. Lage et Textarea-komponent fra Aksel
2. Sende inn `i18n={{ counterTooMuch: 'tegn for mye', counterLeft: 'tegn igjen' }}` som prop til komponenten

## Eksempel/Tilleggsinformasjon (valgfri)

Sceenshot av resultatet:
<img width="667" alt="Screenshot 2023-06-28 at 10 11 20" src="https://github.com/navikt/aksel/assets/58301124/61c9ddf1-506d-47d8-80f1-846e37bc51dd">

Kode fra repo (https://github.com/navikt/aksel/blob/main/%40navikt/core/react/src/form/Textarea.tsx#L206):
```
 {difference < 0
        ? `${Math.abs(difference)} ${i18n?.counterLeft ?? "tegn for mye"}`
        : `${difference} ${i18n?.counterTooMuch ?? "tegn igjen"}`}
```

**Comment by KenAJoh** [comment]
Takk for bug-report! Bør være fikset i `v4.4.2`
