### ISSUE TITLE
[Innspill til komponent]: <DatePicker />

### ISSUE THREAD

**Issue by Leggenn** [navikt/Designsystemet#2086]
### Tilbakemelding

Om man velger samme "til dato" to ganger vil denne hoppe til "fra dato" og fjerne "til dato".

F.eks: Til: 1.06.2023, Fra: 4.06.2023, Fra 4.06.2023 = Til: "4.06.2023".

**Comment by KenAJoh** [comment]
Hei, slik Datepicker er implementert i dag er dette forventet oppførsel hvis jeg skjønte spm riktig. I fremtiden vil vi kanskje se på å gjøre noen UX-forbedringer.

https://github.com/navikt/aksel/assets/26967723/f9722a19-fe07-4a7f-b3e1-c1a75e196b3a
