### ISSUE TITLE
[Innspill til komponent]: <List />

### ISSUE THREAD

**Issue by Trent-NAV** [navikt/Designsystemet#2095]
### Tilbakemelding

Kommer det en Small variant av denne for IF?

**Comment by KenAJoh** [comment]
List har nå Medium/Small size i kode. Kommer snart i Figma også 🚀

**Comment by JorgenMaristuen** [comment]
@KenAJoh Går for spacingen vi snakket om. 16 for Medium og 12 for Small: [Figma](https://www.figma.com/file/m0qpSPpsnNC9DwdmerGqJH/branch/MNUTgOPwJVxr2HPXA2hpOv/Core-UI-kit?type=design&node-id=30273%3A19119&mode=design&t=NZnEC4dfXwXPcsIl-1)
