### ISSUE TITLE
[Innspill til komponent]: <Select />

### ISSUE THREAD

**Issue by Trent-NAV** [navikt/Designsystemet#2096]
### Tilbakemelding

Det hadde vært praktisk med en search prop i Select. Eksempel fra saksbehandling:

Man har behov for å hente opp behandlingskontor/enheter eller konkrete saker i en select liste. Hvis man nøyaktig kjenner saksnummeret så kan man skrive dette og en autocomplete funksjonalitet vil hente saken, men siden de fleste behandlerne ikke husker eller kjenner saksnr. blir det vanskelig, de fleste sakene starter med saksnummer så det er ikke så lett å operere med saksnavn med autocomplete funksjon. Uten et innebygget søk i Select så ender man opp med mye manuell scroll. Det blir drøy interaksjon å skulle introdusere et tradisjonelt søkekomponent i tillegg i saksflyten.

**Comment by KenAJoh** [comment]
Hei, dette blir løst i Combobox-komponenten som snart er klar 🎉 
Demo: https://5f801fb2aea7820022de2936-upivafitkm.chromatic.com/?path=/story/ds-react-combobox--default

**Comment by Trent-NAV** [comment]
Supert! 👍
