### ISSUE TITLE
[Forslag til komponent]: Coach mark

### ISSUE THREAD

**Issue by Trent-NAV** [navikt/Designsystemet#2106]
### Innspill

Det å kommunisere ny funksjonalitet i saksbehandlingssystemer kan være en utfordring. Jeg har vært inne på det før i sammenheng med notification komponent. Når jeg kikker i litt generell IF materiale ser jeg at AO har skissert opp løsninger for bruk av coach marks for å veilede brukerne i kontekst. Det var ifølge dokumentasjonen tenkt at man skulle kunne skru av/gjemme coach marks for erfarne veiledere. Dette er nyttig for førstegangsbrukere eller ved innføring av ny funksjonalitet og er med på å innfri et av de interne prinsippene på interne systemer: "_Jeg opplever mestring og progresjon etterhvert som jeg lærer systemet_."

Jeg vet ikke hvordan dette utviklet seg for AO's del men tenkte å spille inn dette som forslag til sentralt DS komponent da det er flere som kunne hatt nytte av dette, tenker også på egen Pesys kontekst.

**DS eksempler**
https://spectrum.adobe.com/page/coach-mark/

![coach marks](https://github.com/navikt/aksel/assets/86958516/35f40794-d12f-4e34-9391-77744f14fdff)

**Comment by Lilyngs** [comment]
Hei og takk for innspill! Dette er noe flere har ytret ønske om. Vil være nyttig for DS å se på etterhvert. Supert med eksempel du linket til :)

**Comment by sjur-gr** [comment]
Lagt ut forslag i Alpha UI kit og satt opp en discussion for tilbakemelding
