### ISSUE TITLE
[BUG] Toggle Group - inkonsistent bredde

### ISSUE THREAD

**Issue by ivoiv** [navikt/Designsystemet#2120]
## Hva er feilen/problemet?
Bredden på ToggleGruppen endrer seg  bittelitt når man huker det siste elemenet av og på.

## Steg for å reprodusere problemet (valgfri)
Klikk på siste element i Demo. - bredde endrer seg
Klikk så på et annet element - bredde endrer seg igjen

## Eksempel/Tilleggsinformasjon (valgfri)
https://aksel.nav.no/komponenter/core/toggle-group#togglegroupdemo-default

```[tasklist]
### Tasks
- [ ] Endre Selected button til å ha font-weight: 400
```

**Comment by KenAJoh** [comment]
Hei, dette er siden font-weight blir endret fra `regular` til `semibold` på aktive elementer. Er en litt uheldig effekt at størrelsen endrer seg, så skal ta en runde med teamet om dette er noe vi kan fikse 👍

**Comment by KenAJoh** [comment]
Fikset i `v4.11.2` 🚀
