### ISSUE TITLE
[Nytt ikon]: Sketch

### ISSUE THREAD

**Issue by Ildest** [navikt/Designsystemet#2133]
### Navn på ikonet

Sketch

### Eksempel på ikonet

Ønsker meg et ikon som symboliserer skisser til løsning.

**Comment by KenAJoh** [comment]
Hei, finner ikoner for dette i nyeste versjon nå 5.2.0 🚀
https://aksel.nav.no/ikoner/PencilBoard
https://aksel.nav.no/ikoner/PencilLine

**Comment by Ildest** [comment]
Takk!
