### ISSUE TITLE
[Innspill til komponent]: <Combobox />

### ISSUE THREAD

**Issue by lurajon** [navikt/Designsystemet#2156]
<img width="526" alt="Screenshot 2023-08-11 at 14 28 46" src="https://github.com/navikt/aksel/assets/1674209/91e3de0d-f2a7-4cbc-ae95-fcc9d955221c">
### Tilbakemelding

Supert! Vi kommer til å ta denne i bruk etterhvert!

Jeg testet med å legge til egen verdi. Her blir det lagt til en verdi, men tekstfeltet fjerner ikke det jeg hadde tastet inn. (testet fra aksel komponent bibliotek side)

**Comment by it-vegard** [comment]
Klarer ikke helt å finne hvilken versjon det ble fikset i, men så vidt jeg kan se er denne feilen rettet i de nyeste versjonene av designsystemet (også < v5.0.0).
