### ISSUE TITLE
[Innspill til komponent]: <CopyButton />

### ISSUE THREAD

**Issue by karihamnes** [navikt/Designsystemet#2157]
### Tilbakemelding

Hei!

Active text-varianten gir fint klikkområde, og det blir veldig tydelig hva man har kopiert. Men, det virker rart å ikke ha mulighet til å ha kopi-symbolet på høyre side. I mange tilfeller vil man f.eks. ha en prompt på det elementet som skal kopieres, f.eks. "Tlf: 927 64 290", og da blir det nokså "busy" med kopiknappen foran.

I personlinjer på interne flater er det flere typer informasjon der det er aktuelt med en slik konstruksjon, og så kan man selvfølgelig løse det slik som foreslått (at man kun bruker knappen bak i breadcrumbs). Men det gir mindre klikkområde og mindre tydelig sammenheng mellom det som kopieres og kopiknappen. 

Kunne det være mulig for alle knappe-variantene av CopyButton å kunne velge om man skal ha selve kopi-symbolet til høyre eller venstre for det som skal kopieres, slik man jo også har for Button? Og at det også finnes i Figma? 
```[tasklist]
### Tasks
- [x] Legge til prop for `iconPosition` slik Button har
- [ ] https://github.com/navikt/aksel/issues/2175
```

**Comment by KenAJoh** [comment]
@sjur-gr Ønsker vi å legge til en prop for dette i Figma også (som Button har)?

**Comment by sjur-gr** [comment]
Jepp. Legger til Icon left og Icon right i Figma, samme som Button.

**Comment by KenAJoh** [comment]
Hei, nyeste versjon av Aksel har nå en egen prop `iconPosition` i kode hvis man ønsker å bytte side på ikon 🚀 Skal også være oppdatert i Figma med samme prop-navn som vanlig Button
