### ISSUE TITLE
[BUG] navds-date__field-button har hardkodet border-radius og det virker ikke så godt om vi overstyrer de andre spacing tokens

### ISSUE THREAD

**Issue by otenav** [navikt/Designsystemet#2158]
## Hva er feilen/problemet?

DatePicker sin knapp har hardkodet border-radius til 3px. På arbeidsplassen.nav.no har vi satt `--a-border-radius-medium` til å være 6px og vi ser da at denne knappen får litt feil avrunding i hjørnene ved hover effekt.

![Skjermbilde 2023-08-14 kl  13 56 34](https://github.com/navikt/aksel/assets/29566394/9acf29cd-35a4-4f52-984f-8fb221325e8b)

**Comment by KenAJoh** [comment]
Hei, bør være fikset i `v4.11.1` snart 🚀 Tusen takk for innspillene rundt tokens og theming, hjelper oss utrolig mye med å få utviklet et bedre produkt litt etter litt 😄
