### ISSUE TITLE
[BUG] Hvit hake i Checkbox blir for lys i dark mode 

### ISSUE THREAD

**Issue by otenav** [navikt/Designsystemet#2166]
## Hva er feilen/problemet?

På Arbeidsplassen så prøver vi ut dark theme. På Checkbox så blir den hvite haken for lys, dessuten er den ikke lik streken for  indeterminate option. Ser i koden at den hvite haken settes som background-image med en svg av hvit hake.

![Skjermbilde 2023-08-15 kl  09 54 25](https://github.com/navikt/aksel/assets/29566394/4780ef0f-2c3d-4751-8599-b890299c37b4)

Det samme skjer med haken i readOnly mode, da blir haken for mørk.

![Skjermbilde 2023-08-15 kl  10 56 30](https://github.com/navikt/aksel/assets/29566394/b9ecdc41-5579-44df-9ab8-ca7bd4325f71)

```[tasklist]
### Tasks
- [x] Bytte ut Base64 checkmarks med SVG
- [x] Oppdatere bruk av tokens på checkmark
```

**Comment by KenAJoh** [comment]
Er fikset i nyeste versjon 🚀 Checkmark bruker nå svg, og vil ha samme farger som "indeterminate" har nå
