### ISSUE TITLE
[Innspill til komponent]: <Combobox />

### ISSUE THREAD

**Issue by hconhegg** [navikt/Designsystemet#2174]
### Tilbakemelding

I single select mode så kommer det mellomrom etter at du har valgt feltet som om du skal velge flere, den burde vel bare få valgt feltet og lukket menyen? 
[Eksempel](https://github.com/navikt/aksel/assets/32221678/1cd0c497-f659-4c0c-a432-56b4b5ac262c)

**Comment by it-vegard** [comment]
Med endringen i #2177 lukker nå nedtrekkslisten seg når man velger en verdi (for single-select).

Når det kommer til "mellomrommet", så kommer det av at det fremdeles er mulig å skrive/søke i inputfeltet, mens den valgte verdien vises til venstre for teksten. Her har vi vurdert om vi skal gjøre utseendet likere til chips i multiselect, men vi ønsker i utgangspunktet ikke å endre dette, fordi den i single select ikke skal være klikkbar. (I multiselect kan brukeren trykke på Chips for å fjerne valg) Får vi flere tilbakemeldinger på at det er forvirrende, så tar vi det opp igjen da.
