### ISSUE TITLE
[Innspill til komponent]: <Combobox />

### ISSUE THREAD

**Issue by hconhegg** [navikt/Designsystemet#2181]
### Tilbakemelding

Overskriv formattering ved valg av predefinerte verdier når man autocompleter med enter.
[Eksempel](https://github.com/navikt/aksel/assets/32221678/5b7db7ea-ed6a-49cd-a5c9-9f8f95036fef)

**Comment by it-vegard** [comment]
Har omsider fått pushet en fiks for denne.

Løsningen vi gikk for, var at vi viser bokstavene som de skrives inn, men når man velger et valg/trykker enter, så bruker vi formatteringen fra nedtrekkslisten. For nye verdier bruker vi formatteringen as-is.
