### ISSUE TITLE
[BUG] Fokus med søk når man åpner med CTRL+B

### ISSUE THREAD

**Issue by karl-run** [navikt/Designsystemet#2188]
## Hva er feilen/problemet?

Når man åpner søk på aksel med CTRL+B så er X-en fokusert. Åpner søk med klikk så er ingenting foksuert.

## Steg for å reprodusere problemet (valgfri)

1. Åpne Søk på aksel :smile: 

## Eksempel/Tilleggsinformasjon (valgfri)

CTRL+K when? :angel:

**Comment by it-vegard** [comment]
Fokus havner fremdeles på lukkeknappen/X-en, men vi bruker :focus-visible, slik at ikke fokusmarkering vises når man bruker mus, da det ofte kan virke forstyrrende.

Legger du til følgende styling på knappen, så vil du se at fokuset settes der også når du åpner med mus:

```
button.navds-button.navds-button--tertiary-neutral.navds-button--medium.navds-button--icon-only:focus {
  outline: 3px solid black !important;
}
```

**Comment by KenAJoh** [comment]
Skal få fikset 👍 Native `<dialog>` fokuserer første element, som er lukkeknapp nå på grunn av `flex-row-reverse`
