### ISSUE TITLE
[Innspill til komponent]: <Alert />

### ISSUE THREAD

**Issue by daghelgescott** [navikt/Designsystemet#2189]
### Tilbakemelding

Synes det er litt mye spacing mellom ikon og tekst på inline alert. I hvert fall for small-varianten. Kunne den heller hatt 8px ga (i dag er den 12px)?

**Comment by Lilyngs** [comment]
Det skal vi fikse :)

**Comment by Lilyngs** [comment]
Endret small variant i Figma på alle typer, default, inline og full width.
