### ISSUE TITLE
[Innspill til ikon]: Paperplane

### ISSUE THREAD

**Issue by macbruker** [navikt/Designsystemet#2194]
### Tilbakemelding

Litt pikselpirk. Kanskje subjektivt også 🤓 

![image](https://github.com/navikt/aksel/assets/1032194/a1faba77-1391-43b6-92cc-d3eb11897820)

Ved plassering av dette ikonet i en sirkel, virker det ikke optisk sentrert. Testet å flytte ikonet 1px til høyre og synes det ble bedre. Laget en egen branch i Figma for å teste dette.

https://www.figma.com/file/eABsIuirJArdgF5P9nPQZp/Paperplane-alignment?type=design&node-id=2280-63&mode=design&t=SU7knt3IJsPXYmfq-4

**Comment by sjur-gr** [comment]
Bra forbedring! Det er publisert i Figma, klar for sync med kode.
