### ISSUE TITLE
[Innspill til komponent]: Endre token-navn i <Table>

### ISSUE THREAD

**Issue by otenav** [navikt/Designsystemet#2203]
### Tilbakemelding

Det er en token `--a-table-sort-button-sorted-text`, burde denne hete `--ac-table-sort-button-sorted-text` med en ekstra `c`, slik at det blir likt med andre tokens på komponent-nivå?

**Comment by KenAJoh** [comment]
Takk for headsup! Får ut en fix på det. Lager en fallback til gammelt navn slik at ingenting vil brekke hos dere
```
color: var(--ac-table-sort-button-sorted-text, var(--a-table-sort-button-sorted-text, var(--a-text-action-on-action-subtle)));
```
