### ISSUE TITLE
[Innspill til komponent]: Token for text color i <Panel>

### ISSUE THREAD

**Issue by otenav** [navikt/Designsystemet#2205]
### Tilbakemelding

På `Panel` kan jeg både endre token for `-ac-panel-border` og `-ac-panel-bg`, og ønsker også å kunne endre text color på teksten inne i panelet.

**Comment by KenAJoh** [comment]
Hei, vi tenker dette ikke er noe selve panelet bør ha ansvar for i de fleste tilfeller. Vi tenker heller at komponentene inne i panelet (Heading, BodyLong etc) løser dette.
