### ISSUE TITLE
[Innspill til komponent]: <Combobox />

### ISSUE THREAD

**Issue by enstulen** [navikt/Designsystemet#2223]
### Tilbakemelding

Hva med å implementere fuzzy-search? Det hadde vært nyttig mtp stavefeil og generell brukeropplevelse.

**Comment by it-vegard** [comment]
Hei.

Da tenker du på søk etter lignende ord for å ta høyde for skrivefeil? F.eks. `Misisipi ~ Mississippi`?

I utgangspunktet er ikke dette noe vi har planlagt å legge inn, men det er mulig å implementere det i appen som bruker komponenten.

Ved å gjøre søk basert på `onChange`-eventet og sende inn `filteredOptions`, så tar appen utenfor kontroll over søket.
Det kan både brukes for søk i store datamengder (f.eks. ved søk i en database) og om man ønsker en annen søkealgoritme.

Det som kan være relevant, er å legge til søk etter delvis treff. F.eks. `anana ~ Banana`.
Vi hadde det i en tidlig versjon, men droppet det pga. autoComplete fungerte best med søk fra starten av ordet.
Men her kunne vi for eksempel brukt søk etter delvis treff når man ikke har autoComplete aktivert.

Ville det gitt verdi for dere?

**Comment by enstulen** [comment]
Ja, tenkte både for å ta høyde for skrivefeil og delvise treff, men delvise treff i seg selv vil gi mesteparten av verdien. 
Eksempelvis [her](https://www.nav.no/fyllut-ettersending/lospost) så vil man kunne søke på "oppsigelse" og få opp "Permittering og masseoppsigelser" 

Takk for tips om å ta kontroll over søket selv 👍🏻

**Comment by it-vegard** [comment]
Vi har nå merget forbedret søk med delvise treff/treff inni teksten.
Vi tar fremdeles ikke høyde for skrivefeil, men forhåpentligvis gir dette en bedre søkeopplevelse!
