### ISSUE TITLE
[Innspill til komponent]: <Textarea />

### ISSUE THREAD

**Issue by EspenSteinum** [navikt/Designsystemet#2224]
### Tilbakemelding

Når et Text Area med max length counter er satt med en maks høyde på feltet, vil inputteksten etterhvert legge seg oppå/bak counteren. Dette gjør det vanskelig å lese de to tekstene.

Vi har et tekstfelt som skalerer i høyden med mengde tekst, men bare opp til et visst maksnivå. Når teksten blir lenger blir den scrollbar. Vi er nødt til å ha et maksnivå for at det skal bli plass til annet viktig innhold på skjermen ( i dialogløsningen for arbeidsoppfølging).

**Comment by karihamnes** [comment]
Se også https://github.com/navikt/aksel/issues/2341

**Comment by karihamnes** [comment]
Her er forøvrig eksempel på hvordan det kan bli dels på grunn av denne feilen, og dels på grunn av plasseringen til venstre, innsendt fra en veileder (navnet er sladdet).
![teller](https://github.com/navikt/aksel/assets/61583515/c59e0e27-b623-4586-835a-451e86a308af)

Fra veilederen: 
"Hvorfor står antall resterende tegn i en melding nede til venstre?
Den kommer alltid i konflikt med annen tekst, som blir uleselig.
Hadde antall tegn stått til høyre, ville sannsynligvis tekst vært mer lesbar."

**Comment by sjur-gr** [comment]
Dette er fikset i kode nå. Kommer snart i Figma 🤘
