### ISSUE TITLE
[Innspill til komponent]: <Skeleton />

### ISSUE THREAD

**Issue by cskrov** [navikt/Designsystemet#2233]
### Tilbakemelding

Om man benytter `<Skeleton>` i en paragraf, `<p>` (f.eks. `<BodyShort>`), ender man opp med ugyldig DOM fordi man har `<div>` inni en `<p>`.

Forslår å legge til `as` eller annen måte å få `<Skeleton>` til å rendre som `<span>`.
Kanskje det er default for `variant="text"`?

**Comment by KenAJoh** [comment]
Hei, har du et kodeeksempel vi kunne sett på for hvordan Skeleton er brukt her? I de fleste tilfeller ville vi anbefalt å ikke ha skeleton inne i `<p>`-elementer. Dette var også bakgrunnen for at vi ikke la til `as`-prop. Men kan selvfølgelig være edge-caser som vi ikke hadde sett for oss!

**Comment by cskrov** [comment]
I dette spesifikke tilfellet er det navn på en bruker, som lastes inn asynkront, i en tekst.

Noe slikt som dette:
```jsx
<BodyShort>
   {name ?? <Skeleton variant="text" width={100} />} er navnet på brukeren.
</BodyShort>
```

Alternativet for oss blir å gjøre om `<BodyShort>` til en `<div>`.

**Comment by KenAJoh** [comment]
Har da lagt til en `as` prop for Skeleton der man kan bytte mellom `div` og `span` i `v5.3.2` 🚀

**Comment by cskrov** [comment]
Supert, men det er ikke satt noen `display` regel for `span`-versjonen som gjør at `width` fungerer.

Endte opp med å sette inline style `style={{ display: 'inline-block' }}` som en workaround.

**Comment by KenAJoh** [comment]
Bør være fikset i nyeste verjson nå 🤞
