### ISSUE TITLE
[Innspill til komponent]: <ErrorSummary />

### ISSUE THREAD

**Issue by JonathanVidmar** [navikt/Designsystemet#2244]
### Tilbakemelding

Legge til border radius som en token man kan overstyre.

**Comment by KenAJoh** [comment]
Hei 👋 Har dere en spesifikk border-radius dere tenkte å bruke? Vi vurderer å endre standard border-radius til 8px 🤔 Slipper da en egen token for det.  🤞 

![Screenshot 2023-09-06 at 11 14 14](https://github.com/navikt/aksel/assets/26967723/5123c47e-5095-49c0-914c-bfdaa45c251d)

**Comment by JonathanVidmar** [comment]
Vi tänkte 8px på denna faktiskt 😅 Så på denna komponenten ville inte en token behövts i så fall 👌
