### ISSUE TITLE
[Innspill til komponent]: <Chips />

### ISSUE THREAD

**Issue by sjur-gr** [navikt/Designsystemet#2247]
### Tilbakemelding

God dag! Har et ønske om at `toggle chip med checkmark` endres til noe a la dette. Så slipper vi at rekken med chip hopper og spretter. I dag kan CLSen (Cumulative Layout Shift) potensielt øke dersom de plutselig brekker og dytter innholdet som ligger under lengre ned.

Vet at det finnes uten checkmark også, men i et filter hvor vi ikke vet om det kan dukke opp 2 eller flere chips, må vi bruke toggle chip med chekmark, slik at vi er konsekvente i oppførsel og GUI.

![image (13)](https://github.com/navikt/aksel/assets/82579704/63d09b98-c726-48a9-a889-66f6aad0bcac)

**Comment by JorgenMaristuen** [comment]
Kan man alternativt utjevne med lik spacing på høyre og venstre side?
![image](https://github.com/navikt/aksel/assets/86107432/c4bd24ff-a227-4c54-929b-e77bf10d0b28)

**Comment by sjur-gr** [comment]
Forslag som venter på tilbakemelding

<img width="447" alt="Alternativer" src="https://github.com/navikt/aksel/assets/82579704/1e8c4e3f-edbf-4c2f-a33e-ebb79ed534ed">
