### ISSUE TITLE
[Innspill til komponent]: <Alert /> Icon gap

### ISSUE THREAD

**Issue by Trent-NAV** [navikt/Designsystemet#2253]
### Tilbakemelding

Ref. https://github.com/navikt/aksel/issues/2189

Ser at Alert er justert for ikke lenge siden men utvider innspillet til @daghelgescott med ønske om ytterligere justering. 

Syns det er rart at Small inline alert har 8px icon gap når Small btn har 6px. Jeg mener alert burde følge samme avstandskonsept som btn og forøvrig alt som har icon variant. 

I Pesys kan Small inline alert, Xsmall tertiary btn og Xsmall Copy btn stå side ved side, Xsmall har 4px icon gap og da blir differansen til Small inline alert merkbar. Hvis Small alert fikk samme gap som Small btn med icon (6px) så hadde differansen til Xsmall btn i alle fall blitt redusert - men optimalt kunne Alert også hatt en compact variant som matchet Xsmall btn på 6px gap for oss på IF som bruker den størrelsen. Da blir inline alert enda mer plasseringsvennlig, hvilket er et poeng siden inline varianten gjerne står som navnet tilsier inline og tidvis i selskap med andre innslag som vist her. Både Xsmall btn og Small inline alert bruker 16px type size så det hadde ikke vært nødvendig med noe compact justering for tekst, kun for gap 😀

**Brukseksempel med Xsmall Copy btn, Xsmall CTA btn og Small inline alert**

![gaps_eks](https://github.com/navikt/aksel/assets/86958516/7dc10433-1a16-4a96-854f-3dddaea86fa1)

**Ulik icon gap mellom Small**

![gaps 1_1](https://github.com/navikt/aksel/assets/86958516/3e28c622-ab73-445e-b688-d518a3d70ebb)

**Comment by KenAJoh** [comment]
Hei, vi har sett litt på denne og tenker vi ikke ønsker å tilby denne muligheten gjennom selve Alert-komponenten. Kan løse dette gjennom bruk av andre komponenter fra Aksel, f.eks 
```
<HStack gap="2">
    <Ikon />
    <div>tekst</div>
</HStack>
```
Da kan man tilpasse ikon/tekst basert på hva som passer best 🤞
