### ISSUE TITLE
[Nytt ikon]: Bok

### ISSUE THREAD

**Issue by AndreaPaulsen** [navikt/Designsystemet#2254]
### Navn på ikonet

Bok

### Eksempel på ikonet

Bok og stabel med bøker. 
![image](https://github.com/navikt/aksel/assets/144274683/14d33bc1-4f57-4e04-93d0-43abfe2bc6a6)

**Comment by sjur-gr** [comment]
Funker dette?

<img width="1177" alt="Skjermbilde 2023-09-22 kl  16 54 08" src="https://github.com/navikt/aksel/assets/82579704/de91a02a-5bbd-45bb-b6f7-495020f5c710">

**Comment by AndreaPaulsen** [comment]
Hei,

Ja, absolutt! Veldig bra😊



22. sep. 2023 kl. 16:55 skrev Sjur ***@***.***>:

﻿

Funker dette?

[Skjermbilde 2023-09-22 kl  16 54 08]<https://urldefense.com/v3/__https://user-images.githubusercontent.com/82579704/269975335-de91a02a-5bbd-45bb-b6f7-495020f5c710.png__;!!M12l6qNq_w!vx3VHEV8T1-Walrg-3aMFhCrgJ76SEsKeXCwjVb-WNxu7TJpks9MiS4LlMk2hxKjMS0Ml_-T8R0glqyVMQjILrr2OPQ_PZIG$>

**Comment by sjur-gr** [comment]
Publisert i Figma, klar for kode @KenAJoh

**Comment by KenAJoh** [comment]
Er nå tilgjengelig i v5.6.0 i kode (og på nettsiden)
#2283
