### ISSUE TITLE
[Innspill til komponent]: <Button />

### ISSUE THREAD

**Issue by Trent-NAV** [navikt/Designsystemet#2255]
### Tilbakemelding

Hvorfor er ikke lenger Danger del av variantstrukturen til CTA buttons (Action og Neutral) i Figma? Den finnes kun tilgjengelig som eget komponent i Core UI kit. Komponenter som har CTA buttons som en integrert del av komponentstrukturen mangler også Danger variant. Feks Modal.

**Comment by sjur-gr** [comment]
Stemmer. Knappene er forskjellige komponenter. Det gjør at det ikke er så lett å blande stilene som f.eks. Action og Neutral i en gruppe. Har du behov for å bytte er det bare å swap’e komponenten. Btw, publiserte akkurat en oppdatering til Modal. Nå kan du swap’e knappene med en prop.
