### ISSUE TITLE
[Innspill til komponent]: <Combobox />

### ISSUE THREAD

**Issue by KenAJoh** [navikt/Designsystemet#2257]
### Tilbakemelding

<img width="360" alt="Screenshot 2023-09-07 at 10 21 28" src="https://github.com/navikt/aksel/assets/26967723/ec79f71b-984a-4d10-a1b0-e526e9836836">

Ved bruk av Combobox på andre bakgrunner en `#fff` vil bare delere av komponenten ha en bakgrunnsfarge

Forslag:
- Sette background på hele elementet

**Comment by it-vegard** [comment]
Jeg klarer ikke replisere denne. (Setter bakgrunnsfarge på `body` i Storybook-eksempelet.)

Har du mer detaljer om når det oppstår/hvordan den kan repliseres?

**Comment by KenAJoh** [comment]
Klarer heller ikke replikere lengre, så antar det er fikset 👌 Spesifikt denne linjen løser det `navds-combobox__wrapper-inner navds-text-field__input`
