### ISSUE TITLE
[Innspill til ikon]: Tablet

### ISSUE THREAD

**Issue by KenAJoh** [navikt/Designsystemet#2263]
### Tilbakemelding

https://aksel.nav.no/ikoner/Tablet

<img width="66" alt="Screenshot 2023-09-07 at 13 46 52" src="https://github.com/navikt/aksel/assets/26967723/1a820765-b555-46f0-8ed9-79ae24073971">

Ikonet i dag kan lett tolkes som en badevekt 🤔

**Comment by sjur-gr** [comment]
@KenAJoh justert design er publisert i Figma.
