### ISSUE TITLE
[Innspill til komponent]: <CopyButton />

### ISSUE THREAD

**Issue by Trent-NAV** [navikt/Designsystemet#2264]
### Tilbakemelding

- Veldig populær kopieringsfunksjon blant saksbehandlere. (Målt i Amplitude)
- Fine interaksjonsmomenter i siste versjon!
- Innebygget tooltip er supert. 
- Kudos som vanlig for interaktiv komponent versjon i Figma. Det settes stor pris på i protype sammenhenger 👍

Skulle man ønske seg noe til neste iterasjon så kunne det vært at variantene i tillegg var anordnet uten de typiske CTA button statene som okkuperer hele containeren men kun som icon+text med en hover state som kun påvirket selve vektorformen og teksten (klikkflaten ivaretas uansett). Da vil den bli enda mer plasseringsvennlig i tight UI og fremstå mindre fremtredende når den står oppstilt flere ganger i samme seksjonsfelt med lite mellomrom og brukerne klikker på flere ulike mange ganger i samme session (kopiering av f.nr./pers.nr etc) Men veldig bra med Xsmall variant for alle utrykkene! 🥇

**Comment by KenAJoh** [comment]
Har skjønt det slik at denne er løst etter dialog med Linda med tokens, så lukker issuet.
