### ISSUE TITLE
[NEW] Accordion-warnings

### ISSUE THREAD

**Issue by KenAJoh** [navikt/Designsystemet#2280]
## Hva?

Accordion bør gi warning/error når den er brukt feil
Eksempel:
- Accordion.Item brukes uten å være i en Accordion-wrapper

## Hva løser dette?

Sjekke at AccordionContext finnes og gi feilmelding ellers

**Comment by JulianNymark** [comment]
error / warning on missing wrapper <Accordion> (floating Accordion.item, header... etc ), warning on fewer than 2 items
