### ISSUE TITLE
[Innspill til komponent]: DatePicker

### ISSUE THREAD

**Issue by frodehansen2** [navikt/Designsystemet#2284]
### Tilbakemelding

Jeg ønsker at en også ta med onWeekNumberClick fra react-day-picker. Nå ser det ut til at det er kun disse som hentes ut fra DayPickerBase.

 `   Pick<DayPickerBase, "month" | "onMonthChange" | "today" | "onDayClick"> `

**Comment by frodehansen2** [comment]
https://github.com/navikt/aksel/pull/2285

**Comment by KenAJoh** [comment]
`onWeekNumberClick` er nå tilgjengelig i v5.6.0 🚀 #2283
