### ISSUE TITLE
[Nytt ikon]: ChevronDownUpIcon

### ISSUE THREAD

**Issue by ivoiv** [navikt/Designsystemet#2288]
### Navn på ikonet

ChevronDownUpIcon

### Eksempel på ikonet

https://aksel.nav.no/ikoner/ChevronUpDown bare omvendt for å representere motsatt hendelse.

**Comment by KenAJoh** [comment]
Hei, vi er ikke helt sikker på bruken/hvordan denne ser ut så ønsker gjerne et eksempel 🙌 
Ville f.eks https://aksel.nav.no/ikoner/Expand og https://aksel.nav.no/ikoner/Shrink løst problemet?

**Comment by ivoiv** [comment]
Glemte denne bort!

Jeg bruker ChevronUpDown til en knapp som utvider(ExpandRow) samtlige rader i en tabell.
Tenkte ChevronDownUp kunne brukes til minimering.

Jeg føler Expand/Shrink er standard for å utvide bilder/flater/faner/tekstfelt, men den ga lite mening i en tabell.

**Comment by KenAJoh** [comment]
Har nå lagt til disse ikonene som vi håper løser dette 🚀 
- https://aksel.nav.no/ikoner/ChevronDownUp
- https://aksel.nav.no/ikoner/ChevronUpDown
