### ISSUE TITLE
[Innspill til komponent]: <DatePicker />

### ISSUE THREAD

**Issue by Trent-NAV** [navikt/Designsystemet#2289]
### Tilbakemelding

Populært komponent som er inkludert i mye nytt designarbeid i mitt miljø 👍
Veldig bra med interaktivitet i Figma versjon 👍  

Er planen at DatePicker skal oppdateres i Figma til å matche live Aksel demo? Det er props som ikke er mulig å gjenta med komponentet i prototyper og det er ulikheter mellom utrykk i kode versjonen og Figma. Et eksempel er disabled days der calender cell i kodet versjon er overstrøket og i Figma dimmet, det kan fort skape misforståelser mellom design og utvikling når man bruker prototyper som referanse. Håper på så mye sync som mulig.

**Comment by sjur-gr** [comment]
Justerer på både design og kode.
Tar med https://github.com/navikt/aksel/issues/2284 i oppgaven også.

**Comment by sjur-gr** [comment]
Klar for en sync @KenAJoh.
[Demo og notater i branchen](https://www.figma.com/file/m0qpSPpsnNC9DwdmerGqJH/branch/P3ylvjKJKoXrh5F1J4SRSG/Core-UI-kit?type=design&node-id=38610%3A19259&mode=dev)

**Comment by sjur-gr** [comment]
Ta med denne oppgaven også? https://github.com/navikt/aksel/issues/2152
