### ISSUE TITLE
[Innspill til komponent]: <Accordion />

### ISSUE THREAD

**Issue by KenAJoh** [navikt/Designsystemet#2294]
### Tilbakemelding

Ved hover på Accordion Header har innholdet ingen padding top

<img width="728" alt="Screenshot 2023-09-18 at 09 10 08" src="https://github.com/navikt/aksel/assets/26967723/e14c71b6-9fd0-4079-998d-6c9838dd16f6">

// **0.5rem**
<img width="670" alt="Screenshot 2023-09-18 at 09 10 33" src="https://github.com/navikt/aksel/assets/26967723/cbf17805-bdce-4ccf-a84a-9610e7272a99">

// **0.25rem**
<img width="666" alt="Screenshot 2023-09-18 at 09 10 42" src="https://github.com/navikt/aksel/assets/26967723/5989152f-69a8-4098-9175-378acc07b791">

**Comment by sjur-gr** [comment]
Ser at vi har 0.75rem padding på høyre side, det samme på venstre uten `indent`. Tester med 0.75rem som padding top også. Funker det?
https://www.figma.com/proto/m0qpSPpsnNC9DwdmerGqJH/branch/onTL5HTNjRCMR2fsaVoAZS/Core-UI-kit?page-id=12133%3A32272&type=design&node-id=38524-3512&viewport=-1711%2C1161%2C0.57&t=CeAa43yUlk6M7guq-1&scaling=min-zoom&starting-point-node-id=38524%3A3512&mode=design

**Comment by KenAJoh** [comment]
🙌 Fungerer det!

**Comment by sjur-gr** [comment]
Cool. Gi meg et hint før den går live, så skal jeg justere Figma samtidig.

**Comment by KenAJoh** [comment]
Er klar til merge nå https://github.com/navikt/aksel/pull/2310

**Comment by sjur-gr** [comment]
Publisert i Figma
