### ISSUE TITLE
[Innspill til komponent]: <Textarea />

### ISSUE THREAD

**Issue by tu55eladd** [navikt/Designsystemet#2298]
### Tilbakemelding

Jeg skal implementere et design hvor jeg trenger at TextArea fyller høyden til sin container men det er ikke så lett slik komponenten er implementert nå. Se bilder og forklaring under:
![Skjermbilde 2023-09-18 kl  16 03 28](https://github.com/navikt/aksel/assets/7754140/90804152-9f93-48ca-9655-9247a3c75755)
![Skjermbilde 2023-09-18 kl  16 04 34](https://github.com/navikt/aksel/assets/7754140/9cf6ca4a-5f68-4450-8fe4-8b6cabcdcca0)
På bildene over bruker jeg TextArea komponenten for å få den til å fylle høyden til containeren, den interne containeren som har klassen`navds-textarea__wrapper` følger etter og får riktig høyde men ikke selve textarea elementet. På bilde nr 2 har jeg highligtet css-griden som følger med `navds-form-field--medium` for å vise at den interne containeren har fått riktig høyde.

![Skjermbilde 2023-09-18 kl  16 04 07](https://github.com/navikt/aksel/assets/7754140/84409e6d-8db3-46bc-9397-6779c7683990)
Over er et bilde av hvordan designet ser ut ish, men jeg brukte native `textarea`

**Comment by KenAJoh** [comment]
~~Hei, fungerer det å sette `minRows` til et relativt høyt nummer i dette tilfellet?~~ Får det ikke til å fungere selv så antar det ikke fungerer for dere heller 🤷 Vi anbefaler for det meste at høyden til Textarea vokser etterhvert som man skriver, men dette er kanskje et fagsystem der dette ikke er så relevant?

**Comment by HalvorHaugan** [comment]
Hei! Nå har vi lagt til en eksperimentell feature der tekstfeltet slutter å utvide seg og får scrollbar når det ikke er mer plass i høyden. Vi tror det er bedre enn at feltet fyller høyden hele tiden. Hadde vært kult om du kunne teste ut dette og komme med tilbakemelding på hvordan det funker. Det aktiveres med propen `UNSAFE_autoScrollbar`.
