### ISSUE TITLE
[Innspill til komponent]: Spacing

### ISSUE THREAD

**Issue by Trent-NAV** [navikt/Designsystemet#2304]
### Tilbakemelding

I Figma versjonen av Spacing er fill varianten OLD/Global/lightblue-100 som er identisk med Surface/Info.subtle fra Core UI kit. Med andre ord identisk med en eksisterende semantisk surface farge. 

Jeg syns Spacing fill kunne hatt en farge som skiller seg ut mer når det praktiske formålet er at den skal fungere kontrasterende. Valører mer i retning av f.eks. rosa, lilla o.l matcher sjeldent noe som brukes i UI'et og innfrir funksjonen litt bedre. Kanskje man også kunne hatt noen innebygde varianter så kan folk velge det som passer best i layouten 😀

![spacing color](https://github.com/navikt/aksel/assets/86958516/d8272c62-ab4d-4d4d-9864-735c85f3dab6)

**Comment by sjur-gr** [comment]
Vi anbefaler ikke å bruke OLD. Spacing'en vi har ute nå bruker layout grid. Snarvei Shift+G for å skru av og på farge. Fargen kan du også justere selv i din fil.

**Comment by Trent-NAV** [comment]
Ok, takk for info. Sist jeg sjekket Spacing i Core så jeg fort at den ikke hadde noe fill default slik den har nå, så derfor endte jeg opp med den andre versjonen da den var, og fortsatt er, tilgjengelig. Ny fungerer fint slik du beskriver den.
