### ISSUE TITLE
[Innspill til komponent]: <Chips />

### ISSUE THREAD

**Issue by sjur-gr** [navikt/Designsystemet#2305]
### Tilbakemelding

<img width="992" alt="Skjermbilde 2023-09-21 kl  16 52 12" src="https://github.com/navikt/aksel/assets/82579704/5a8f7e70-b416-45ac-a291-746aa3775cbe">
Er det noe galt med kodeboksen? Ser ut som CopyBotton er veldig brei.

**Comment by KenAJoh** [comment]
Er by-design (lånt av tailwind). Men lett å endre på!

<img width="831" alt="Screenshot 2023-09-22 at 09 08 09" src="https://github.com/navikt/aksel/assets/26967723/1552b6c8-6fab-4828-baf1-79d9871307b4">
