### ISSUE TITLE
[Innspill til komponent]: <ErrorSummary />

### ISSUE THREAD

**Issue by Ildest** [navikt/Designsystemet#2306]
### Tilbakemelding

Hei! Tilbakelenka til Intro fungerer ikke. jeg kan gå fra Eksempel i høyre marg til andre emner, men ikke fra andre emner til intro. Minifeil, men tenkte dere ville vite om det :-).

**Comment by it-vegard** [comment]
Ser vi skjuler Intro-overskriften med `display: none`. Kanskje vi bare burde visuelt skjule den (f.eks. bruke sr-only) om vi skal lenke til den?

**Comment by KenAJoh** [comment]
> Ser vi skjuler Intro-overskriften med `display: none`. Kanskje vi bare burde visuelt skjule den (f.eks. bruke sr-only) om vi skal lenke til den?

👌 Tror det fikser saken

**Comment by Ildest** [comment]
Supert, takk!
