### ISSUE TITLE
[BUG] Popover i Timeline lukkes om en klikker både i Popoveren og en interaktiv komponent inni den, som en knapp

### ISSUE THREAD

**Issue by it-vegard** [navikt/Designsystemet#2308]
## Hva er feilen/problemet?

Popover i Timeline lukkes om man har en interaktiv komponent (f.eks. Button) i den og klikker på både den interaktive komponenten og resten av Popoveren. Rekkefølgen har ingenting å si.

Popoveren bør ikke lukke seg bare fordi man trykker rundt inni den.

## Steg for å reprodusere problemet (valgfri)

1. Legg til en knapp i  en Popover på https://aksel.nav.no/komponenter/core/timeline#timeline-interndemo-timeline.
2. Klikk på teksten i Popoveren og så på knappen ELLER først på knappen og så på Popoveren.
3. Popoveren lukker seg.

## Eksempel/Tilleggsinformasjon (valgfri)

Ble først rapportert på en urelatert PR (med video): https://github.com/navikt/aksel/pull/2303#issuecomment-1730980927.

Mistenker at det er noe onBlur-event her som trigges pga. man bytter hvilket element inni Popover som klikkes på.

**Comment by it-vegard** [comment]
Ser ut som feilen skyldes linje 121 i Pin.tsx: `e.target.previousSibling !== document.activeElement`.

Kan være et case for event.relatedTarget, som jeg snakket om på frontend-forum for en måneds tid siden? 😅

**Comment by KenAJoh** [comment]
Skal teste om relatedTarget løser det da 🤞
