### ISSUE TITLE
[Innspill til komponent]: <Alert />

### ISSUE THREAD

**Issue by mortentollefsen** [navikt/Designsystemet#2314]
### Tilbakemelding

Dette kan ha blitt diskutert før min tid. Synes vi bør ta en runde på om noen alert-typer bør ha role=alert/status.
Under tilgjengelighet står det: Alert-komponenten er ikke en ARIA live region og er ikke relatert til ARIA 
Jeg tenker meg likevel at både error og warning frontes som ganske viktige, og at det da kunne ha vært en live-region. Mulig dette har litt med om det er dynamiske meldinger eller om det alltid er sånn at alerten lastes med siden.

**Comment by KenAJoh** [comment]
Aksjonpunkter:
- Legge til JSDoc med `role` eksempel
- Oppdatere dokumentasjon på Aksel med info om bruk av role/status etc
