### ISSUE TITLE
[Innspill til komponent]: <List />

### ISSUE THREAD

**Issue by mortentollefsen** [navikt/Designsystemet#2318]
### Tilbakemelding

Er det sånn at title alltid vises som en heading?
I så fall tenker jeg at aria-labelledby blir støy siden den vises rett etter headingen og du da må høre den to ganger i stedet for å gå rett inn i lista. Absolutt ingen stor sak, men likevel.
... hehe, og så en liten digresjon: det som står under "Tilgjengelighet" er rimelig banale greier som sier veldig lite verdifult, eller tar jeg feil?

**Comment by KenAJoh** [comment]
Aksjonspunkter:
- Fjerne seksjon "Tilgjengelighet", skrive noe av det under "Egnet til"
- Fjerne `aria-labeledby` kobling mellom `ul` og heading.
- Teste om variant med title på hvert `li` element kan automatisk bli `<dl>`-liste
