### ISSUE TITLE
[Innspill til komponent]: <MonthPicker />

### ISSUE THREAD

**Issue by mortentollefsen** [navikt/Designsystemet#2321]
### Tilbakemelding

MonthPicker brukes typis i skjemaer. Der bruker selv jeg Tab fra felt til felt. Skrives en dato manuelt med feil får du en melding, feks: "Du må velge månede".
Jeg tror kanskje disse feilmeldingene med fordel kan merkes med role=status, særlig siden du ikke kan Tabbe til feilmeldingen. Det er da litt (eller egentlig temmelig) forvirrende å komme til Forrige/Neste måned i en modal uten Lukk knapp. Det betyr faktisk at du ikke har mulighet for å få lest feilmeldingen.

**Comment by KenAJoh** [comment]
Aksjonspunkter
- Oppdatere validation-eksempel med bedre håndtering av validering
