### ISSUE TITLE
[Innspill til komponent]: <Pagination />

### ISSUE THREAD

**Issue by mortentollefsen** [navikt/Designsystemet#2322]
### Tilbakemelding

Her synes jeg vi burde ha en default aria-label (i alle fall hvis jeg har skjønt komponenten riktig), husker ikke at jeg har sett den i bruk. aria-label=Sidevelger?

**Comment by KenAJoh** [comment]
Aksjonspunkter
- Se på å legge til `h`-tag med `sr-only` som første element i `nav`
- Evt oppdatere dokumentasjon med bruk av `aria-label` på `nav`-element?

![Screenshot 2023-10-30 at 13 53 39](https://github.com/navikt/aksel/assets/26967723/08ee0ee8-b27b-4631-aafb-2c12ce331efc)
