### ISSUE TITLE
[Innspill til komponent]: <Popover />

### ISSUE THREAD

**Issue by mortentollefsen** [navikt/Designsystemet#2323]
### Tilbakemelding

Mulig jeg tar litt feil her, altså, men denne bør muligens ha aria-expanded. Når du trykker på knappen oppfører den seg i alle fall som en expander, og du kan minimere vha. Escape. Du kan riktignok ikke minimere ved å trykke på knappen igjen: er det tilsiktet eller burde det være mulig?

**Comment by KenAJoh** [comment]
Fikset nå 🚀
