### ISSUE TITLE
[Innspill til komponent]: <Radio />

### ISSUE THREAD

**Issue by mortentollefsen** [navikt/Designsystemet#2324]
### Tilbakemelding

Her er det kanskje bare eksemplet på Aksel som er litt dumt! Nå leses alle valg som feil (error-varianten). Hadde kanskje vært lurt at kun ett valg var feil og de andre gyldige? Hvis validering skjer i etterkant er det i alle fall dumt at det ser ut som alle valg er ugyldige - hvordan skal du komme videre, da?

**Comment by KenAJoh** [comment]
Aksjonspunkter
- Oppdatere `Error`-eksempel med realistisk feilmelding
