### ISSUE TITLE
[Innspill til komponent]: <Tabs />

### ISSUE THREAD

**Issue by mortentollefsen** [navikt/Designsystemet#2325]
### Tilbakemelding

Her leses/vises alle fanenavn dobbelt opp, dvs. hvis aria-label på ikonet er det samme som teksten på knappen. Er teksten ulik, som i den første fanen i Aksel-eksemplet blir det feks:
"Historielogg Logg"
Forslag: skjul ikonet med aria-hidden dersom det finnes tekst på fanen.

**Comment by KenAJoh** [comment]
Aksjonspunkter
- Legge på en `span`-wrapper rundt ikonet og `aria-hidden` på ikonet hvis `label` er definert
- Oppdatere eksempel med bruk av aria-hidden på ikon når tekst er definert
