### ISSUE TITLE
[Innspill til komponent]: <Textarea />

### ISSUE THREAD

**Issue by mortentollefsen** [navikt/Designsystemet#2326]
### Tilbakemelding

Forslag: vi bruker role=status for meldingen om antall tegn hvis mulig. Synes vi bør teste om det funker like bra, men det tror jeg og vil være bedre rent semantisk (siden skjermlesere da kan bestemme mer hvordan de vil presentere meldingen - altså her om antall tegn igjen). Eksempelvis kan vi tenke oss at noen skjermlesere gjør det nøyaktig slik det er kodet nå mens andre skjermlesere ikke leser meldingen før det har gått en tidsperiode siden forrige tastetrykk. Særlig for mobile skjermlesere hadde det vært kult med en forsinkelse før du hørte antall tegn igjen, men det er en diskusjon vi kan ta når vi har tid.

**Comment by KenAJoh** [comment]
Aksjonspunkter
- Teste om `role=status` kan erstatte `aria-liave="polite"`
- Teste debounce på opplesing av tekst i `Counter`
