### ISSUE TITLE
[Innspill til komponent]: <Timeline />

### ISSUE THREAD

**Issue by mortentollefsen** [navikt/Designsystemet#2328]
### Tilbakemelding

Her kan vi godt beskrive hvordan aria-controls funker under avsnittet Tilgjengelighet.

Skulle gjerne sparret med noen om det som står ellers under Tilgjengelighet gir helt mening?

**Comment by KenAJoh** [comment]
Aksjonspunkter
- Oppdatere dokumentasjon
