### ISSUE TITLE
[BUG] Modal får svart text color

### ISSUE THREAD

**Issue by otenav** [navikt/Designsystemet#2337]
## Hva er feilen/problemet?

I den nye `<Modal>` så blir all tekst svart `rgb(0, 0, 0)`. Det ser ut som det skyldes at `color` arves fra `dialog` fra user agent styles. Fungerer ok på hvit modal, men i dark mode så fungerer ikke svart tekst på mørk modal. Er dette et issue dere kjenner til, og er det en workaround på dette?
```
dialog {          //user agent stylesheet
    color: canvastext;
}
```

**Comment by HalvorHaugan** [comment]
Vil dette løse problemet? https://github.com/navikt/aksel/pull/2340/files

**Comment by otenav** [comment]
Har testet det i dark mode, og det virker fint 👍
