### ISSUE TITLE
[Innspill til komponent]: <Textarea />

### ISSUE THREAD

**Issue by karihamnes** [navikt/Designsystemet#2341]
### Tilbakemelding

Har fått tilbakemeldinger fra veiledere som bl.a. skriver meldinger eller begrunnelser i text area at plasseringen av telleren (max length) er uhensiktsmessig plassert der den står til venstre, og burde stå på høyre side. Da er det mindre sannsynlig at den er forstyrrende ved skrivingen av meldingen. 

Det burde være mulig å velge om max length skal stå til venstre eller til høyre.

**Comment by sjur-gr** [comment]
Ta med denne også https://github.com/navikt/aksel/issues/2298

**Comment by karihamnes** [comment]
Ta med denne også som underlag, Espen har meldt dette tidligere, jeg visste ikke det -  https://github.com/navikt/aksel/issues/2224

**Comment by karihamnes** [comment]
Her er forøvrig eksempel på hvordan det kan bli dels på grunn av [denne rapporterte feilen](https://github.com/navikt/aksel/issues/2341#issuecomment-1740757184), og dels på grunn av plasseringen til venstre, innsendt fra en veileder (veiledernavnet er sladdet).
![teller](https://github.com/navikt/aksel/assets/61583515/c59e0e27-b623-4586-835a-451e86a308af)

Fra veilederen: 
"Hvorfor står antall resterende tegn i en melding nede til venstre?
Den kommer alltid i konflikt med annen tekst, som blir uleselig.
Hadde antall tegn stått til høyre, ville sannsynligvis tekst vært mer lesbar."
