### ISSUE TITLE
[Innspill til komponent]: <Modal />

### ISSUE THREAD

**Issue by EspenSteinum** [navikt/Designsystemet#2343]
### Tilbakemelding

Figma versjonen av denne komponenten har ikke scrollbart innhold.
Dette er viktig for at skissene skal fungere som prototype. I tillegg vil lange modaler ikke vises realistisk i skisser der høyden på skjermen er begrenset.

Det hadde også vært fint om det kunne legges inn en option for å vise Windows scrollbar i det scrollbare feltet, for å visualisere at bredden blir mindre på windows maskiner. Selv om scrollbaren trenger ikke å kunne rulle ved scrolling (jeg tror det er umulig i Figma).

**Comment by sjur-gr** [comment]
Jeg har testa litt og dette støttes i dagens modal.

- Velg varianten Fixed height: True
- Lag innholdet som en lokal komponent og legg den inn som Body slot
- Ut fra det jeg ser så vil scrollbar dukke opp der det er padding på høyre side. Jeg simulerte det ved å legge inn et rektangel med Absolute position utenfor framen.



https://github.com/navikt/aksel/assets/82579704/767e7ac7-379c-413d-baf7-7e5d441be529

**Comment by EspenSteinum** [comment]
Jeg la ikke merke til den switchen rett og slett. Fikk det til nå ja. Takk for hjelpen!

**Comment by sjur-gr** [comment]
Supert! Bare hyggelig.
