### ISSUE TITLE
[Innspill til ikon]: PersonPencilFill

### ISSUE THREAD

**Issue by LiseAndreassen** [navikt/Designsystemet#2352]
### Tilbakemelding

Vi benytter dette ikonet endel i vår saksbehandlingsløsning, og etter dere oppdaterte ikonene har blyanten blitt veldig liten.
Spesielt i liten variant og med fill ser det mer ut som en arm enn en blyant. Hadde det vært mulig å gjøre selve blyanten lenger eller større slik at den vises tydeligere?

**Comment by sjur-gr** [comment]
Har justert litt:

- Blyanten er litt smalere og skarpere
- Kuttet bort større del av kroppen, som gir mer avstand til blyanten

Sjekk om det funker bedre.


![Image](https://github.com/navikt/aksel/assets/82579704/ec9765bb-cad4-4466-9152-87b2d54edab5)

**Comment by sjur-gr** [comment]
Om det blir for smått vil jeg anbefale å bruke [PencilIcon](https://aksel.nav.no/ikoner/Pencil)

**Comment by sjur-gr** [comment]
Vi avslutter denne saken nå. Ta kontakt om det fortsatt er problemer.
