### ISSUE TITLE
[Innspill til komponent]: <Table /> | Excel style filtering

### ISSUE THREAD

**Issue by jonasnico** [navikt/Designsystemet#2353]
### Tilbakemelding

Hadde vært fint med en Excel style filtrering på kolonnene. Sånn at man kan fjerne visse entries et søk returnerer som ikke er relevante. 
Noe ala dette: [https://docs.telerik.com/devtools/winforms/controls/gridview/filtering/images/gridview-filtering-excel-like-filtering001.png](https://docs.telerik.com/devtools/winforms/controls/gridview/filtering/images/gridview-filtering-excel-like-filtering001.png)

**Comment by KenAJoh** [comment]
Hei, takk for innspill! Dette er noe vi ikke blir å se på med det aller første så vi tenker å lukke issuet for nå. 
Vi har på listen å se på hvordan filterering utføres og hvordan mer avanserte tabeller bør løses på sikt, så vi har det på listen for 2024 🚀
