### ISSUE TITLE
[BUG] Feil med <List.Item>

### ISSUE THREAD

**Issue by Mathiamu** [navikt/Designsystemet#2358]
## Hva er feilen/problemet?

Får feil når jeg prøver å bruke `<List.Item>` inne i en `<List>`. Nettsiden kræsjer med masse feilmeldinger i konsollen. `<ListItem>` fungerer. 

## Steg for å reprodusere problemet (valgfri)

Legger for eksempel inn eksempelkode fra Aksel:
```js
<List as="ul" title="Det kan også være aktuelt hvis du:">
	<List.Item>
		står i fare for å miste jobben etter å ha vært sykmeldt helt eller delvis i 12
		måneder, eller
	</List.Item>
</List>
```

## Eksempel/Tilleggsinformasjon (valgfri)
![image](https://github.com/navikt/aksel/assets/85442404/21d0e68f-6323-44c5-9ec0-ea5f991ce6b3)

I eksempelet har jeg lagt koden over rett under `.main-grid` section-elementet [i App.tsx i veilarbdetaljerfs](https://github.com/navikt/veilarbdetaljerfs/blob/main/src/App.tsx#L195).

navds-pakker i versjon 5.6.4, fungerte ikke i 5.3 eller 5.5 heller.
Feiler i Firefox, Edge og Chrome.

**Comment by Mathiamu** [comment]
Kan det ha noe med `swr`-pakka å gjøre? 🤷‍♂️

**Comment by KenAJoh** [comment]
Fant kilden til feilen:
Dette er i vite chunk ved kjøring av `npm run dev`
![Screenshot 2023-10-10 at 10 25 54](https://github.com/navikt/aksel/assets/26967723/a3b27e68-5ca9-4f2b-9296-dd3b147e21f0)

Har ikke funnet en løsning akkurat nå, men skal se om det er noe vi kan løse på vår side

**Comment by KenAJoh** [comment]
Skjer forresten bare når `customElements.define(WEB_COMPONENT_APPNAVN, Veilarbdetaljer);` er definert i `main.tsx` (kommenter ut + slette `.vite` i node_modules + restart dev)

**Comment by Mathiamu** [comment]
Ahhh, skjer diverse rare ting når vi bruker custom web components, så ikke overraskende at det er årsaken! 😅

**Comment by KenAJoh** [comment]
Fant en løsning på det 🎉 

Hvis man fjerner alle `import ListItem from '@navikt/ds-react/esm/list/ListItem';` og bare bruker `List.Item` i 
```
src/components/cv-innhold.tsx
src/components/cv/kompetanser.tsx
src/components/jobbonsker-innhold.tsx
```
samtidig fungerer det. Så lenge en av filene fortsatt bruker `import ListItem from '@navikt/ds-react/esm/list/ListItem';` brekker det for alle andre

**Comment by Mathiamu** [comment]
Okaay, tusen takk! 😄 🎉
