### ISSUE TITLE
[Innspill til komponent]: <Modal />

### ISSUE THREAD

**Issue by EspenSteinum** [navikt/Designsystemet#2359]
### Tilbakemelding

Det er ikke lenger noen mulighet for å lukke modalen ved å klikke utenfor modalen. Dette er en ganske vanlig praksis på modaler, så dette burde være et alternativ.

**Comment by ivoiv** [comment]
Jeg er enig.

Særlig info-modaler som brukes mer til informasjon enn noe annet bør ikke kreve at du finner OK-knappen for å få de vekk.
