### ISSUE TITLE
[BUG] MonthPicker piltast navigasjon fungerer ikke

### ISSUE THREAD

**Issue by ivoiv** [navikt/Designsystemet#2367]
## Hva er feilen/problemet?
Ser ut som at tastatur-navigasjonen med piltastene på MonthPicker ikke fungerer.
Fungerer greit i DatePicker men i MonthPicker kan du navigere kun i første måned-rad (Jan Feb Mar Apr).
Er det valgt noe i rad 2 eller 3 så fungerer ingenting. 

## Eksempel/Tilleggsinformasjon (valgfri)
[https://aksel.nav.no/komponenter/core/monthpicker](https://aksel.nav.no/komponenter/core/monthpicker)

**Comment by KenAJoh** [comment]
Fikset i nyeste versjon 🚀 Takk for heads-up!
