### ISSUE TITLE
[Nytt ikon]: 

### ISSUE THREAD

**Issue by andregroseth** [navikt/Designsystemet#2369]
### Navn på ikonet

Slack icon

### Eksempel på ikonet

Hei vi skulle gjerne hatt et slack ikon uten tekst. link: https://salesforce.widencollective.com/c/qqyq7eec

**Comment by KenAJoh** [comment]
Hei, vi er litt usikker på om dette er noe vi har lovt til å gjøre ref slack brand guidelines https://brand.slackhq.com/logo, så vi tenker vi unngår å legge den inn for nå 🙁
