### ISSUE TITLE
[Innspill til komponent]: <Tag />

### ISSUE THREAD

**Issue by solumstrand** [navikt/Designsystemet#2371]
### Tilbakemelding

Har ett ønske om at det var mulig å legge til ikon på taggen :)

**Comment by sjur-gr** [comment]
Jeg skal utforske denne nå @solumstrand. Har du noen eksempler på konteksten dere ser for dere tags med ikoner?

**Comment by solumstrand** [comment]
Jeg jobber med saksbehandling for tiden og tags er tenkt brukt i header og oppgavebenk, for å raskt skille sakstype fra sakstype så kunne det vært fint med mulighet til ikoner i tagsene: 
![image](https://github.com/navikt/aksel/assets/144889236/60f4c66e-1a97-480a-9db1-01ee2daa435a)

**Comment by solumstrand** [comment]
![image](https://github.com/navikt/aksel/assets/144889236/91035df8-389f-4140-9642-31d90cb6ac6c)


Litt raske skisser her for å forklare :)

**Comment by sjur-gr** [comment]
@solumstrand Takker! Det slo meg at det kanskje er mer logisk at et ikon som beskriver typen / status ligger på venstre side. Har du/dere sett noe på det?

**Comment by solumstrand** [comment]
Ser de er til høye i GitHub 
![image](https://github.com/navikt/aksel/assets/144889236/cc90916f-c2d8-4540-bc81-660ca7460271)
Men ingen sterk mening her, hvis taggene listes opp under hverandre ser det absolutt mer ryddig ut med ikoner til venstre. Jeg liker at vi kan velge på knappene våre, hvilken side ikoner skal være på.

**Comment by sjur-gr** [comment]
Det er fordi det er emoji i Github og en del av label som er skrevet. Siden det er tekst og ikke dekor så kan det tulle til alfabetisk sortering, om man trenger det. Noe som et ikon ikke vil gjøre.
