### ISSUE TITLE
[Innspill til komponent]: <Select />

### ISSUE THREAD

**Issue by Jesperpaulsen** [navikt/Designsystemet#2382]
### Tilbakemelding

Mulighet til å endre fargen på chevron. Per dags dato er det mulig å endre bakgrunnsfargen til select komponenten med tokens, men chevronen er det ikke mulig å endre farge på uten å bruke css selectorer. Ettersom jeg bruker tailwind prøvde jeg å sette stroke color på stylingen til Select komponenten, men det gir kun en hvit border rundt chevronen, men endrer ikke bagkrunnsfargen til fyllet. En token man kunne ha satt for fargen til hele chevronen hadde vært helt prima.
<img width="263" alt="Skjermbilde 2023-10-17 kl  11 02 44" src="https://github.com/navikt/aksel/assets/37295027/e9d43104-09bb-49ac-908e-ee506552e83b">

**Comment by KenAJoh** [comment]
I nyeste versjon bruker nå Select-chevron samme token/color som tekstfarge:
Default: --a-text-default
Override: --ac-select-text

**Comment by Jesperpaulsen** [comment]
Nydelig, takk skal du ha!
