### ISSUE TITLE
[Innspill til komponent]: <Pagination />

### ISSUE THREAD

**Issue by jmnorheim** [navikt/Designsystemet#2389]
### Tilbakemelding

Hei, synes komponenten stort sett ser veldig bra ut, men noe jeg tror kunne vært en logisk feature er at man "skroller" i sidetall-menyen om man trykker på de tre prikkene som dukker opp. Eksempel:
Menyen ser slik ut:
![image](https://github.com/navikt/aksel/assets/75325125/11fcce31-52b8-496b-8150-6e7e0a36df28)
Om jeg klikker på de tre prikkene til høyre synes jeg menyen burde bli til dette:
![image](https://github.com/navikt/aksel/assets/75325125/71510c27-5a34-4700-843f-28b72b3d1886)

Fant akkurat ut om Aksel, imponert over innholdet, keep it up!

**Comment by KenAJoh** [comment]
Takk for innspill! Vi legger det på listen over potensielle forbedringer vi kan gjøre på komponenten i fremtiden. 🚀
