### ISSUE TITLE
[NEW] DatePicker/MonthPicker motsatt rekkefølge på årstall-dropdown

### ISSUE THREAD

**Issue by ivoiv** [navikt/Designsystemet#2397]
## Hva?

Vi har fått et endringsønske av noen saksbehandlere.

Årstallene i dropdownCaption kommer per i dag i stigende rekkefølge dvs
2001
2002
2003

De ønsker gjerne at de kommer i synkende rekkefølge, dvs.
2003
2002
2001

Kunne vi hatt en prop som lar oss inverte rekkefølgen på årstallene i dropdownCaption ?
## Hva løser dette?

De mener det er mer naturlig for blikket og ser bedre ut.
Jeg tror også det har hovedsakelig med vanesak å gjøre, ettersom vår gamle dato-løsning har hatt synkende rekkefølge i mange år og de er nok ganske vant til det.

## Eksempler/Info

Ønsket løsning
![image](https://github.com/navikt/aksel/assets/11502345/62088107-d3ce-4609-87ae-e963ff23924d)

Dagens løsning
![image](https://github.com/navikt/aksel/assets/11502345/e411453c-a3d3-4bc0-8924-c3286bb5b92f)

**Comment by KenAJoh** [comment]
Har gjort litt utforskning på denne nå:
- Ser ut som native funksjonalitet for `<input type="date">` på mac/windows og chrome, firefox etc alltid starter med minste året på toppen
- Dette er også slik f.eks material (google) anbefaler at det skal være https://m3.material.io/components/date-pickers/specs
- Månedsvelger starter alltid med Januar øverst
![Screenshot 2023-10-26 at 12 54 30](https://github.com/navikt/aksel/assets/26967723/87979750-7283-40a5-bdb9-34a78ce58a68), så kan være uheldig at rekkefølgen er forskjellig for måned/år


Når vi etterhvert oppdaterer årsvalg (ref #1856) vil også årsvalg gjøres lignende material:
![Screenshot 2023-10-26 at 12 53 16](https://github.com/navikt/aksel/assets/26967723/c94cd7c6-517b-4ed2-a4a7-8b20a2b16bf8)
![Screenshot 2023-10-26 at 12 53 11](https://github.com/navikt/aksel/assets/26967723/e6161e17-cf81-42cd-93a3-3304070b11f2)

Ser at det kan virke uvanlig for saksbehandlere som har hatt motsatt interaksjon tidligere. Men for å minske forskjell i UX på tvers av fagsystemer eller systemer generelt ønsker vi å ikke tillate manuell overstyring av dette.

**Comment by ivoiv** [comment]
@KenAJoh 

Saksbehandlerne i kontrollsaker pleier i de fleste tilfellene å sjekke de nyeste årstallene, dvs 2023 2022, kanskje 2021.
Jo eldre datoen er jo mindre sannsynlig at den sjekkes, f.eks. så å si ingen sjekker 2015.

Derfor er det synd at de nyeste årstallene havner nederst og 2015 havner først.
Dette betyr at de må helt ned i lista hver gang de skal bytte årstall for samme måned, og det gjør de ofte for å se på utvikling mellom perioder.

Jeg er enig at på generell basis er det greit med stigende rekkefølge særlig i bruker-eksponerte flater, men det finnes flere tilfeller hvor det motsatte kan være ønskelig - nemlig når det gjelder datoer som kan i teorien gå langt tilbake i tid, men i praksis brukes de nyere. 

Feks. når du skal velge når barnet ditt ble født - ja, det i teorien være 1950, men du vil mest sannsynligvis velge blant de siste 18 årene først. I det tilfellet vil hele den første delen av scrollen fra 1950 til 2004, som tar opp mesteparten av skjermen i høyden, være veldig lite nyttig.

Ber gjerne om en re-vurdering av saken.
En ekstra prop vil være lite inngripende og stigende rekkefølge vil fremdeles være standard.

**Comment by KenAJoh** [comment]
Etter å ha testet datepicker litt mer på windows/mac er vi enig i at opplevelsen på spesielt windows nå er ganske elendig. Macos håndterer dette bedre da mus ikke trengs å flyttes, men windows krever lengre flytt hver gang.

Vi har tenkt å gjøre e refactor av hvordan mnd/år blir håndtert i Datepicker og vil derfor ikke tilby en egen prop frem til da som løser dette da dette vil skape enda mer forvirring ved bruk på tvers av fagsystemer. Men målet med oppdateringen er absolutt å sikre at denne interaksjonen fungerer like bra for windows og mac-brukere 🚀 

Duplicate #1856

**Comment by ivoiv** [comment]
@KenAJoh 

Hei! Vil gjerne gjenopplive den tråden.
Vi lanserte nylig en ny frontend løsning for Arbeid-og-Inntekt med Aksel i bruk, og en av de første tilbakemeldingene vi fikk er at nyeste årstall havner nederst og det skaper problemer for arbeidsflyten saksbehandlerne har. 

Derfor ber jeg igjen om en prop som kan snu om rekkefølge på årstallene, i hvert fall som en midlertidig løsning inntil dere ordner det nye du nevner. 🙂 

![image](https://github.com/navikt/aksel/assets/11502345/d8608801-4469-490a-bf1e-d77b2d990e6b)
