### ISSUE TITLE
[Innspill til komponent]: MonthPicker - valgt måned bør kunne følge årstall

### ISSUE THREAD

**Issue by ivoiv** [navikt/Designsystemet#2398]
### Tilbakemelding

Hvis du velger 1. januar 2021, men så velger 2023 fra dropdownCaption, blir ikke dato satt til Januar 2023 hvis du ikke klikker på januar-måneden på nytt. 

Det hadde vært nyttig dersom samme dag/måned forblir valgt når man bytter årstallet.

Saksbehandlerne som bruker løsning har ser iblant på samme måned, men under forskjellige årstall. 
Vi erfarer at enkelte ikke skjønner at de må trykke på datoen igjen for å bekrefte årstallet.

I vår gamle løsning har vi ett input for måned og ett input for årstall, som løser vel problemet, men vi håpet på at funksjonaliteten av MonthPicker kunne gjøre at vi fikk alt i ett felt. 

Det virker som at det allerede er tilrettelagt for den funksjonen ved å kalle `setSelected` ved `onYearChange`, altså `onYearChange={dato => setSelected(dato)}` i `<MonthPicker />` så det mangler kanskje bare en prop for å aktivere det?

https://codesandbox.io/s/goofy-poincare-3l7w8r?file=/App.tsx

**Comment by KenAJoh** [comment]
Hei, usikker på om dette er en case vi ønsker å bygge inn funksjonaliteten native i MonthPicker, men klarte å løse det slik: 
https://codesandbox.io/s/dazzling-water-n4w5h7?file=/App.tsx:105-863

Siden `monthpickerProps` fra `useMonthpicker` bruker `onYearChange` må man kjøre den manuelt
```tsx
monthpickerProps.onYearChange?.(yearDate);
if (selectedMonth && yearDate) {
  setSelected(setYear(selectedMonth, yearDate.getFullYear()));
}
```


Full kode:
```tsx
const Example = () => {
  const {
    monthpickerProps,
    inputProps,
    selectedMonth,
    setSelected
  } = useMonthpicker({
    fromDate: new Date("Aug 23 2019"),
    toDate: new Date("Aug 23 2025"),
    onMonthChange: console.log
  });

  const customYearChange = (yearDate?: Date) => {
    monthpickerProps.onYearChange?.(yearDate);
    if (selectedMonth && yearDate) {
      setSelected(setYear(selectedMonth, yearDate.getFullYear()));
    }
  };

  return (
    <div className="min-h-96">
      <MonthPicker {...monthpickerProps} onYearChange={customYearChange}>
        <MonthPicker.Input {...inputProps} label="Velg månede" />
      </MonthPicker>
      {selectedMonth && <div className="pt-4">{selectedMonth.getMonth()}</div>}
    </div>
  );
};
```

**Comment by ivoiv** [comment]
Kan ikke dere ha en høringsrunde på det?

Dette er en standard funksjon som finnes i de mange kalendere jeg husker å ha brukt på nettet.
Sjekk f.eks. MUI sin egen kalender, valgt dag settes automatisk når man bytter årstall/måned.
[https://mui.com/x/react-date-pickers/date-calendar/](https://mui.com/x/react-date-pickers/date-calendar/
)

Askel sin kalender er den første hvor jeg opplever at det ikke er standard.
Tipper det er også derfor saksbehandlerne er litt forvirret.

**Comment by KenAJoh** [comment]
Vi har brukt litt mer tid på å utforske dette konseptet og teste det nå. Har da endt opp med dette ikke er noe vi ønsker å bygge inn i selve DatePicker/Monthpicker siden vi ønsker at interaksjonen for valg og visning skal være lik uansett situasjon ved bruk av disse komponentene.

Men vi ser at funksjonaliteten absolutt er noe som gir mening i noen tilfeller der man ønsker raske "shortcuts" for å vise x-år eller lignende. Vi testet da å heller trekke denne funksjonaliteten ut i egne knapper eller lignende (vi har ikke sett på layout her, men bare funksjonalitet)
https://codesandbox.io/p/sandbox/hardcore-glade-qdzqcm?file=%2FApp.tsx%3A27%2C26
https://codesandbox.io/p/sandbox/fancy-mountain-6fq4kf?file=%2FApp.tsx%3A52%2C18

Håper eksemplene kanskje åpner opp for å løse akkurat denne casen, om ikke kan vi sikkert se på andre løsninger sammen 🙏
