### ISSUE TITLE
[Dokumentasjon] <Link> og <LinkPanel> NextJS eksempler

### ISSUE THREAD

**Issue by ivoiv** [navikt/Designsystemet#2399]
## Hva?

Hadde vært fint å vise et eksempel på hvordan bruke disse med/som NextJS lenker akkurat som på `<Button>`
Jeg vet det er egentlig enkelt men jeg har jobbet med NextJS i to år og likevel merker at jeg fremdeles går sånn "Uhhhh...." hver gang jeg skal kombinere Aksel lenker med NextJS 😛

**Comment by KenAJoh** [comment]
Har publisert eksempler for Link og LinkPanel 🚀
