### ISSUE TITLE
[BUG] <Table> expandOnRowClick fungerer ikke når <Table.DataCell> inneholder et HTML element

### ISSUE THREAD

**Issue by ivoiv** [navikt/Designsystemet#2402]
## Hva er feilen/problemet?

Når tabell-kolonnen inneholder et HTML element går det ikke an å klikke på kolonnen for å utvide raden.
```
<Table.DataCell>Hei</Table.DataCell>  // fungerer
``` 
```
<Table.DataCell> 
     <div>Hei</div>                   // går ikke an å klikke på.
</Table.DataCell>  
```

Man kan kun klikke på den syltynne paddingen rundt elementet, da går det.

## Eksempel/Tilleggsinformasjon (valgfri)
https://codesandbox.io/s/exciting-shannon-8v84yz?file=/App.js

**Comment by KenAJoh** [comment]
Hei, for å sikre at interaktive elementer ikke åpner raden har vi en enkel sjekk 
```
e.target.nodeName === "TD" || e.target.nodeName === "TH"
```
som gjør at bare direkte children `<Table.DataCell>Hei</Table.DataCell>` fungerer riktig.

Kan hende det er noen caser vi ikke har sett for oss enda her, så ønsker gjerne å se noen eksempler hvis det ikke svarte på problemet 🙌

**Comment by ivoiv** [comment]
Iblant trenger man en div eller span til styling eller formattering.
Akkurat i vårt tilfelle har vi 2 datalinjer i samme rad (ikke den beste UU-messig men sånn er det bare) med detaljer for de når man utvider raden, og det blir enklest å ha de i div-er. 

Kan ikke det styres via en prop?
F.eks. `<Table.DataCell interactive={ true | false }>` som er satt til `false` som default og heller setter den til true når du setter inn en knapp eller noe?

Dagens løsning kan uansett hackes ved å skrive følgende i steden for å bruke `div` og da fungerer det, men har ikke lyst til å ty til det.
```
<Table.DataCell> 
     <td style={{display:'block'}}>HÅRREISENDE FRISØR</td>
     <td style={{display:'block'}}>SJOKKERENDE ELEKTRIKER</td>
</Table.DataCell>  
```


![image](https://github.com/navikt/aksel/assets/11502345/67d8f038-10d1-4c4c-a7ac-144b91bb31a2)

**Comment by KenAJoh** [comment]
Vi testet litt mer og virker som `br` fungerer i denne casen.
```
<Table.DataCell> 
    {fnr}
    <br/>
    {fnr}
</Table.DataCell>  
```

Hvis ikke dette løser problemet skal det være relativt enkelt å legge på egen logikk for å sikre at klikk på div åpner Table-row
```
<Table.DataCell> 
     <div onClick={handleOpenState}>Hei</div>
</Table.DataCell>  
```

**Comment by ivoiv** [comment]
Ifølge retningslinjer for UU skal `<br/>` ikke brukes til visuell formattering.
[https://www.w3.org/TR/2011/WD-html5-author-20110809/the-br-element.html](https://www.w3.org/TR/2011/WD-html5-author-20110809/the-br-element.html)

Det hadde uansett ikke fungert(enkelt) når du skal mappe over entries for da får du en trailing `<br/>` på slutten.
Ang. `handleOpenState`, det lar seg heller ikke gjøre (enkelt) fordi innholdet sendes som en prop via et annet komponent.

Synes det er greit at Aksel er noe opinionated men den bør ikke frata muligheten for konfigurering når det enkelt lar seg gjøre.
`e.target.nodeName === "TD" || e.target.nodeName === "TH"` - man kan vel angi ekstra gyldige nodes vi en prop?
Eller som nevnt i min forrige post `<Table.DataCell interactive={ true | false }>`
