### ISSUE TITLE
[Innspill til komponent]: <Switch /> farger, tokens, ikon, størrelse og div.

### ISSUE THREAD

**Issue by ivoiv** [navikt/Designsystemet#2415]
### Tilbakemelding

1. Hvis jeg skal ha et mer NAV-aktig blå tema på `Switch` må jeg ha 3 forskjellige design tokens som gir en del støy.

Hadde vært artig med med bare ett token for farge og at Switch setter de andre fargene basert på denne. Dvs. sette `checked-bg` og `icon-checked` til det jeg har valgt og automatisk sette en litt formørket versjon av fargen på `hover-bg`.

Jeg synes det er veldig fint med separate tokens for hver property, men samtidig føler jeg de fleste implementasjonene kommer til å følge en veldig lik pattern.
```
'--ac-switch-checked-bg': 'var(--a-blue-700)',
'--ac-switch-thumb-icon-checked': 'var(--a-blue-700)',
'--ac-switch-checked-hover-bg': 'var(--a-blue-800)',
```

2. Kanskje det over kan løses med en `color` prop som på Alert? Noe a-la `"error" | "warning" | "info" | "success"`. Disse er vel de mest vanlige fargene vi bruker på tvers av NAV skal jeg anta?

3. Hadde vært artig å kunne bytte ikon. Vi bruker `Switch` til å låse en periode, så for oss hadde det vært mer logisk med et ikon av en lås.
(Det kan hende at Aksel-ikonene er for tykke til den størrelsen, men man kan vel bruke `stroke-width` på SVGen for å tynne de ut?)

4. Dette er egentlig bare en FYI, men høyden på en `small` `Input / Select` er 60px mens høyden på en `small` `Switch` er 32px pga. paddinger. Skal man stacke 2 Switcher i høyden blir de et hakk større enn andre Input elementer og ødelegger layouten litt.

5. `Tooltip` fungerer ikke helt 100% med `Switch`. Den trigges når man hovrer over selve `Switchen` men ikke label til den.

**Comment by KenAJoh** [comment]
Vi bestemte oss for å fjerne bruk av success-farger og bare bruker default action som standard på switch. Er oppdatert i v5.11.1 🚀 

Ref custom-ikon er nå ikonet brukt tilpasset Switch, og Aksel-icons vil ikke fungere så bra rett ut av boksen. På grunn av dette ønsker vi ikke å åpne for egne ikoner i denne omgang.

Siden rest-props er lagt på `<input>` vil tooltip være attachet til den. Dette gjelder forsåvidt alle skjemaelementene våre slik at vi ikke kan løse det på kort sikt.
