### ISSUE TITLE
[Innspill til komponent]: <Tooltip />

### ISSUE THREAD

**Issue by Mokkatroffen** [navikt/Designsystemet#2416]
### Tilbakemelding

Følgende står på siden: 
_Mobil
Tooltip aktiveres av fokusmarkering eller hover og vil ikke være noe som dukker opp på mobil._

Blir kanskje litt misvisende da man kan bruke både mus og tastatur på mobile enheter ☎️ ⌨️ 🖱️ ?

**Comment by KenAJoh** [comment]
Takk for heads-up! Har oppdatert teksten da 👍
