### ISSUE TITLE
[BUG] <DropDown.Menu> sin style overskrives av bruker

### ISSUE THREAD

**Issue by ivoiv** [navikt/Designsystemet#2437]
## Hva er feilen/problemet?

`DropDown.Menu` sin posisjon er angitt via `style`-proppen i Aksel.

Når man sender en egen `style` prop til `DropDown.Menu` for å justere/pynte på ting,  overskrives `DropDown.Menu` sin `style` og den havner på feil sted.

De to burde heller slås sammen.

## Eksempel/Tilleggsinformasjon (valgfri)
Uten style
![image](https://github.com/navikt/aksel/assets/11502345/eb500689-6d23-411f-9baa-ba59d5695761)

Med style `width:auto`
![image](https://github.com/navikt/aksel/assets/11502345/fdd1f3fe-876b-4026-ae8d-c6d86cf5b402)

**Comment by KenAJoh** [comment]
Hei, vi har valgt å ikke eksponere styles da `Popover` som `Dropdown.Menu` bruker ikke håndterer endringer av style så bra. Popover blir automatisk plassert basert på størrelse, og har problemer i noen tilfeller med flikker/layoutshifts ved endring av inline styles.
