### ISSUE TITLE
[BUG] sr-only gir Modal scrollbar

### ISSUE THREAD

**Issue by HalvorHaugan** [navikt/Designsystemet#2441]
Hvordan gjenskape:
1. Gå til https://navikt.github.io/aktivitetsplan/
2. Åpne et kort
3. Gjør viewport mindre i høyden. Du får nå dobbel scrollbar. Skyldes sr-only på legend.

**Comment by KenAJoh** [comment]
Virker som å sette `top: 0;` løser det på sr-only klassen. Men top er kanskje ikke anbefalt 🤔 https://stackoverflow.com/questions/66572172/sr-only-class-causing-page-scroll

**Comment by HalvorHaugan** [comment]
Da havner elementet øverst i modalen i stedet:
![image](https://github.com/navikt/aksel/assets/83693529/659cc147-6186-4aa1-97b4-8d38ab5e10ba)
Tror det kan være et problem for skjermlesere som leser i "visuell" rekkefølge i stedet for DOM-rekkefølge (?)
