### ISSUE TITLE
[Nytt ikon]: 

### ISSUE THREAD

**Issue by Trent-NAV** [navikt/Designsystemet#2463]
### Navn på ikonet

Pin 

I familie med [pin Travel](https://aksel.nav.no/ikoner/Pin) men funksjonelt annerledes. Feks når man fester/pinner en sak i et saksbehandlingssystem.

![pin](https://github.com/navikt/aksel/assets/86958516/0fa0eec3-0749-4aad-8fbf-148799352e21)
![pin_stroke](https://github.com/navikt/aksel/assets/86958516/dc9dfe1a-1750-4330-81c8-50d99e220921)

**Comment by JorgenMaristuen** [comment]
Nytt ikon: [DrawingPin ](https://www.figma.com/file/wEdyFjCQSBR3U7FvrMbPXa/Aksel-Icons?type=design&node-id=2663-1154&mode=design&t=wcFKB9kQdMZafABG-4)
