### ISSUE TITLE
[BUG] Button - feil med types, kan ikke lage egen implementasjon

### ISSUE THREAD

**Issue by ivoiv** [navikt/Designsystemet#2472]
## Hva er feilen/problemet?

Det er noe rart med typene til Button. 
Klarer ikke lage en egen implementasjon.

Begge varianter under gir forskjellige feil når de skal brukes
```
const MyButton = (props: React.ComponentProps<typeof Button>) => {
  return <Button {...props} />;
};

const MyButtonTwo = (props: ButtonProps) => {
  return <Button {...props} />;
};
```
Den første gir: 
```
Property 'as' is missing in type '{ children: string; }' but required in type '{ as: ElementType<any>; }'.
```

Den andre: 
```
Type '{ children: string; as: string; }' is not assignable to type 'IntrinsicAttributes & ButtonProps'.
  Property 'as' does not exist on type 'IntrinsicAttributes & ButtonProps'.
};
```

## Eksempel/Tilleggsinformasjon (valgfri)
[https://codesandbox.io/s/eager-minsky-nmv52y?file=/App.tsx](https://codesandbox.io/s/eager-minsky-nmv52y?file=/App.tsx
)

**Comment by KenAJoh** [comment]
Ser ut som det kan løses ved å bruke `Partial`
```
Partial<React.ComponentProps<typeof Button>>
```
Kan undersøke å løse det i Button-apiet, men risiko for at `OverridableComponent`-api et brekker 💥
