### ISSUE TITLE
[Innspill til komponent]: <Alert />

### ISSUE THREAD

**Issue by PerOlavM** [navikt/Designsystemet#2501]
### Tilbakemelding

Det kan se ut som title ikke blir satt når man bruker inline.
Dette gir UU-feil.

**Comment by KenAJoh** [comment]
Hei 👋 Gjorde en rask sjekk av kode vår, og ser ut som title blir riktig satt for inline-variant. 

<img width="901" alt="Screenshot 2023-11-20 at 14 11 18" src="https://github.com/navikt/aksel/assets/26967723/4c8c8476-fe2f-407d-ada9-7acb84deed43">

**Comment by PerOlavM** [comment]
Det var rask respons :-)  Takk!
Hmm, da må jeg prøve å finne ut hvorfor dette ikke skjer i vår bruk av komponenten.
