### ISSUE TITLE
[BUG] Resizable <Textarea> har ingen scrollbar

### ISSUE THREAD

**Issue by ivoiv** [navikt/Designsystemet#2506]
## Hva er feilen/problemet?

Når du har mer tekst enn størrelsen på Textarea med `resize={true}` dukker ikke scrollbar opp.
Det er ikke mulig å se resten av innholdet uten å forstørre Textarea.
Det går heller ikke an å bruke musehjulet. 

`overflow:hidden` i `style` er skylderen.
Det fungerer fint uten den.

## Eksempel/Tilleggsinformasjon (valgfri)

Dagens løsning med `overflow:hidden`
![image](https://github.com/navikt/aksel/assets/11502345/ee872033-4816-46dd-8723-93b1df936531)

Ønsket løsning
![image](https://github.com/navikt/aksel/assets/11502345/07ba12f2-33b9-4c19-aec8-758f30b3f64a)
![image](https://github.com/navikt/aksel/assets/11502345/631813be-f798-4fe7-b986-9a6d1e2c937a)

**Comment by HalvorHaugan** [comment]
Hei! Skjer det etter at du manuelt har endret størrelsen på tekstfeltet ved å dra i hjørnet?

**Comment by ivoiv** [comment]
Ja, på en måte. TextArea prøver jo automatisk å tilpasse seg innholdet, men jeg krymper den ned ved å dra i hjørnet.

Jeg ser "buggen" skjer hvis man ikke har angitt `maxRows`.
Med `maxRows` får man scrollbar i alle tilfeller det er mer text enn plass, selv om man drar i hjørnet.

Det blir en issue når du ikke er sikker på hvor mange `maxRows` du egentlig trenger, eller om du ikke trenger det i det hele tatt.

**Comment by HalvorHaugan** [comment]
Fikset i v5.11.3
