### ISSUE TITLE
[Ny komponent]: TextArea med støtte for RichText/Markup/Markdown

### ISSUE THREAD

**Issue by ivoiv** [navikt/Designsystemet#2508]
### Navn på komponent

RichTextArea

### Eksempel på komponenten

Hadde vært nyttig med noe a-la GitHub sitt tekstfelt eller [https://richtexteditor.com/](url)
![image](https://github.com/navikt/aksel/assets/11502345/8bb43a50-41b2-4f4f-a8fe-ae1ea88d95ea)

I flere interne flater for saksbehandling har vi behov for enkel tekst-formattering, type linjeskift, fet tekst, en liste, osv. til notater og tekst som skal lagres i dokumenter eller PDFer. 
Jeg synes det kan også være nyttig i tilfeller hvor brukerne trenger å skrive en del.

**Comment by KenAJoh** [comment]
Hei 👋 Dette er en komponent vi har sett litt på tidligere og ikke blir å implementere i Aksel på grunn av kompleksiteten.
Vet det er noen team rundt i NAV som har implementert dette gjennom ulike npm-pakker. Diskusjon her: https://nav-it.slack.com/archives/C7NE7A8UF/p1668596451499759
