### ISSUE TITLE
[Innspill til komponent]: <ExpansionCard />

### ISSUE THREAD

**Issue by frodehansen2** [navikt/Designsystemet#2516]
### Tilbakemelding

Er det meningen at innholdet skal være tilgjengelig i DOM når kortet er lukket? Hadde kanskje været greit at det var en prop for om innholdet skal rendres eller ikke når den er lukket.

**Comment by KenAJoh** [comment]
Hei, ja dette er et bevisst valg vi har gjort for at innholdet skal være tilgjengelig for søkemotorer. Dette gjelder for det meste åpne sider, men vi så ingen store downsides med å ha det som standard for alle på Accordion og ExpansionCard.

Er det noen tilfeller i bruken deres der det kunne vært nyttig å kunne fjerne elementene fra DOM? @frodehansen2

**Comment by KenAJoh** [comment]
Lukker denne for nå, hvis dette fortsatt er et problem kan vi gjerne gjenåpne issuet å se videre på det 🙌
