### ISSUE TITLE
Color tokens / Action

### ISSUE THREAD

**Issue by Trent-NAV** [navikt/Designsystemet#2524]
Mulig dette fortsatt er work in progress men siden komponentene er dokumentert og color tokens etablert så lurer jeg på hvorfor Aksel bruker to litt ulike blåtoner og ulike semantiske gruppenavn til det som generelt kan oppfattes som samme rollefarge? Surface/Action.Selected #00459c og Surface/Action #0067c5. Se vedlagte eksempler.

Hvis man ser på input komponentene som har selected state (checked) så har de andre fargestiler enn Surface/Action.Selected som Switch, Removable Toggle, Toggle Chip, Toggle og Stepper har nå. Av sistnevnte er det vel kun Switch som faktisk har en selected state (checked), de andre som Chip, Toggle og Stepper er blå default i respektive **Action** og **Interactive** varianter. Selected state av Radio-button, Checkbox samt interaktive komponenter som HelpText er tildelt Surface/**Action** og Border/**Action** i samme stilsett i Core UI kit. Stepper komponentet har en miks av alt. 

Hvorfor har man splittet en semantisk farge i to på denne måten og gitt de ulike valører?

For 7 mnd siden delte @Lilyngs et[ Slack innlegg](https://nav-it.slack.com/archives/C7NE7A8UF/p1682071331133289) på fargetema der  interaksjonsfarge er nevnt. Er det noe nytt i den sammenheng som påvirker det jeg omtaler her?

![Action colors](https://github.com/navikt/aksel/assets/86958516/cf2a0218-8ee4-46ab-ba92-ae10bc73e7a4)

**Comment by sjur-gr** [comment]
Det er 2 forskjellige ting ja. Mulig vi kan se på om vi bruker riktig farge på skjemaelementer og tabs som er valgt.

**Comment by Trent-NAV** [comment]
Burde vi ikke bare benytte en felles generisk action eller interactive farge? Surface/Interactive, Text/Interactive, Icon/Interactive osv? Så kan states som active, visited etc justeres på komponentnivå? Syns å huske at vi kun opererte med interactive begrep på alt dette før og at alle semantiske tokens som Surface, Text, Icon, Border etc hadde en felles interactive blue. 

På Aksel står det om design tokens at det "_forenkler vedlikeholdet av designet og sikrer en helhetlig visuell fremstilling på tvers av produkter_". Når man har to ulike valører av blå og samtidig bruker de ulikt på samme type komponentutrykk (selected) så sikrer ikke det helhetlig fremstilling. Jeg syns en påskrudd eller selected/checked switch burde ha samme blå som en selected radio-button eller checkbox, eller en selected tab.  Deler bare noen tanker her, jeg har ikke deltatt på iterasjonen så kan være det er strategiske ting jeg ikke inkluderer i vurderingen.

PS: Syns det var riktig å fjerne success token (Icon/Success og Surface/Success) fra switch da det er med på å forsterke semantikken i success der den faktisk har en tydelig rollebetydning, som feks på alert og for fremtidige komponenter som toast, success button o.l 👍

**Comment by sjur-gr** [comment]
Figma og kode er oppdatert med riktig action-farge

**Comment by Trent-NAV** [comment]
@sjur-gr Eneste jeg ikke har fått update på i Figma er Primary CTA button som fortsatt har Surface/Action. Sjekket med manuelt søk i Core Ui kit.

**Comment by sjur-gr** [comment]
Surface.Action er uendret. Om vi endrer det gjør vi det med ny versjon av tokens. Som er en større jobb.
