### ISSUE TITLE
[Nytt ikon]: Slack

### ISSUE THREAD

**Issue by gunnjohansen2** [navikt/Designsystemet#2540]
### Navn på ikonet

Slack

### Eksempel på ikonet

Siden Slack er så integrert i organisasjonen, tenker jeg det burde være et ikon i Aksel?

Eksempler:

Her er et slack-ikon brukt: 
https://navno.sharepoint.com/sites/intranett-kunnskap/SitePages/Tableau.aspx (Høyremarg > Kanaler > Tableau)
https://teamkatalog.nav.no/team/29d44f3f-ff09-477c-b26a-83cd0aa66116

Her kunne det vært brukt: 
https://navno.sharepoint.com/sites/fag-og-ytelser-fagsystemer/SitePages/Aa-registret.aspx

![Skjermbilde 2023-12-04 kl  15 00 28](https://github.com/navikt/aksel/assets/89259469/9dd4fd2e-07d4-4fae-a4cf-699fc8407535)
![Skjermbilde 2023-12-04 kl  15 00 05](https://github.com/navikt/aksel/assets/89259469/11bbb6c7-28c3-43a9-83af-468878eed3ab)
![Skjermbilde 2023-12-04 kl  14 59 49](https://github.com/navikt/aksel/assets/89259469/2c4c5300-c735-497d-899b-7e0988a4dc04)

**Comment by KenAJoh** [comment]
Duplikate #2369 

Hei 👋 Vi tror ikke dette er noe vi har lovt til å gjøre: [slack brand guidelines](https://brand.slackhq.com/logo) siden vi eksponerer ikonene våre eksternt, og blir gjenbrukt i systemer utenfor NAV. Vi ønsker derfor å ikke trekke inn logoer til eksterne løsninger uten eksplisitt tillatelse.
