### ISSUE TITLE
[Innspill til komponent]: <Textarea />

### ISSUE THREAD

**Issue by PerOlavM** [navikt/Designsystemet#2550]
### Tilbakemelding

--ac-textarea-counter-text er ikke WCAG 2.1 AA compliant. Gir bare kontrast på 4,09:1

**Comment by it-vegard** [comment]
Hvilken bakgrunnsfarge er brukt da? Ut i fra hva jeg kan se er den satt til subtle-fargen som har opacity, som gjør evalueringen litt mer komplisert. 

Men ut i fra sjekkene jeg gjør med hvit bakgrunnsfarge, så skal kontrasten være 7.07:1:
https://www.siegemedia.com/contrast-ratio#rgba%281%2C%2011%2C%2024%2C%200.68%29-on-white (uten at jeg har erfaring med denne fra før av).

Bruker jeg en color picker, så evaluerer den fargen til å være #535963, som gir kontrast på 7.05:1 på https://webaim.org/resources/contrastchecker/.

**Comment by PerOlavM** [comment]
Hvit. Det er et godt poeng. Det ville jo vært rart hvis subtle ikke skulle være compliant. :-) 
Det er Siteimprove som rapporterer, sjekket ikke selv hva kontrasten faktisk er. My bad.
