### ISSUE TITLE
[Innspill til komponent]: <Combobox /> typing av options

### ISSUE THREAD

**Issue by idaame** [navikt/Designsystemet#2553]
### Tilbakemelding

Hei! Jeg savner en variant av Combobox hvor det er mulig å sette options til noe mer enn bare en string. For eksempel at options er et objekt med value og label, hvor label er det som vises, men value er verdien man får tilbake i onChange/onToggleSelected. Dette gjør det mye lettere å bruke komponenten, da vi har mange steder i koden hvor vi ønsker annen visningstekst enn verdien vi ønsker å jobbe med i koden. 

Eksempel på komponent jeg gjerne ønsker å bytte ut med combobox, men som i dag blir utrolig kronglete: vi bruker i dag en ReactSelect (multiselect variant) hvor saksbehandler skal kunne velge begrunnelser som skal dukke opp i vedtaksbrevet. Disse begrunnelsene representeres som enum, men vi ønsker jo ikke at det er enum-verdien som skal vises frontend, men heller en visningstekst. Her hadde det vært veldig fint å kunne skille på value og label på hvert option, så vi slipper konvertere enum til streng og streng til enum igjen for å kunne bruke Combobox.

Et annet eksempel hvor vi ønsker å gå over til Combobox er i dag en ReactSelect hvor saksbehandler skal velge hvilke barn en gitt vurdering gjelder for. Her ønsker vi å formatere identen med mellomrom for saksbehandler, men når vi jobber på identen i backend ønsker vi ikke at den skal være formatert. Går selvfølgelig å jobbe rundt det, men det mest ryddige hadde vært om vi kunne fått på plass en løsning som skiller på value og label på hvert option.

Er dette noe dere har diskutert?

**Comment by it-vegard** [comment]
Hei Ida,

Kommer bare med de første tankene mine her nå før helgen, og så skal jeg/vi svare mer utfyllende til uken.

Vi har i hvert fall diskutert en ganske lik problemstilling, blant annet rundt muligheten for å legge til ikoner og annet i formatteringen for hvert punkt (for eksempel for landvelger/valutavelger). Da har det gått på å endre typen til å støtte objekter med forskjellige properties, som value, displayText/label, icon, etc. Jeg vil anta at behovet deres vil dekkes av dette også.

Problemet er at det trolig gjør den interne logikken ganske mye mer komplisert, så vi har skjøvet på det lengst mulig for å se om det er et reelt behov, og ikke bare en idé vi hadde fått. Det med ikoner har vi også funnet en annen løsning på, uten at vi er i mål med det enda. Det er dermed fremdeles mulig å gå for denne løsningen også i det tilfellet.

Som nevnt må jeg komme tilbake til deg med et bedre svar til uken, når vi har fått diskutert det i teamet, men det korte svaret er at "ja, vi har tenkt på det, men det kan være det kompliserer den interne koden en del, så vi må tenke oss litt om før vi eventuelt gjør det".

**Comment by it-vegard** [comment]
Etter en runde internt i teamet ser det ut til at vi vil gå for å implementere støtte for å sende inn objekter, slik du har skissert. Jeg har ikke en ETA enda, men vi kommer med en oppdatering her når vi går i gang med oppgaven.

**Comment by idaame** [comment]
Åh nydelig! Takk for veldig rask respons 🤩 bare å huke tak i meg om dere trenger å sparre om noe

**Comment by sndrem** [comment]
Vi i Team Valp har tilsvarende behov. Vi ønsker å sende inn et objekt ala

```ts
value: {
 arenaKode: tiltakstype.arenaKode,
 navn: tiltakstype.navn,
 id: tiltakstype.id,
},
label: tiltakstype.navn, 
```
der `label` blir det som vises i nedtrekksmenyen, mens value er verdien vi får når bruker velger i komponenten. Vi kan alltids skrive oss rundt det, men om Aksel kan ordne det slik at alle andre team slipper å skrive seg rundt det hadde nok det vært det beste.

Vi bruker react-select i dag som støtter å sende inn objekter (men som gjør at vi må inn med egen styling for å få det til å se likt ut som Aksel sine input-komponenter i skjema vårt). Vi ønsker helst å bruke Aksel-komponenter for å få mer "gratis ut av boksen".

**Comment by it-vegard** [comment]
Value som objekt (eller `any`?) ser fornuftig ut. Kan nok fort være at det er stor variasjon i hva konsumentene ønsker å få returnert.

Som nevnt over vil vi nok ta fatt på denne oppgaven over nyttår.

**Comment by it-vegard** [comment]
En liten tanke som slo meg:

Burde verdiene som ligger i `value` kunne søkes i for filtrering i listen, eller vil det være forvirrende om det vises treff som ikke inneholder søketeksten? 🤔  

Å kunne søke i de gjør jo at det ville være mulig å legge til synonymer, samt la ekspertbrukere søke i koder og lignende.

**Comment by lurajon** [comment]
Bra ide! Det kan kanskje lages støtte for å overstyre filterfunksjonen? Da kan konsumentene selv velge om de vil ha standard eller en egendefinert.  Bakdelen er kanskje at det vil ikke være samme oppførsel på tvers av applikasjoner.

**Comment by it-vegard** [comment]
@sndrem: Hvor viktig er det å få et objekt tilbake som returverdi?
Ville det kunne være tilstrekkelig å sende inn
```
{
value: "en id",
label: tiltakstype.navn,
...
} 
```
og få tilbake `value`, så kan resten slås opp basert på den?

Så vidt jeg kan se vil det dekke de andre behovene her, mens det å returnere et objekt vil lage krøll for `allowNewValues`-propen. (Da må vi for eksempel tilby en prop for å formattere nye verdier, slik at de får samme datastruktur)

**Comment by Watercolours** [comment]
> @sndrem: Hvor viktig er det å få et objekt tilbake som returverdi? 

@it-vegard: Kan ikke svare på vegne av @sndrem, men for vår del holder nøkkelen (`value`) i massevis.

**Comment by sndrem** [comment]
@it-vegard Vi kan nok klare oss med en id som vi selv slår opp med. Er jo enklest for oss med en verdi, men om det skaper veldig mye mer krøll så la oss prøve med id i første omgang.

**Comment by it-vegard** [comment]
Supert! Da satser jeg på å få ut denne i løpet av uken.

**Comment by it-vegard** [comment]
Seint ute med å oppdatere saken, men denne featuren ble sluppet i versjon 6.3.0.
Se [eksempel på bruk på Aksel](https://aksel.nav.no/komponenter/core/combobox#comboboxdemo-with-complex-options).

Vi vil gjerne ha tilbakemelding på om dette fyller de behovene dere har, enten her, gjennom tilbakemeldingsfunksjonen på Aksel eller i #aksel-designsystemet på Slack.
