### ISSUE TITLE
[Innspill til komponent]: <ExpansionCard /> Spacing mellom title, og content uten description

### ISSUE THREAD

**Issue by juliekulie** [navikt/Designsystemet#2554]
### Tilbakemelding

Det ser litt rart ut når man ikke har description på title. Blir litt vel mye luft mellom title og content

**Comment by sjur-gr** [comment]
![pics-or-it-5b96f5](https://github.com/navikt/aksel/assets/82579704/a0d68c59-c63b-4dc8-90bb-0530289d9831)

**Comment by juliekulie** [comment]
![Skjermbilde 2023-12-11 kl  11 59 28](https://github.com/navikt/aksel/assets/47856099/6a203d84-d348-4632-b7ca-8bd3e8f5f9ba)

**Comment by sjur-gr** [comment]
Ja, vi justerte den for ikke veldig lenge siden. Litt tricky fordi det øverste delen er en knapp med states. Vi har ikke veldig lyst til å sette bakgrunnsfarge på den øverste delen når den er åpen heller, fordi det tar fokuset vekk fra det som åpner seg. 
Eksempel med `hover` 👇
<img width="1152" alt="Skjermbilde 2023-12-11 kl  12 24 04" src="https://github.com/navikt/aksel/assets/82579704/1718feee-b121-4a7d-ad9e-d077fdc556f6">

**Comment by sjur-gr** [comment]
En mulighet er å legge inn en divider i default state som viser den usynlige kanten.
<img width="1132" alt="Skjermbilde 2023-12-11 kl  12 25 32" src="https://github.com/navikt/aksel/assets/82579704/81b2dc4f-9302-44cf-93b6-258167c0939d">

**Comment by beeccy** [comment]
Er denne divider en prop i denne komponenten? Hvordan ser det eventuelt ut? (driver og ser i dokumentasjonen, men finner ikke noe tilsvarende)

**Comment by sjur-gr** [comment]
Nei, det er kun en skisse fra min side.
