### ISSUE TITLE
[BUG] Modal: Lukking av modal med trigger ikke onBeforeClose hvis den lukkes med Esc-knapp

### ISSUE THREAD

**Issue by tu55eladd** [navikt/Designsystemet#2555]
## Hva er feilen/problemet?

Lukking av modal med trigger ikke `onBeforeClose` hvis den lukkes med Esc-knapp istedet for close-button eller å trykke utenfor modalen. 

## Steg for å reprodusere problemet (valgfri)

Kan testes her https://navikt.github.io/aktivitetsplan/#/

1. Klikk på en aktivitet (et kort)
2. Trykk Esc
3. Modalen blir lukken men man står fortsatt på en gammel url (#/aktivitet/vis/:id)

For å se forventet oppførsel:
1. Klikk på en aktivitet (et kort)
2. Trykk på krysset i modalen for å lukke den
3.  Modalen blir lukket og det navigeres tilbake til startsiden (#/)

## Eksempel/Tilleggsinformasjon (valgfri)
Versjon: 5.11.3

Mulig relatert konfigurasjon:
- Vi bruker closeOnBackdropClick
- Vi setter modalen alltid til open
```
<Modal
            closeOnBackdropClick
            open
            onBeforeClose={closeFuncOrDefault}
>

**Comment by HalvorHaugan** [comment]
Hei! Dette ser ut til å være [en bug i Chrome 120](https://bugs.chromium.org/p/chromium/issues/detail?id=1510389). Skal se hva vi får gjort med det, men kanskje dere kan bruke `onClose` i stedet?

**Comment by HalvorHaugan** [comment]
Ser ikke ut som det er så mye å gjøre med det, men vi har iallfall oppdatert dokumentasjonen og gått ut med info, slik at folk er klar over det. Takk for at du rapporterte det!
