### ISSUE TITLE
[Innspill til komponent]: Custom css border color på Chips.Toggle icon

### ISSUE THREAD

**Issue by otenav** [navikt/Designsystemet#2556]
### Tilbakemelding

Hei :) På arbeidsplassen.nav.no så klarer vi ikke å overstyre border-color på sirkelen på ikonet i Chips.Toggle. 
Er det mulig å få en custom prop for dette?

![Skjermbilde 2023-12-12 kl  10 27 29](https://github.com/navikt/aksel/assets/29566394/ebc13985-0868-40bd-b7aa-4f22e9c50f37)

**Comment by KenAJoh** [comment]
Hei, har lagt til `--ac-chip-toggle-circle-border` da i nyeste versjon 🙌
