### ISSUE TITLE
[Innspill til komponent]: <Switch />

### ISSUE THREAD

**Issue by JulianNymark** [navikt/Designsystemet#2564]
### Tilbakemelding

Det er 6x VO + pil høyre per switch, kan nok reduseres ned til 1 accessibility node med `[end of?] text + unchecked/checked checkbox, clickable`. Mange av de er i hvert fall redundante, med `, group` på noe som bare er _en_ checkbox, og samme text blir lest opp flere ganger.

[Sandbox](https://aksel.nav.no/sandbox/preview/index.html?code=N4Igxg9gJgpiBcJgB0B2ACdAKLBKdAvAHzooabqSoDOALugKIAeAhgLYAOANjIdvsVJoK6AE4xaAV1EYsAHiJyAygHcAlrTAALdLGphRajrTURUBZCABqa9NRipYo9EoCyS9GxhcuENugAGAA54AID0CABzdABGAHZQgMsiYRF0KxZRah5PGCgXd1TMOQB6VQ1tFPI0kWV1TR09AyMTMwsQAAkANxhnKBZogGs-Lz6JOzVBwd76VAheWxgOCDpBlmp7DCg1VGSiigysnK98hmW6fdLyhqqatLqKxph9Q2NTc0sASXQuAA+OcYsLq6AYOXjUPzoYZsUboABGXDUfUkEQ4HEMqEitD21QOmWyvBO6AAKt4YAAzMzUdi0Fg8fa1Mr1SoPBq6Z7NN5tSwcACnnjUUFQLFo9Bi6AAUiwMJsnOgurYIGj0A4xCxpqLcvlyUCIIZRTrRJFVdtdiBbmlDgStegAHIAT1FvKyonVEmxuMZ1xZJSIuAA3GgAL6B3a48RSGToOTMdjcXi+1JB3B4YMgINAA)

**Comment by KenAJoh** [comment]
For selv bare 3 stop med "checkbox" -> label -> description 🤔 Er det noen innstillinger for VO som påvirker dette?

**Comment by JulianNymark** [comment]
Ikke som jeg vet om 🤔 , så lukker den, virker som det sikkert bare er mitt oppsett da.
