### ISSUE TITLE
[Innspill til komponent]: <MonthPicker />

### ISSUE THREAD

**Issue by BorghildSelle** [navikt/Designsystemet#2598]
### Tilbakemelding

When you do not supply fromDate or toDate, as they are optional, my assumption is that one should be able to navigate as far back or forward one wants to go. The methods hasPrevYear and hasNextYear in MonthCaption returns true when no such dates are supplied, so i assume one should be able to go to next and previous year, but since the result is used set disabled with the response the buttons are thus disabled when hasPrevYear and hasNextYear is true.

Also if one has a controlled component with initial value, (not default value), should not the input show the controlled value? By entering selected into useMonthpicker and set it the same way as defaultSelected (except on reset)?

**Comment by KenAJoh** [comment]
Hi, thank you for the heads up on the `MonthCaption`-bug. Should now be fixed in version `5.12.5` 🤞 

#

> Also if one has a controlled component with initial value, (not default value), should not the input show the controlled value? By entering selected into useMonthpicker and set it the same way as defaultSelected (except on reset)?


Do you have an example or code snippet we could look at to get a better understanding of the interaction @BorghildSelle? 🙌

**Comment by BorghildSelle** [comment]
We used it in a situation where url search params has the period, type `?period=2024-01`, and the monthpicker should be rendered with this period initially set, but it is not default so a reset would just empty period. 
Might not be something you need in your cases.

I have forked the Monthpicker and solved it with adding selected as a prop into useMonthpicker, and initalize it like this:
```
  // Initialize states
  const isControlled = Boolean(selected);
  const [year, setYear] = useState(
    selected ?? defaultSelected ?? defaultYear ?? today,
  );
  const [selectedMonth, setSelectedMonth] = useState(
    selected ?? defaultSelected,
  );
  const [open, setOpen] = useState(false);

  const defaultInputValue = defaultSelected
    ? formatDateForInput(defaultSelected, locale, 'month', inputFormat)
    : '';

  let initialInputValue = defaultInputValue;
  if (isControlled) {
    initialInputValue = formatDateForInput(
      selected,
      locale,
      'month',
      inputFormat,
    );
  }
  const [inputValue, setInputValue] = useState(initialInputValue);
```

**Comment by KenAJoh** [comment]
If i understood the example given correctly, is there an practical difference between just supplying the query `period` as the `defaultSelected` value? The hook will not be truly controllable, but the input will reflect the query. The hook also gives the callback `setSelected` where one could try something like this if one needs to listen for the query change:

```jsx
useEffect(() => {
    selectedMonth !== query && setSelected(query)
}, [query, selectedMonth])
```

Just probing for alternative solutions since to properly add `controlled`-state to `useMonthpicker` (and useDatepicker, useRangeDatepicker) we will have to refactor large parts of the hooks, something we will not be able to prioritize at the short term 🙁

**Comment by BorghildSelle** [comment]
Only that using defaultSelected will set this value everytime you use reset, which is not what we want. 
But as you say the setSelected might be used to get around it, so dont prioritize until necessary :)

Have a good one!
