### ISSUE TITLE
[Innspill til ikon]: BeaconSignals

### ISSUE THREAD

**Issue by Buvik** [navikt/Designsystemet#2600]
### Tilbakemelding

Dette ser mer ut som et nøkkelhull, det vil kanskje hjelpe om ikke sirkelen sluttes til bunnen på antennen.

**Comment by sjur-gr** [comment]
Ser ut som navnet er feil her. Dette er ikonet for "open source". Er det noe annet dere har behov for?

**Comment by sjur-gr** [comment]
Lukker denne saken. Åpne den om det er noe mer.
