### ISSUE TITLE
[Nytt ikon]: FigureChild

### ISSUE THREAD

**Issue by kristeine** [navikt/Designsystemet#2625]
### Navn på ikonet

FigureChild

### Eksempel på ikonet

I løsningene for barnetrygd, kontantstøtte og enslig forsørger bruker vi ikoner for å representere personene i en behandling:
ukjent kjønn, kvinne, jente, mann, gutt
<img width="169" alt="image" src="https://github.com/navikt/aksel/assets/2379098/1b322cad-2fa6-44b7-af7c-58eedeaccfbd">

I den nye ikonpakken finner vi FigureCombination, FigureOutward og FigureInward, men mangler en figur for jente/gutt/barn. Det hadde vært gull, så kan vi gå vekk fra de gamle ikonene 😇

**Comment by sjur-gr** [comment]
Vi har [denne for bar nå](https://aksel.nav.no/ikoner/ChildEyes), men den står ikke så godt sammen de andre. Kan vi lage en for barn uavhengig kjønn? Jeg sprø fordi barn tegnet som "figure" vil bli veldig liten og jeg er usikker på om detaljene blir tydelig nok.

**Comment by kristeine** [comment]
Ja, det går fint med uavhengig kjønn, vi kan bruke farge for å indikere det 👍

**Comment by KenAJoh** [comment]
Kan teste dette ikonet i nyeste versjon 🚀 
- https://aksel.nav.no/ikoner/FigureChild
