### ISSUE TITLE
[Innspill til ikon]: Buldings3

### ISSUE THREAD

**Issue by kristeine** [navikt/Designsystemet#2627]
### Tilbakemelding

Kan vi fikse skrivefeilen i disse ikonene? Buldings -> Buildings
- Buldings2Icon
- Buldings2FillIcon
- Buldings3Icon
- Buldings3FillIcon

**Comment by sjur-gr** [comment]
Publisert i Figma @KenAJoh

**Comment by KenAJoh** [comment]
Navn er oppdatert i `v5.15.0` da 🙌  For å ikke introdusere breaking changes vil disse fortsatt være tilgjengelig i ikonpakken, men ikke vises i ikon dokumentasjonen vår 📝
