### ISSUE TITLE
[BUG] <Alert size="small" closeButton/> ikke sentrert

### ISSUE THREAD

**Issue by ivoiv** [navikt/Designsystemet#2640]
## Hva er feilen/problemet?

Teksten på en "small" Alert er ikke sentrert på samme linje som "medium" når `closeButton` er satt.
Den ligger bittelitt under nivået til ikonene.

Ser ut som at Lukk-knappen er litt for stor/har for mye padding som gjør at den utvider Alert-boksen.

## Eksempel/Tilleggsinformasjon (valgfri)
[Playroom eksempel](https://aksel.nav.no/sandbox/index.html?code=N4Igxg9gJgpiBcJgB0B2ACdAKLBKdAvAHzooabqSoDOALugKIAeAhgLYAOANjIdvsVJoK6AE4xaAV1EYsAHigBLAG6UuLatQBy7GAWQgA5qMVR0hlhwC0AFgNFhI9HICCPUbQDqi2gAsAwlwQ1DAAQpK0tBAYyiwmLKi0%2BiDUkmBgMJoG6NSKAF56BmwwSpJs2WBBIeGR0QTAtKKSMAC%2BDuRO6AAiMKiovDCiYooA1rSKhjm9jYO0AHSOInIA9G6z3n6BwWERUajtna7uXj4BVTu1MXGKCUkGqemZ1Nm5BcnUbCxcXBXnNXv1ABmXxCbUWTh6fQGQxMYwmU0S4g8Cw6FBWaw8GzO23%2B0QOTiO61OW2qu2i6Fi8US7zSGSyIBy%2BUKKU%2B31%2BOLJqHqjWaYNRIkh-XQg3QoxGvBCiNmKMOq2OWJJFz2%2BMwKyUyiIuAA3GgWjrUFQ6OgMSdNn9OXwsMBKL5FFwoOJUAAaCnXW4u14wF2VDmXdAtAQkMgiQ30ADa1F8EAA7h6JABlKPRgC6fAASjAWGB5pIQvHaCxaDAsDyYNrweIpDJsJGY%2BgAGT17CEjyuqlJYCUm6JFqMt7AT29n2ky71YdK6K96KK%2Bp4QgkEK0RMxrDArghXB8zqYYBgW32x3oAA%2BR-QBn80SLiQMLXBqrls015dQerQFYk0gwcmY7G4vGW%2BIBnguogC0QA)

![image](https://github.com/navikt/aksel/assets/11502345/a46cb6c9-f1da-41df-a831-3bdbeb93cd0a)

**Comment by Trent-NAV** [comment]
Henger meg på denne for Figma versjonen har samme setup som @ivoiv beskriver her. 

Når jeg går inn på lagene i Figma versjonen og fjerner close button icon spacing fra det venstrestilte ikonet og close button text spacing som framer text framen, så retter ting seg opp. Men jeg ser også at det høyrestilte close ikonet ikke reduseres i hverken visuell størrelse eller container størrelse på Small variant, den beholder 32x32px target size men 24x24px er tilstrekkelig mtp WCAG AA. Bare et innspill på det sistnevnte selv om det i Figma ikke ser ut til å endre utgangspunktet med misalignment.

**Comment by sjur-gr** [comment]
Jeg klarer ikke å reprodusere det. Både [i Figma](https://www.figma.com/file/GokRG0D5xjlAg6yov3wJe3/Alert-small-test?type=design&node-id=0%3A1&mode=dev) og [i kode](https://aksel.nav.no/sandbox/index.html?code=N4Igxg9gJgpiBcJgB0B2ACdAKLBKdAvAHzooabqSoDOALugKIAeAhgLYAOANjIdvsVJoK6AE4xaAV1EYsAHigBLAG6UuLatQBy7GAWQgA5qMVR0hlhwC0AFgNFhI9I5FyAgj1G0A6otoALAGEuCGoYACFJWloIDGpFAC89A2o2Fi4uA3RlFhMWVFp9EGpJMDAYTXsXJwBlAA%2BAa1QWMxhRdDDUKHpFVFQAQmrMOQB6DzafPyCQsMjo2IdyEWrRpWUiXABuNABfbdQqOnRxr18A4NCIqJiMAmxgSn9FLihxVAAabNzFfNpPnYEJDIIkO9AA2tR-BAAO6fMK0GpQ6EAXT4ACUYCwwLQAHSSMI1WgsWgwLC0USSGBbariKQybCQmHoABkzOw7k89ByeQKBGA3J%2BBR2akucxu6FiFzCfLwhBI8MRMKwADN0mFcDtFk4KMAwE8Xm90AAfI3OECBWIkgoGHZDdCjE60DbU1B7NA0iTSDByZjsbi8EZa9AAvC7EDvEDQ0wBagIMEAZgATAAGZE7IA) så ser det ut som teksten står riktig sammen med `CloseButton`

**Comment by Trent-NAV** [comment]
Når komponentet hentes fra Core UI Kit er Close button på default, samtidig er layeret Close button icon spacing også på, de sees som lilla bokser. Når man fjerner Close button fra Small alert, enten med bolean eller direkte i layers så rettes ting opp. Close button står i 32x32 frame på både Small og Medium. Kanskje close button burde justeres med komponent størrelsen, og kanskje det også bør gjelde for venstrestilt ikon, akkurat slik tekststørrelsen endres med komponentstørrelse.  

### Alert small
![small_alert](https://github.com/navikt/aksel/assets/86958516/acd5ae29-720a-4a89-b4d4-8b7ce2c0a43b)

**Comment by ivoiv** [comment]
> Jeg klarer ikke å reprodusere det. Både [i Figma](https://www.figma.com/file/GokRG0D5xjlAg6yov3wJe3/Alert-small-test?type=design&node-id=0%3A1&mode=dev) og [i kode](https://aksel.nav.no/sandbox/index.html?code=N4Igxg9gJgpiBcJgB0B2ACdAKLBKdAvAHzooabqSoDOALugKIAeAhgLYAOANjIdvsVJoK6AE4xaAV1EYsAHigBLAG6UuLatQBy7GAWQgA5qMVR0hlhwC0AFgNFhI9I5FyAgj1G0A6otoALAGEuCGoYACFJWloIDGpFAC89A2o2Fi4uA3RlFhMWVFp9EGpJMDAYTXsXJwBlAA%2BAa1QWMxhRdDDUKHpFVFQAQmrMOQB6DzafPyCQsMjo2IdyEWrRpWUiXABuNABfbdQqOnRxr18A4NCIqJiMAmxgSn9FLihxVAAabNzFfNpPnYEJDIIkO9AA2tR-BAAO6fMK0GpQ6EAXT4ACUYCwwLQAHSSMI1WgsWgwLC0USSGBbariKQybCQmHoABkzOw7k89ByeQKBGA3J%2BBR2akucxu6FiFzCfLwhBI8MRMKwADN0mFcDtFk4KMAwE8Xm90AAfI3OECBWIkgoGHZDdCjE60DbU1B7NA0iTSDByZjsbi8EZa9AAvC7EDvEDQ0wBagIMEAZgATAAGZE7IA) så ser det ut som teksten står riktig sammen med `CloseButton`

@sjur-gr Det er fordi du ser på Medium versjonen i din Playroom. Din komponent sender ikke `size`-proppen videre til `Alert`en.

**Comment by KenAJoh** [comment]
Tror denne skal være fikset nå i 6.12 🤞 
https://github.com/navikt/aksel/pull/3007
