### ISSUE TITLE
[Nye ikoner]: Geometriske former, stiplet bokmerke og huskelapp-ikon(er)

### ISSUE THREAD

**Issue by karihamnes** [navikt/Designsystemet#2658]
### Navn på ikonet

Det er behov for flere ikoner - se melding

### Eksempel på ikonet

Har laget [mockup av ikonene i denne Figma-filen](https://www.figma.com/file/61Q7OX0ibC7llPy1AV5DCp/Ikonbehov-team-obo?type=design&node-id=1%3A253&mode=design&t=lrMg6W2qK0po7dtK-1). Har også lagt ved bilde nederst.

### Geometriske former
Mange av ikonene i Aksel har bestemt betydning/mening, og noen ganger trenger man mer nøytrale ikoner for ikke å tillegge for mye vekt/mening/kulturell betydning. I vårt tilfelle er anvendelsen en kategorisering á la merkelapper i Outlook (vet ikke om det er der fortsatt?). Av UU-hensyn trenger vi å variere formen/omrisset, og fargene. Og da trenger vi noen rene former som fungerer både om de er store eller små. Vi har 5 ulike geometriske former som vi har gått for, i tillegg til et [bokmerke-ikonet som allerede eksisterer](https://aksel.nav.no/ikoner/Bookmark), altså:

- Trekant (likesidet) - I Figma brukte vi https://aksel.nav.no/ikoner/ExclamationmarkTriangle som utgangspunkt
- Kvadrat - I Figma brukte vi https://aksel.nav.no/ikoner/MenuElipsisVerticalSquare som utgangspunkt
- Sirkel -  I Figma brukte vi https://aksel.nav.no/ikoner/MenuElipsisVerticalCircle som utgangspunkt
- Diamant - I Figma brukte vi https://aksel.nav.no/ikoner/QuestionmarkDiamond som utgangspunkt
- Pentagon (femkant) - I Figma laget vi denne manuelt med polygon.

Disse bør eksistere i både stroke og fill-variant. 

### Stiplet bokmerke
I tillegg har vi behov for [en stiplet - dashed - variant av bokmerke](https://aksel.nav.no/ikoner/Bookmark), som indikerer en emptystate for å legge inn bokmerke/kategori slik som beskrevet over.

### Huskelapp-ikoner
Vi har tidligere fått hjelp til å lage et [remindersymbol (HandKnot)](https://aksel.nav.no/ikoner/HandKnot). Men dette fungerte dårlig i prod og i små versjoner, der ikonet blir for likt selve pekeren i nettleseren ved hover (pekefinger og hånd). 

For en huskelapp-funksjon vi bygger nå så har vi gått for et kvadrat med en blyant inni. Det er postits er metaforen for huskelappen, og de er mer gjennkjennbar som kvadrater enn med A4-layout, slik som ikonet https://aksel.nav.no/ikoner/DocPencil har. I https://aksel.nav.no/ikoner/DocPencil stikker blyanten ut av arket, men for en postit blir det litt uproporsjonert hvis man skal velge samme stil og bare endre slik at arket blir kvadratisk. Vi foreslår derfor å sette blyanten inni firkanten. 

For dette ikonet trenger vi stroke, fill og i tillegg et stiplet (dashed) ikon. Vi landet som dere ser på å ikke stiple blyanten siden den er såpass liten. Det sagt, ikonet inni Slack for å skrive melding er nokså nært, og det har blyanten stikkende ut. Hvis det bare blir tydelig nok når det blir lite, så er det jo forsåvidt greit. Hvis det ikke misforstås til å være en melding (Slack-ikonet er jo en melding). 

<img width="359" alt="obo-behov-ikoner" src="https://github.com/navikt/aksel/assets/61583515/1c30a56c-bd0d-4dee-a184-3861724072df">

![image](https://github.com/navikt/aksel/assets/61583515/7ef39f1b-56af-48d1-83f6-d73dc7ac697c)

**Comment by sjur-gr** [comment]
Utkast til nye ikoner @karihamnes 


![Image](https://github.com/navikt/aksel/assets/82579704/914eb634-36de-4d78-a47a-d2b0dcaa1238)

**Comment by sjur-gr** [comment]
@KenAJoh nye ikoner publisert i Figma og klare for kode
