### ISSUE TITLE
[Innspill til komponent]: <Combobox />

### ISSUE THREAD

**Issue by lurajon** [navikt/Designsystemet#2663]
### Tilbakemelding

Hei!

Det hadde vært supert om Combobox kunne støttet value:label som alternativer. Vi har f.eks ett kodeverk i bunn som er verdiene som kan bli sendt inn til API (value), mens det vi ønsker å vise til brukeren er en lesbar og forståelig tekst (label)

values ville da sett ut noe a.la dette: 

`initialOptions =  [{ value: 'test', label: 'Test som vises til bruker' }, { value: 'test_2', label: 'Ett annet alternativ' }]`

**Comment by it-vegard** [comment]
Hei!

Dette ligger på blokken som en av de neste oppgavene vi vil ta tak i: 
https://github.com/navikt/aksel/issues/2553

Lukker denne som duplikat, men følg gjerne issuet jeg lenket til over.

**Comment by lurajon** [comment]
Takk @it-vegard !
