### ISSUE TITLE
Focus state

### ISSUE THREAD

**Issue by Trent-NAV** [navikt/Designsystemet#2666]
### Tilbakemelding

Burde focus state vært dokumentert på Aksel? 

Hender at man har et prosjektsamarbeid med utviklere der egne komponenter som ikke finnes i Aksel designes, da må focus og slikt anordnes manuelt om man ikke bare går for browser native. Hvis utvikler er ny og kanskje er inne på kort oppdrag kan man alltids angi hvordan focus ser ut i NAV i Figma, eller man kan se i koden på Aksel komponenter, men kunne det vært nyttig med en formell dokumentasjon og beskrivelse av focus på Aksel? 

Man kunne også dokumentert [WCAG aspektene](https://www.w3.org/WAI/WCAG22/Understanding/focus-appearance.html) som del av praksis seksjonen.

**Eksempler på focus dokumentasjon.**

https://www.astrouxds.com/patterns/focus/

https://designsystem.gov.scot/styles/focus-states

https://m3.material.io/foundations/interaction/states/applying-states

**Comment by KenAJoh** [comment]
Vi har det på listen å se på fokus-state når vi nå jobber med ny palette og darkmode 👍
