### ISSUE TITLE
[BUG] Høyden på Textarea i lokalt bygg (React StrictMode)

### ISSUE THREAD

**Issue by idaame** [navikt/Designsystemet#2671]
## Hva er feilen/problemet?

I lokalt bygg (med React StrictMode) får Textarea satt høyden til kun 2 piksler og overflow hidden. Men når jeg høyreklikker på komponenten og trykker på "inspiser" vises plutselig hele høyden igjen. Ved refresh er alt tilbake til rar state igjen. I produksjon ser heldigvis alt helt fint ut, men hadde vært fint å få fikset opp så lokal utvikling ikke ser annerledes ut enn prod 😊 

Se bilder under:
![image](https://github.com/navikt/aksel/assets/25459913/b14ffc12-ae6e-40bd-bd57-532bfd753d57)
![image](https://github.com/navikt/aksel/assets/25459913/110ae015-ccac-4f38-ad46-dcd1f9ebde2e)

Lurer på om det kan være knyttet til denne commiten: https://github.com/navikt/aksel/commit/8dda59082d9e64a81751805e6be5c30e3fb9cfaa

Dette er sånn det egentlig skal se ut
![image](https://github.com/navikt/aksel/assets/25459913/42566b95-b7ed-4111-a81c-b724808be70b)

**Comment by HalvorHaugan** [comment]
Hei!
Hvilke(n) nettleser(e) har du testet med?
Er dette en app som jeg kan kjøre lokalt for å teste?

**Comment by idaame** [comment]
Har testet både i Arc og safari. Appen det gjelder er https://github.com/navikt/familie-ba-sak-frontend, men tror ikke du får kjørt den opp selv. Si ifra hvis jeg kan bistå med noe 😊

**Comment by HalvorHaugan** [comment]
I hvilken fil ligger koden for denne instansen av Textarea?

**Comment by HalvorHaugan** [comment]
Jeg har fått gjenskapt feilen nå, så trenger ikke svar på forrige spørsmål :)

**Comment by HalvorHaugan** [comment]
Dette skal nå være fikset i v5.17.2. Takk for at du rapporterte feilen!
