### ISSUE TITLE
[BUG]: <Combobox /> - Fjerning av valg med enter

### ISSUE THREAD

**Issue by HalvorHaugan** [navikt/Designsystemet#2676]
Gjelder multiselect med mulighet for å legge til nye verdier.

1. Legg til en egendefinert verdi.
2. Skriv inn ett av de forhåndsdefinerte verdiene og trykk enter.
Feil: I stedet for at det du skrev inn blir valgt, fjernes heller den egendefinerte verdien du la til først.

![combobox-addremove](https://github.com/navikt/aksel/assets/83693529/2ff18c62-1093-491c-a407-b3418569f2e4)

EDIT:
Nå får jeg også replikert feilen uten å legge til egendefinert verdi, i storyen "Max Selected Options". Problemet ser ut til å være at det er det første elementet i listen som toggles når du trykker enter, uansett hva du har skrevet.

**Comment by it-vegard** [comment]
Så vidt jeg kan se ble denne fikset i endringene som kom inn i versjon 6.6.0
