### ISSUE TITLE
[Innspill til komponent]: <Stepper />

### ISSUE THREAD

**Issue by Maamua06** [navikt/Designsystemet#2687]
### Tilbakemelding

Trenger flere eksempler på hvordan man kan bytte ut tallene i stepperen med ikoner

**Comment by KenAJoh** [comment]
Hei 👋 Dette er ikke mulig i dagens versjon av Stepper dessverre. `CheckMark`-ikonet dukker opp når man har satt et steg til `completed`, men utenom dette vil tallene ikke kunne byttes ut.
