### ISSUE TITLE
[Innspill til komponent]: <Tabs />

### ISSUE THREAD

**Issue by martin-andreassen** [navikt/Designsystemet#2698]
### Tilbakemelding

Aksel benyttes også for saksbehandlingssystem. Ønskelig med egendefinerte hurtigtaster for de enkelte tab'ene

**Comment by sjur-gr** [comment]
Kan også kombineres med [Tooltip with shortcuts](https://aksel.nav.no/komponenter/core/tooltip#tooltipdemo-with-shortcuts)

**Comment by KenAJoh** [comment]
Hei 👋 Dette er noe fagsyster kan implementere med relativt lite kode og tilpasse systemet sitt
```js
useEffect(() => {
  const handleKeyDown = (event: KeyboardEvent) => {
    if (event.key === [shortcut]) {
      setTab("tab1")
    } else if (event.key === [shortcut 2]) {
      setTab("tab2")
    }
  }

  window.addEventListener("keydown", handleKeyDown);

  return () => window.removeEventListener("keydown", handleKeyDown);
},[]);
```
