### ISSUE TITLE
[BUG] <Combobox />: Skjema sendes inn dersom man forsøker å velge et element i nedtrekkslisten med enter-tasten

### ISSUE THREAD

**Issue by akgagnat** [navikt/Designsystemet#2702]
## Hva er feilen/problemet?

I et `<form>` som inneholder en `<button type='submit'>` samt en combobox så vil skjemaet sendes inn dersom man forsøker å velge et element i nedtrekkslisten med _enter_-tasten. Elementet man forsøkte å velge blir for øvrig heller ikke registrert som valgt.

Forventer at skjemaet ikke sendes inn når man bruker enter-tasten til å velge et element i nedtrekkslisten.

## Steg for å reprodusere problemet (valgfri)

1. Opprett et skjema med en combobox og en button med type=submit (se kode nedenfor)
2. Åpne combobox, bruk piltastene for å gå til ønsket element i nedtrekkslisten, og trykk enter-tasten

## Eksempel/Tilleggsinformasjon (valgfri)

```  
    <form onSubmit={(event) => console.log("onSubmit")}>
      <UNSAFE_Combobox
        name="frukt"
        label="Velg frukt"
        options={["Appelsin", "Pære", "Melon"]}
      />
      <button type="submit">Send inn</button>
    </form>
```

**Comment by KenAJoh** [comment]
Hei 👋 Dette skal være fikset i versjon 6.6 av `@navikt/ds-react` 🤞 
[Endringslogg](https://aksel.nav.no/grunnleggende/kode/endringslogg#83cac4b6f124)
