### ISSUE TITLE
[BUG] Combobox: 

### ISSUE THREAD

**Issue by it-vegard** [navikt/Designsystemet#2710]
## Hva er feilen/problemet?
Hvis man fjerner chips med "enter" mens listen er åpen, så velger man automatisk et nytt element

### Hva forventet du skulle oppstå?
Chipen skulle forsvinne, og det skulle vært en mindre chip i listen enn før

### Hva skjedde istedenfor?
Det fokuserte elementet i listen blir valgt på "keyup", fordi fokus da er tilbake i input-feltet

## Steg for å reprodusere problemet (valgfri)

1. Velg et par elementer i Comboboxen (multiselect) med tastaturet. La det virtuelle fokuset stå i listen.
3. Trykk shift+tab for å fokusere en Chip
4. Trykk ned enter for å klikke på Chippen og fjerne den. Hold først nede enter og se at chipen forsvinner.
5. Slipp enter og se at det fokuserte elementet i listen blir valgt

**Comment by KenAJoh** [comment]
Ser ut som dette er fikset 🚀
