### ISSUE TITLE
[Innspill til komponent]: <Combobox />

### ISSUE THREAD

**Issue by Watercolours** [navikt/Designsystemet#2713]
### Tilbakemelding

EDIT: Feil i skjema gjør at "tilbakemelding" ikke fungerer som det skal. Blir bare "_Tom respons_".

Uansett... Combobox burde ta imot `Map<Key, Value>` og returnere _key_ i `onChange`. Per dags dato er Combobox utrolig kronglete å bruke siden man får _value_ i retur, som medfører at man må selv mappe value tilbake til key, ettersom de fleste backends forventer key-verdien.

**Comment by it-vegard** [comment]
Dette høres ut som de samme behovene som er meldt om i [dette issuet](https://github.com/navikt/aksel/issues/2553), som allerede er under utvikling.

Options vil nå støtte både `string` og `{ label: string, value: any }`. Value vil da returneres fra onToggleSelected. Her blir det mulig å være sende inn f.eks. en enum, eller et objekt med flere verdier man ønsker å få tilbake. Det blir altså en liste med objekter, ikke et Map, men jeg tror det vil løse det du ønsker?
