### ISSUE TITLE
[Innspill til komponent]: <LinkPanel />

### ISSUE THREAD

**Issue by frodehansen2** [navikt/Designsystemet#2724]
### Tilbakemelding

Hadde det vært mulig at navds-link-panel__content har 100% bredde? I og med den har flex styling får den ikke det automatisk, og tar kun opp den bredden som er i innholdet.

**Comment by KenAJoh** [comment]
Hei 👋 Tror dette kan være relatert til layout-et LinkPanel ligger i og ikke selve komponenten. [Testet i sandbox](https://aksel.nav.no/sandbox/index.html?code=N4Igxg9gJgpiBcJgApkEoAEBeAfB4AOgHYYaREDOALhgKIAeAhgLYAOANjNhutnoSVIYATjCoBXYSWTEhQgDwAZAJZEA1gAVGRGOwwALUQDMsBEAGIzGAEYRhsYTllyFK9Vp3sAdABVlVThwAQWFrGGUoCgoAD7UYYQxdTgTWeOZ-KniqeQB6N01tXV9-QOcXDCVVAs8vABEYCjBhZVYqZQgiJ0Fy0gBZGCgMADddKGUAcwx2bXGaVSJ9CHZBighmG3ZlBNFUzOE58YArGCIAGgxmAeHRiamZuaIFpZW1ja2RGF2sjAnjs4uriNlrdpkRZj9HotlhhVutrJttp8xN9fidzpdBkCxpNQeD5lCXnCER8vvsfkc0Rgyi5cvkPEV6o1mq12p1iNTSLSqvT2F05GgANzOAC%2BQqIzlEEikFQYLA4XByODFwrQ6GFxBApxAAHcIlR9BQEABtACMABYzQAGAC6wqAA) og tar opp all bredden som er tilgjengelig her 🤔 Testet også med flexlayout men klarer ikke replikere.

Kan hende vi testet feil så del gjerne noe kode vi kan teste 🙌 @frodehansen2

**Comment by KenAJoh** [comment]
Lukker denne da jeg antar det ordnet seg, bare å gjenåpne hvis det ikke stemmer.
