### ISSUE TITLE
[Innspill til komponent]: <Table />

### ISSUE THREAD

**Issue by perkynades** [navikt/Designsystemet#2725]
### Tilbakemelding

Hei. Har et ønske om at `SortState` interfacet som brukes til sortering av kolonner i `<Table />` inkluderer at det er ingen direction satt for et spesifikt `SortKey`, f.eks slikt:
`
export interface SortState {
  orderBy: string;
  direction: "ascending" | "descending" | "no-order";
}
` 

Da er det litt enklere å holde styr på sorteringen av de forskjellige kolonnene

**Comment by KenAJoh** [comment]
Hei @perkynades  👋 Siden dette vil være en breaking change ser vi på å ta den inn i neste major-versjon. Vil denne endringen løse problemet deres? 
https://github.com/navikt/aksel/pull/2726/files

**Comment by perkynades** [comment]
Det ser ut som det vi trenger ja!

**Comment by KenAJoh** [comment]
Er publisert i v6 nå 🎉 
https://nav-it.slack.com/archives/C7NE7A8UF/p1708353105088269
