### ISSUE TITLE
[Innspill til komponent]: <Radio />

### ISSUE THREAD

**Issue by Trent-NAV** [navikt/Designsystemet#2731]
### Radio group i Figma

I komponentbeskrivelsen på Aksel så angir dere at radio group skal anordnes som en vertikal liste, men for vår del benyttes radio alltid horisontalt fordi det i saksbehandlingssystem er mange kompakte plasseringsforhold. Det er som regel to eller maks tre radio buttons, så det scannes helt fint. Med bakgrunn i dette hadde det vært fint om radio group også kom som en **singel** radio button i Figma og/eller at radio group har en horizontal variant prop i Figma. Da slipper man å løsrive group og anordne det manuelt og da risikere å gå glipp av eventuelle komponent updates osv fordi den da er desentralisert. For utviklere er det enkelt å tilpasse komponentet live, så de forholder seg til dette på en annen måte. 

Eksempel på "inline" horisontal radio button plassert i kontekst av tabell i Pesys, det er flere slike lignende områder.
Toggle group blir for dominerende eller stor for slike plasseringer. Radio brukes gjennomgående i hele systemet som del av et forutsigbart handlingsmønster for saksbehandlerne. 

![radio buttons Pesys](https://github.com/navikt/aksel/assets/86958516/34b6e721-f8fa-459f-8873-362e0468414f)

![radiogroup_table](https://github.com/navikt/aksel/assets/86958516/ecd062c4-3009-43d4-8f70-00ccb3c90ca9)

-----------------------------------------------------------------------------------------------------------

 ### Eksempler på horisontal radio group i andre designsystemer
 
https://carbondesignsystem.com/components/radio-button/usage/

https://design-system.service.gov.uk/components/radios/#:~:text=Nunjucks-,Inline%20radios,-In%20some%20cases

https://ant.design/components/radio#components-radio-demo-radiogroup

**Comment by KenAJoh** [comment]
VI har oppdatert dokumentasjonen med demo og retningslinjer for bruk av horisontal radio nå 🎉 
https://aksel.nav.no/komponenter/core/radio#1202e1bece90
