### ISSUE TITLE
Select i Figma

### ISSUE THREAD

**Issue by Trent-NAV** [navikt/Designsystemet#2747]
### På ønskelista 🙏

Som et hendig tillegg til de andre statene som [Select](https://aksel.nav.no/komponenter/core/select) har i **Figma** versjonen så ville open/active state gjort susen, gjerne også som en interactive component slik at den blir enkel å prototype rett fra boksen med innholdsvisning, så kan man bare bytte label items i nedtrekket til noe autentisk for hver gang. Eneste interaktive respons på den nå er hover og focus.

**Comment by sjur-gr** [comment]
Dette funker best i Figma ved å bruke overlay-interaksjon. Og overlay funker ikke for komponenter levert gjennom et bibliotek. Så du må sette opp overlay-interaksjonen lokalt i din fil.
