### ISSUE TITLE
[DO-A-THING-REQUEST] Authorize repo

### ISSUE THREAD

**Issue by Reasonable-Solutions** [navikt/Designsystemet#2755]
Heya!
Kan noen på aksel gå inn i console https://console.nav.cloud.nais.io/ å legge authorize deploy på repoet navikt/aksel?
Vi sitter å flytter buckets for cdn for det nye reconciler opplegget vi har lagd

**Comment by KenAJoh** [comment]
Bør være fikset da 🤞 
<img width="1334" alt="Screenshot 2024-02-23 at 19 20 38" src="https://github.com/navikt/aksel/assets/26967723/72a80a77-0b5c-43e1-8d9f-aee17273d26f">
