### ISSUE TITLE
[Ny komponent]: Språkvelger

### ISSUE THREAD

**Issue by idaame** [navikt/Designsystemet#2763]
### Navn på komponent

Språkvelger

### Eksempel på komponenten

Hei, til søknadsdialogene våre trenger vi språkvelgere og kunne ønske det fantes noe felles i Nav på dette, så vi slipper å lage vår egenkomponerte løsning. Er det noe dere har vurdert å lage? 🙏

I dag lager vi vår egen hacky løsning med `react-aria-menubutton`, men denne er utdatert så vi trenger å gjøre en oppgradering ganske snart. Har vurdert å bruke deres `Select`, men der er det ikke (så langt jeg vet) mulighet for å sette ikon, så det vil isåfall endre stilen på språkvelgeren ganske mye

Hvordan vår ser ut i dag: 
<img width="254" alt="image" src="https://github.com/navikt/aksel/assets/25459913/f03a8a48-6466-43b5-972f-0cef1d549f8d">

**Comment by KenAJoh** [comment]
Hei 👋 Siden dekoratøren har innebygd språkvelger er dette en komponent vi (med det første) ikke har tenkt å ta inn i systemet. 
https://github.com/navikt/nav-dekoratoren?tab=readme-ov-file#eksempler

**Comment by idaame** [comment]
Skjønner! Hvilken språkvelger tenker du på? Er det denne som ligger i footeren?
<img width="401" alt="image" src="https://github.com/navikt/aksel/assets/25459913/854878c3-33b0-49f6-866b-ff261a8520b8">

**Comment by KenAJoh** [comment]
Vil være den som f.eks vise så forsiden til Nav.no (mener å huske den skal tilhøre dekoratøren 🤞 )

<img width="1511" alt="Screenshot 2024-03-15 at 10 07 58" src="https://github.com/navikt/aksel/assets/26967723/18ebe81f-382f-482a-8e39-5b3924dd766a">

**Comment by idaame** [comment]
Ah okei, den har ikke vi klart å finne i docsene til dekoratøren - vi tolket det som at det er den språkvelgeren jeg sendte bilde av som ligger i footeren som er i dekoratøren 🤔 Hvis man [går inn på siden til "språkvelger" eksemplet](https://www.nav.no/dekoratoren/?availableLanguages=[{"locale":"nb","url":"https://www.nav.no/person/kontakt-oss"},{"locale":"en","url":"https://www.nav.no/person/kontakt-oss/en/"}]) så er det kun språkvelgeren i footeren som dukker opp hverfall. 

Etter å ha sett litt mer på nav.no ser vi at det er to forskjellig språkvelgere liggende inne (den du sendte bilde av og den i footeren) og ganske inkonsistent oppførsel, men det er kanskje en oppgave for noen andre å fikse opp i 😅 men, et poeng her er at det kunne vært ganske interessant om dere (evt noen andre om det er mer passende) hadde tatt en titt på bruken av språkvelgere i nav-sfæren som en helhet. Vi har sett at det er flere søknadsdialoger som har laget sin egen variant av en språkvelger, inkludert oss, og det aller beste hadde jo vært om det fantes tydelige retningslinjer og en felles komponent alle kunne bruke så det blir likt på tvers og bedre opplevelse for brukerne 🙌 🤞

**Comment by idaame** [comment]
@KenAJoh har dere sett noe mer på dette? 👆

**Comment by KenAJoh** [comment]
Vi har ikke sett noe mer på denne, så lenge dekoratøren inneholder innebygd støtte for språkvelger blir vi mest sannsynlig på kort sikt ikke å tilby en egen variant da dekoratøren er brukt av de fleste åpne sider. Vi har sett en del forskjellige språkvelgere rundt på ulike flater, men har ikke funnet noen veldig konkrete forskjeller som ikke dekoratøren allerede tilbyr 🙁 

Brukt sammen med `@navikt/nav-dekoratoren-moduler`-pakken vil man selv styre alle språk som vises, og hva som skjer når et språk blir valgt med funksjonen `onLanguageSelect` i dekoratøren ([docs](https://github.com/navikt/nav-dekoratoren-moduler?tab=readme-ov-file#onlanguageselect)). Hvis det er noe som mangler der har man også slack-kanalen [#dekoratøren-på-navno](https://nav-it.slack.com/archives/CAFRFDJMN)
