### ISSUE TITLE
[Aksel.nav.no - 404]

### ISSUE THREAD

**Issue by gunnjohansen2** [navikt/Designsystemet#2769]
## Hva er feilen/problemet?
Denne siden var lenket fra et eller annet sted i Aksel. Hadde mange tabs oppe, så klarte ikke å finne fra hvor, men kanskje dere klarer? 
https://aksel.nav.no/god-praksis/artikler/uxtweak?tema=brukerinnsikt

Føyer til en liten skrivefeil (nestemt ) herfra: https://aksel.nav.no/god-praksis/artikler/mal-brukeratferd-med-amplitude?tema=brukerinnsikt#6ace7eb3f956
_Velg prosjekt i Amplitude > Når teamet har **nestemt** seg for å bruke Amplitude så må dere velge hvilket prosjekt dere skal sende data til._

(skriv her.)

## Steg for å reprodusere problemet (valgfri)

(skriv her.)

## Eksempel/Tilleggsinformasjon (valgfri)

```
 Hvis mulig, legg gjerne til kode her, evt lenke til kode i repo
```

**Comment by KenAJoh** [comment]
Hei 👋 UX-tweaks artikkelen ble avpublisert i desember 2023. For innlogging på uxtweaks etc tror jeg Felgen er beste portal nå 🤞 https://felgen.intern.nav.no/

Har fikset skrivefeil 🎉
