### ISSUE TITLE
Størrelseforhold [Innspill til komponent]: <CopyButton />

### ISSUE THREAD

**Issue by Trent-NAV** [navikt/Designsystemet#2781]
### Tilbakemelding

Komponentet har tre størrelsesvarianter men kun Xsmall påvirker størrelsen på selve ikonet, Medium og Small er like og endrer kun target size. Tenkte det kunne vært greit med feks større ikon på Medium.

![copybutton_size02](https://github.com/navikt/aksel/assets/86958516/b2e5aa02-975d-4b1f-9ce0-88d3692b2f5d)

**Comment by sjur-gr** [comment]
Dette er "by design" for at vektingen mellom ikon og tekst skal funke godt på Medium-varianten. Gjelder både CopyButton og Button. Men jeg ser at vi kan justere ikonet på Small-varianten ned til 20px. Den er litt ubalansert.

**Comment by KenAJoh** [comment]
@sjur-gr Er oppdatert til 20px for ikon på small og xsmall i kode nå 🚀
