### ISSUE TITLE
[Dokumentasjon] Egen kategori for verktøy/guides - Hotjar, Amplitude, div. andre.

### ISSUE THREAD

**Issue by ivoiv** [navikt/Designsystemet#2796]
Aksel har guides til hvodan legge inn eller jobbe med diverse verktøy hos NAV rettet mot eksterne sider og sluttbrukere f.eks. Hotjar, Amplitude, Figma, Siteimprov, osv.
I dag ligger disse gravd under artikler i forskjellige kategorier i God Praksis.
Jeg husker aldri hvilken kategori de er lagt under, så jeg bruker nesten alltid Søk-funksjonen.

Hadde vært fint om disse fikk en egen kategori ved siden av God Praksis, Grunnleggende osv.
Noe type "Verktøy" eller "Programvare" eller noe sånt, med en liste over dem til venstre, som i Komponenter. 

Kanskje bare en lenke til [Felgen](https://felgen.intern.nav.no/) eller bare en curated utvalg av verktøy fra Felgen som hovedsakelig er relevante for brukersider.

Har vi ikke plass kan jeg ikke se at Mønster og Maler med sine 2 items fortjener en egen kategori, den kan gjerne legge seg under Grunnleggende tenker jeg.

**Comment by KenAJoh** [comment]
Liten teaser, men vi kommer snart med en oppdatering til God praksis der man kan filtrere etter innholdstype. Verktøy vil da være en av dem. 
For mønster og maler vil det etterhvert også komme flere sider om skjema de neste månedene 🤞 

<img width="571" alt="Screenshot 2024-03-19 at 10 20 12" src="https://github.com/navikt/aksel/assets/26967723/09abd6b9-e6cb-419d-b3f7-7d6d7a523061">

**Comment by sjur-gr** [comment]
Vi jobber med dette nå og vil få det ut om ikke så lenge.
