### ISSUE TITLE
[Innspill til komponent]: <FileUpload />

### ISSUE THREAD

**Issue by rrsslnd** [navikt/Designsystemet#2816]
### Tilbakemelding

Jeg savner en list item variant for å vise filer du har lastet opp tidligere. Dette er filer som allerede er arkivert og som det ikke er mulig å slette. Det er derfor ikke behov for “trash”-knapp, men det er nyttig å kunne vise dato for når filen ble lastet opp. Er det mulig å få inn en slik variant? (Se nederste list item i skjermbilde 👇)

![Skjermbilde 2024-03-21 kl  13 06 15](https://github.com/navikt/aksel/assets/5665943/1d991d48-2bfb-4f09-b857-de13feca2afb)

**Comment by KenAJoh** [comment]
Hei 👋  I versjon 6.11 har vi nå lagt til en egen `description`-prop på `FileUpload.Item` slik at man selv kan styre hvilken tekst som står der. Teksten vil da erstatte dagens `xx kB`-visning rett under tittel.
