### ISSUE TITLE
[Nytt ikon]: Kompetanseutvikling ikon til Aksel God Praksis

### ISSUE THREAD

**Issue by eilifjohansen** [navikt/Designsystemet#2820]
### Navn på ikonet

Kompetanseutvikling

### Eksempel på ikonet

Det er ønsker om å etablere et nytt Aksel God Praksis tema; Kompetanseutvikling. I den forbindelse har vi behov for et ikon som kan brukes på God Praksis temasiden. Temaet vil inkludere innlegg om alt fra kompetanseutviklingsmodellen, fagtorsdag, faggrupper, Delta ++

**Comment by sjur-gr** [comment]
Det skal vi få til @eilifjohansen . Mens dere planlegger, kan dere også ta tak i hvilke undertemaer artiklene skal kobles til? Minimum 1 til å starte med. Hvert undertema må ha en beskrivelse (ca. 200 tegn).

**Comment by sjur-gr** [comment]
Done. Tema er satt opp i den nye strukturen. Vi jobber med å få det ut snart. Send meg teksten på DM.

Da trenger jeg:

- Beskrivelse av temaet Kompetanse (ca. 200 tegn)
- Undertema med beskrivelse (ca. 200 tegn)
- Hvem som skal være temakontakter

<img width="816" alt="Skjermbilde 2024-03-25 kl  15 27 43" src="https://github.com/navikt/aksel/assets/82579704/4a227314-414e-49c4-9842-7511da1c5b4e">
