### ISSUE TITLE
[Innspill til komponent]: <Link />

### ISSUE THREAD

**Issue by Trent-NAV** [navikt/Designsystemet#2822]
### Link color token i Figma

Visited state er nyttig å inkludere i prototyper men den er ikke mappet som semantisk  color token for **tekst** i Core UI kit, den er kun tilgjengelig som Icon/Visited, den burde hatt en Text/Visited stil. Icon/Visited (#634689) er også brukt uten semantisk mapping som en global color token ved navn Alt-1, det også under Icon, samtidig opererer Alt-1 også som #8269A2 i Surface og Border seksjonen. 

Jeg tok en sjekk med utvikler på dette og de ser ut til å ha en React relasjon til a:visited {color: var(--a-text-visited)}

![visited_color](https://github.com/navikt/aksel/assets/86958516/232a3cdf-4e8a-4be9-ab7c-c7cdf1b456e0)

**Comment by sjur-gr** [comment]
Fiksa det nå. Fargen var nok plassert i feil "mappe". Ikoner i lenker bruker ofte samme farge som tekst i kode.

**Comment by Trent-NAV** [comment]
[like]  Gulbrandsen, Trent reacted to your message:
________________________________
