### ISSUE TITLE
Bakgrunnsdesign på produktbloggen tiltrekker oppmerksomheten på uheldig vis

### ISSUE THREAD

**Issue by finiteattention** [navikt/Designsystemet#2823]
Hei :) Jeg driver og leser https://aksel.nav.no/produktbloggen/vi-pusser-opp-malene-oppbygging-av-ny-produktside. Det finnes noen gule, linjebaserte former oppå den lysgule bagrunnsfargen. Tro det eller ei, opplever jeg disse linjene som kanskje distraherende, idet de tvinger vekk oppmerksomheta fra teksten jeg kom for å lese. 

Legger ved et bilde som prøver å gjenskape den subjektive opplevelsen når jeg møtes med dette. Så vidt jeg opplever det (disclaimer, dette er ikke øyesporing, osv), tiltrekkes blikket der:

- linja treffer treffer lange eller medium-lange ord (treffet bidrar til litt mer visuell tyngde, føles det som)
- linja treffer kanten til bilder med hvit bakgrunnsfarge (ikke et inntrykk i og for seg, mer at jeg merker at plutselig har jeg havnet der bare)
- linja bøyer seg skarpt (jeg blir plutselig bevisst at her var det en "feature" jeg burde sjekke ut)
- linja strekker seg langt ut i "space" (merker at jeg har lyst til å bli med den oppover)
- flere av de overnevnte skjer samme sted. Et godt eksempel er ordet "tidligere", der linja treffer et mellomlangt ord, _og_ endrer retning. Enda bedre er "Målgrupper", siden den både er en mellomoverskrift og treffer hele to linjer, derav en også endrer retning. Dét var et blikkfang :) 

Disse merker jeg at jeg aktivt må kjempe mot for å kunne fokusere på selve ordene som står. Dette særlig i dag da jeg er trøtt, men på andre dager blir det nok også litt effekt.

Jeg tenker ikke at man skal endre på grafiskdesign-grep fordi Chris er trøtt i dag, men jeg anbefaler at dere tar en øyesporingsrunde på sånne sider med folk som eksempelvis er slitne, har oppmerksomhetsforstyrrelser, eller mental helse diagnoser, eller lese- eller kognitive vansker.

Takk som leser, som alltid 🙏 

![Chris sin oppmerksomhet spiller ping-pong](https://github.com/navikt/aksel/assets/6875491/b3ed1f78-c29d-4396-852c-545ffb4e4fed)

**Comment by finiteattention** [comment]
Legger også ved samme skjermbilde uten markering, da den lyse gulfargen ikke alltid er så lett å finne under det blå sporet jeg har tegnet, og det kan være fint å sammenligne.
![Chris yoyo blank](https://github.com/navikt/aksel/assets/6875491/8f18c9a6-b31d-4309-86fb-c327f4821b2a)

**Comment by KenAJoh** [comment]
Takk for innspill! 👏  Vi gikk for å fjernet illustrasjonen 🔥

**Comment by finiteattention** [comment]
Wow, det gikk utrolig fort! 😀 Tusen takk 🙌
