### ISSUE TITLE
[Innspill til komponent]: <MonthPicker> sperre fjerning av valgt måned

### ISSUE THREAD

**Issue by ivoiv** [navikt/Designsystemet#2829]
### Tilbakemelding

Dersom man trykker på den valgte måned, blir valget fjernet og MonthPicker sender onchanged med undefined/tomt.
Dette ødelegger for logikk hvor noe alltid skal være valgt.
Er det mulig å legge inn en prop som sperrer for "de-select" av dato?

![ScreenRecording2024-04-03at12 08 05-ezgif com-video-to-gif-converter](https://github.com/navikt/aksel/assets/11502345/aee35dc2-cad6-41c6-b72e-b94f56ab9934)

**Comment by KenAJoh** [comment]
Gir mening det 👍 Bruker dere useMonthPicker-hook eller MonthPicker.Standalone her?

**Comment by KenAJoh** [comment]
![Screenshot 2024-04-09 at 10 11 29](https://github.com/navikt/aksel/assets/26967723/3ad332cf-be0a-4123-8bdb-43a14973d1b5)

Etter litt sjekking har `useMonthpicker` en required-prop som gjør akkurat dette. Prop-en er ikke tilgjengelig for Standalone-versjonen, så hjelper selvfølgelig ikke hvis den blir brukt.

**Comment by ivoiv** [comment]
Hei! Vi bruker `useMonthPicker` men jeg ser ikke at `required` hjelper.

La til `required` til et [Playroom](https://aksel.nav.no/sandbox/index.html?code=N4Igxg9gJgpiBcJgB0B2ACdAKLBKdAvAHzooabqSoDOALugKIAeAhgLYAOANjIdvsVJoKlCDXoBtABYtqDAE7yI8gDTpqMWgAlZCpfIC6fAEowWYWgDoArhoDKtFrRhYAZiy4bcAbmEUqdKTobGK0UhwAlmAA1jDyAApKHNRqEagc1rSJEMnoAL58tjAAsqHhUbHyWGQiIq5KbAAiTjDw6KgwAO7ozc5YyCAAgtYA5ugATADMEwAMAIwAnAO4Kn616PIwAI7WEZtQbbTy1jCr5Ou0EL2t7V09Lf1DoxPT4zPjAKzLZ%2BuYYgBqHgiUBabSwADcPAISDVfiINNpdIplFgAISQriWCLUQFcYGlVBhHxrOGiGgQHiWLgQEYQqG%2Bc61PI-Ch5YmMza0azyDBYAA8UAi4MoXFk1AAcuwYAQBmw0gBaKTyhYANgGRBJmD5BLC8QqcVIliNIUJ5RicWyyTyGsZIm1ZT15vklgAkulMoajWkMlkktQCqKAEYwLgykD-ENjNgAU46UAG6Di%2BgIwBkcmR8nQADIs%2BgBo1rMFo%2BhwZHeDG4wM8gB6G3rPnVnVSR2VOsUBuC8FEdl5BkkzncjB85jsbi8Wt%2BNl4NB5EAqECdYFhagICSTN4qObjAAcMwMeSAA) eksempel og jeg kan fremdeles ta bort valgt måned.

**Comment by KenAJoh** [comment]
Blir fikset i v6.5.0 i løpet av dagen 🚀
