### ISSUE TITLE
Unike Endre svar-lenker for skjermleser: <FormSummary />

### ISSUE THREAD

**Issue by mortentollefsen** [navikt/Designsystemet#2854]
### Tilbakemelding

For å øke verdien av lenkene i lenkeliste kan vi vurdere å gjøre følgende:
<a ...><span class=sr-only>Tilhørende 'heading' </span>Endre svar</a>

**Comment by mortentollefsen** [comment]
Dvs. skal vi første inn med sr-only blir det jo enda penere sånn:
<a ...><span class=sr-only>'Tilhørende heading' endre svar</span><span aria-hidden=true'>Endre svar</span></a>

**Comment by KenAJoh** [comment]
Etter ulike diskusjoner på Slack ble vi enige om å ikke endre på dagens løsning.
