### ISSUE TITLE
[Innspill til komponent]: <Modal />

### ISSUE THREAD

**Issue by Trent-NAV** [navikt/Designsystemet#2862]
### Figma 

Komponentet har size variants for title og buttons men ikke for bodytekst, den er statisk BodyLong/Medium. Som kjent bruker internflate og saksbehandling gjerne Small alternativer for alt. Siden title har en funksjonell Small variant så er det naturlig at bodytekst også har det med BodyLong/Small. Dette som et alternativ til det å bytte stilen manuelt.

Det er for øvrig supert med komponenter som tilbyr **totale** size varianter som endrer samtlige innslag i komponentet, slik som med Search, Checkbox, Tabs, Alert m.fl. Gevinsten ved dette er ekstra stor på innholdsrike komponenter som Modal, man kan fortsatt beholde de ulike individuelle variant propsene, forskjellen ville bare blitt færre manuelle tilpasninger. For hvis man feks. bruker Small title er sjansen stor for at også bodyteksten skal være Small - og antageligvis også buttons 😊  

![Figma varianter](https://github.com/navikt/aksel/assets/86958516/c92d3739-fe19-4b8b-a49b-660820619454)

**Comment by sjur-gr** [comment]
I kode er body i modal riktekst og man kan velge den fonten man vil. Vi kan få inn body-small i Figma. En felles size prop funker ikke i Figma dessverre.

**Comment by Trent-NAV** [comment]
Vet ikke om vi tenker på samme sak nå eller om det er det er noe jeg ikke har tenkt på i oppbyggelsen av Modal komponentet? Tenker det blir konseptuelt det samme som Aksel Search, Checkbox og Alert, der man slipper manuell etterjustering av size på ikon, tekst etc fordi de endrer seg i takt med global size variant.

**Comment by Trent-NAV** [comment]
Bare for å illustrere så gjenskapte jeg en hurtigversjon av Modal uten alle de ulike boolean props'ene bare for å vise hva jeg mener med total size variant samtidig med at props variantene også kan justeres enkeltvis, på samme måte som de andre Aksel komponentene jeg nevnte. Jeg tenker bare at default innstillingene for hvert innslag i Modalen er tilpasset størrelsen når man velger size variant for hele komponentet.     

https://github.com/navikt/aksel/assets/86958516/8263616b-c0eb-4163-ac2b-9dcd1a33ec95

**Comment by Trent-NAV** [comment]
Her er et lite eksempel (ikke tenk på farge eksperimentet 😀) på en mindre innholdsrik komponent laget kun for å illustrere hva jeg mener, men den er bygget konseptuelt likt som Modalen med nested instances for individuell kontroll av enkeltinnslagene. Men i mitt eksempel så har jeg i tillegg en total eller "global" size variant. Det blir forøvrig identisk med oppsettet i Aksel Radio Group, som også har en total size variant på denne måten. Aksel ToggleGroup har det **nesten** da headline title ikke endrer seg der. 

https://github.com/navikt/aksel/assets/86958516/79897216-e3df-4f09-bd39-953e0805d1fb

----------------------------------------------------------------------------------------------------------------------------------

Her er et autentisk eksempel med flere props men uten at de er nested. Dette er et lokalt komponent uten total size variant, derfor er kun Default tilgjengelig for øyeblikket, men hadde jeg hatt en annen size variant så hadde jeg lagt den til som en Type variant slik at alle innslagene endret seg til Small. 

https://github.com/navikt/aksel/assets/86958516/47273997-1263-4c13-938a-c9d399b71c02

**Comment by sjur-gr** [comment]
Jeg må lage en ny versjon og endre litt på strukturen. Får den ut denne uka.

**Comment by sjur-gr** [comment]
Ute nå 🤘
