### ISSUE TITLE
[Nytt ikon]: GroupMinus

### ISSUE THREAD

**Issue by bha96** [navikt/Designsystemet#2864]
### Navn på ikonet

GroupMinusIcon

### Eksempel på ikonet

https://cdn.iconscout.com/icon/premium/png-512-thumb/group-minus-6913601-5662866.png?f=webp&w=256

**Comment by JorgenMaristuen** [comment]
Skal ikonet symbolisere "fjern gruppe" (ikke "fjerne person fra gruppe") ?
