### ISSUE TITLE
[Innspill til komponent]: <FileUpload />

### ISSUE THREAD

**Issue by lurajon** [navikt/Designsystemet#2871]
### Tilbakemelding

Hei! Takk for ett fint felleskomponent.

Vi har i dag vår egen filopplastkomponent og jeg ser for meg at vi bytter over til Aksel sin så raskt som mulig.

Vi har derimot ett ønske om å kunne gi brukeren mulighet til å endre navn på filen som er lastet opp. Slik vi har identifisert best mulig måte å gjøre det på er å endre filnavnet etter at filen er lastet opp, og da med en egen "endre" knapp i FileUpload.Item som endrer fra statisk tekst til input.

Slik jeg leser dokumentasjonen nå, ser det ikke ut til at vi har mulighet til å endre innhold i en Fileupload.Item

Jeg har sett at noen team har ett eget TextField utenfor filopplaster som setter navn på dokumentet før opplast, men vi syntes at det ble litt rart.

**Comment by KenAJoh** [comment]
Hei, har dere noen skisser eller screenshots av tiltenkt funksjonalitet? 🙏 

Vi ønsker så langt det er mulig å holde FileUpload.Item enkel uten ekstra funksjonalitet. Men vi er klar over at det er forskjellige behov for hvordan filer må vises rundt i ulike systemer (F.eks i tabeller eller datalister). Så i de tilfellene man trenger mer kompleks interaksjon vil det ofte være enklest for teamene å implementere dette selv da DropZone eller FileUploadTrigger kan brukes separat fra Item.
