### ISSUE TITLE
[Innspill til komponent]: <ToggleGroup.Item />

### ISSUE THREAD

**Issue by perkynades** [navikt/Designsystemet#2898]
### Tilbakemelding

I `<ToggleGroup.Item />` burde icon være en prop på lik linje med andre Aksel komponenter.

**Comment by KenAJoh** [comment]
🙌 Har det på listen over forbedringer i en evt fremtidig major versjon. Helt mega med forslag til API-forbedringer, så bare å komme med flere hvis man kommer over noen etterhvert 🙏 
https://github.com/navikt/team-aksel/issues/391
