### ISSUE TITLE
[Tilbakemelding på ikon]: Uskarphet i Files-ikoner

### ISSUE THREAD

**Issue by ivoiv** [navikt/Designsystemet#2901]
### Tilbakemelding

Jeg føler at ikonene i Files-kategorien er ganske uskarpe, i hvert fall på Mac i Chrome, særlig når man ikke er zoomet inn.
Dette blir skikkelig vanskelig å demonstrere fordi Github komprimerer bildene som lastes opp, men Imgur ser ut til å være et hakk bedre.
Data Transfer ikonene er for meg veldig skarpe, mens jeg føler det er en slags "blur" rundt Files.
De er veldig anstrengende å se på, jeg merker det godt på øynene.

https://i.imgur.com/cwqN76x.png

**Comment by KenAJoh** [comment]
Lukker denne som wontfix da vi ikke har klart å replikere dette på Mac. Det kan være noen instanser der SVG blir rendret ulikt basert på render-engine og skalering, men vi har ikke noen flere henvendelser om at dette er et problem med dagens ikonpakke 🤞
