### ISSUE TITLE
[Figma] Padding i kode vs Figma: <Modal />

### ISSUE THREAD

**Issue by Trent-NAV** [navikt/Designsystemet#2904]
### Tilbakemelding

Utvikler kommuniserer at han kun har en size versjon av Modal tilgjengelig i React og den har 24px padding globalt, utover dette har vedkommende tilgang på de samme size props'en som jeg har i Figma for de enkelte innslagene i komponentet. Samtidig har Figma versjonen både Small og Medium versjon der Small har **16px** padding globalt. Når jeg bruker Figma small versjonen i prototypene så kjenner ikke utvikler igjen disse padding verdiene fra sitt React miljø og det blir litt sync issues. Kanskje kodet versjon burde synces med Figma versjonen? Eller er det noe utvikler ikke har oppdaget?

**Comment by sjur-gr** [comment]
Vi får ut en oppdatering snart 👍

**Comment by KenAJoh** [comment]
Modal har nå en `size="small"` i kode som oppdaterer padding 🚀
