### ISSUE TITLE
[BUG] Mulig feil i typen til Modal

### ISSUE THREAD

**Issue by ivoiv** [navikt/Designsystemet#2907]
## Hva er feilen/problemet?

Siden 6.0 har det kommet følgende endring.
"Hvis du bruker propen open må du også bruke onClose for å holde lokal state oppdatert."

Dette skaper problemer når man bygger videre på Modal komponenten.

```tsx
type MyModalProps = Partial<ModalProps>
const MyModal = (props: MyModalProps) => <Modal {...props} />  // `Property 'onClose' is optional in type '...' but required in type '...'`
```

```tsx
type MyModalProps = Omit<ModalProps, "onBlur">
const MyModal = (props: MyModalProps) => <Modal {...props} />  // `Property 'onClose' is optional in type '...' but required in type '...'`
```

Dette gjelder uansett om man bruker `Partial`, `Omit`, eller andre "modifiers". Alle forsøk på å ha en modifisert variant av ModalProps gir utslag på feilen, selv om proppen som fjernes ikke er noe viktig.

Hadde vært fint å kunne fikse denne.

## Eksempel/Tilleggsinformasjon (valgfri)
CodeSandbox sier `JSX element type 'Modal' does not have any construct or call signatures.typescript(2604)` så jeg måtte lage eksemplet i TS Playground. 
Du må kanskje legge til `@navikt/ds-react` i `Plugins` fanen oppe til høyre.

[TypeScript playground](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAJQKYEMDGMA0cDecCuAzksgGZwC+cpUEIcARFKhgwNwBQoksucAQhAAmATwAyEAHYBzbP3wwYU7AFlhKADar1GgAq0whStVr0GAAUkoAbsADWMAPRDCAWmboY7DhzRTC8ACiAB4o4BpIcAC8cAAUYAaEAFxwAPIgwDAAPGpCmvoQhtgMUvwa+FAMAHwAlNFVuBxwcH6SAXDM5DFEJEikWQASACoqYgAiwJoQ0oERIEiSMFWxkvgaGjWcTR1IMBWScdvNWULA1i0aKISEAHJhSFEMYCKuAIwAbNVHzXBZ8opSOBSADCGmAaDsURwsTqUQanQAdGgKsxFgB+BGEAAWEAA7rlNDCKFUAKNgSSREA6LKOf5KSRVHw-H45HQ7UhQzpULGoIRIKBQvA8lCnGQpBipaz8wh2KDAUheShUHAI1UJQqEYnfZmsvIaBGCUSM5km36G8RSaTG00m4FrMAoOCaYAAR3wwDABHgyLAwDyMBQ8EuACNoPh6BlJKA4G7gEYkME4MADs63SgEXAAIru7U25NoP1+-CLOBCCAaaCliBOoRejMASUkBdOQmL8CQwCIVNrkggASg+FrfOIA5LrbjudNIbDIAzBT9C3gKAUkWRGgdMfdcF7-cHcClYKXp19hHByekcEjoARk9t-iQaaXYLTTpXVYrUCrcFP8AkzHoUanpe5aHvuSCHhmACCz74Cgt7Mgm-IFgGMDAICvYHFeEbJtGDpyoGFTfm2cDTgO9AeoQ4Y3jaJohEhmSBmhBw7jAA61kg7SkeGl4oNIVjbuhgKprBm7AHAHHENRNG-LSwgWjI1qmjSBL6uaikmrqmgIgAYhAEAwPy6lKXSgIwCIYAPAwwYKPSDBApIoLgpC0KwvCfRIiii4YmgFbEESRk2vooAAGdQPBMkmQy4V-DZUjhc0ZkWY81kApIDDxfuKD4YsjzEK0eRQCI6XST8IJghCUIwvU7IeVAqIwN5vlIES4UBaaADKSB2MWQihdFtKxVFJUxalGWJZZKW2Rl1hZZMOUMAZsCTIVxUlfZjkVS51WIsidVeUiTUtSVbUmkM-KoX1w0DalJ3KToOl6YtAV3Xq6k0qc1jWpsHAUFsCY8PAfKkMuGhBKE4RIJwQA)

**Comment by KenAJoh** [comment]
Har testet litt forskjellige løsninger og finner ingen som vil ignorere alle "conditional"-typene ModalProps kommer med. Vi har valgt å ta i bruk mer komplekse typer fremover for å sikre at komponentene er riktig implementert for tilgjengelighet og funksjonalitet i noen tilfeller. Hvis det ikke er noe typescript smartnes vi ikke er klar over (som det sikkert er 😅) er dette ikke noe vi blir å fikse på vår side da det gir flere fordeler vs ulemper. 

I de tilfellene som eksemplet i ts-playground vil vi anbefale å bygge opp egne spesifikke typer, ovenfor å legge på en `Partial` rundt komponenten. Så f.eks: 

```ts
type MyNewModalProps = {
    children: ModalProps["children"];
    "aria-label": ModalProps["aria-label"];
}
```
