### ISSUE TITLE
Font weight utvidelse

### ISSUE THREAD

**Issue by Trent-NAV** [navikt/Designsystemet#2934]
Foreslår å utvide type weight hierarkiet da Windows forskjellen mellom Regular og SemiBold er moderat med Source Sans Pro. Dette fremstår nok mer utfordrende med tall enn med tekst. På Mac rendres SemiBold mye tykkere men det hjelper ikke saksbehandlerne som alle er på Windows. 

## Hva løser dette?
Når vi feks. opererer med "used/unused state" i vår tabellkontekst trenger vi større vektdifferanse enn det strong stilen gir. 

## Eksempler/Info
Ny vektstil for bold kunne vært mappet som extra strong for å følge opp strong. 

![type weight](https://github.com/navikt/aksel/assets/86958516/b15cabe4-4051-421d-be23-738b2cf15e60)

PS: [Source Sans 3](https://fonts.google.com/specimen/Source+Sans+3/tester) har variable støtte for weight axis (wght), da kunne man justert dette trinnløst uten fontvekt stiler - har dere vurdert en upgrade?

**Comment by JorgenMaristuen** [comment]
Som en del av arbeidet med nye produktsidemaler for nav.no, jobbes det også med en generell oppdatering av typografi. Her ser vi blant annet på å øke kontrasten mellom Regular og Semibold, ved bruk av egendefinerte vekter av Source Sans 3. Vi kommer derfor ikke til å tilføre nye stiler nå, før slike oppdateringer er tatt inn i Aksel.

PS: Vi bruker allerede Source Sans 3 i kode, men har ikke "døpt den om" enda pga det vil bli en major update. Når dette skjer skal den også innføres i Figma-biblioteket.
