### ISSUE TITLE
[Innspill til komponent]: Select variant med icon-only

### ISSUE THREAD

**Issue by Karroholm** [navikt/Designsystemet#2935]
### Tilbakemelding

Ønsker en select-komponent med ikon for interne flater. 

Usecase er texteditor med lite plass, og ønsker en dropdown for alternativer av formatering, heller enn å ha inn mange knapper. Fint om den også har styling-alternativ uten stroke (lik en tertiary button). 

Bilde som illustrerer usecase:
<img width="784" alt="image" src="https://github.com/navikt/aksel/assets/131680187/4d1e404f-90c1-4281-9ece-41c27949ab08">

P.S. Ikonet i bildet trengs også 🫣

**Comment by sjur-gr** [comment]
Vi snuser på en komponent som passer den situasjonen inspirert av [Dropdown Menu](https://www.radix-ui.com/primitives/docs/components/dropdown-menu), men vi har ikke noe tidspunkt for den ennå. I mellomtiden anbefaler vi [Dropdown](https://aksel.nav.no/komponenter/core/dropdown).

**Comment by KenAJoh** [comment]
Hei, vi lanserte nylig [ActionMenu](https://aksel.nav.no/komponenter/core/actionmenu)-komponenten som vi tror kan fungere bra for denne casen 🤞
