### ISSUE TITLE
[Innspill til komponent]: <Link /> Forslag om justert understreking

### ISSUE THREAD

**Issue by solhell** [navikt/Designsystemet#2944]
### Tilbakemelding

Standard understreking reduserer lesbarheten for en del lesere. Dette gjelder for eksempel brukere med enkelte former for nedsatt syn, der linjen oppleves å flyte sammen med bokstavene. For brukere med dysleksi kan linjen være forstyrrende for gjenkjenning av bokstavformen ettersom det blir overlapp mellom linjen og bokstaver som g, j og y.

Forslaget mitt er å endre til f.eks.
text-underline-offset: 5px;

Så må det selvsagt sees i sammenheng med linjeavstanden, slik at understrekingen ikke oppleves å være del av noe på neste linje, men slik denne er satt opp per nå opplever jeg ikke dette som en utfordring.

Vil i samme slengen kommentere på at i eksempelet på Accordion-komponenten har dere ikke brukt deres egen Link-komponent, da lenken inne i accordion mangler understreking: 
![image](https://github.com/navikt/aksel/assets/20128085/7b47f7e4-6436-48bc-bc42-3e0c14f62ce7)

**Comment by KenAJoh** [comment]
Hei 👋 Takk for innspill! Vi har en oppgave på å utbedre Link-komponente vår her: https://github.com/navikt/team-aksel/issues/378, så vi håper dette er noe vi får prioritert etterhvert 🤞 

Når jeg sjekket eksemplet nå for Accordion er det underline på lenke, men kan hende vi har oppdatert eksemplet nylig.
