### ISSUE TITLE
[Innspill til komponent]: <Chat /> Savner aria-live

### ISSUE THREAD

**Issue by solhell** [navikt/Designsystemet#2945]
### Tilbakemelding

Nå man har en chat gående, er det sannsynlig at man samtidig navigerer i nettstedet forøvrig, for eksempel fordi man hadde flere oppgaver man skulle løse eller fordi chat-dialogen krever at man sjekker ut en del ting. 
Når det da kommer en ny melding fra chat, må man gjør en vurdering om man skal gå tilbake til chatten og legge igjen ny beskjed eller fortsette å navigere. For skjermleserbrukere er det ikke nok med lydsignal om at det er kommet en ny chat-beskjed, de vil også trenge å få lest opp beskjeden for å gjøre denne vurderingen. Samtidig er det sannsynlig at det er mer krevende for dem å navigere tilbake til chatten, så det er enda viktigere for dem å kunne gjøre denne vurderingen uten å måtte aktivt navigere seg dit.

Jeg savner derfor `aria-live`-attributtet på chat-regionen, fortrinnsvis med verdien `polite` dersom det er et lydsignal som varsler om ny melding, alternativt `assertive` dersom det ikke er lydsignal.

**Comment by it-vegard** [comment]
Hei og takk for tilbakemelding!

Denne komponenten er utviklet i utgangspunktet bare for å vise meldinger som sendes asynkront, uten live oppdateringer, for eksempel kommunikasjon om en sak. Chat-navnet er altså litt misvisende. Den tar bare for seg det visuelle uttrykket, og ikke live-funksjonalitet, som gjerne kunne være en del av applikasjonen som bruker den.

Tilfeldigvis sto denne komponenten på agendaen til ukens dokumentasjonsmøte, og vi har nå ryddet litt i teksten for å gjøre det tydeligere hva den er egnet til.

Vi har drodlet litt om å legge til en wrapper-komponent som kunne håndtert nettopp live-opplesing, men siden vi ikke kjenner til noen team internt her som har det behovet per nå, så er det sannsynligvis ikke noe som kommer med det første.
