### ISSUE TITLE
[Innspill til komponent]: <Combobox />

### ISSUE THREAD

**Issue by Watercolours** [navikt/Designsystemet#2953]
### Problemstilling

Det er ikke mulig å søke i _hele_ tekststrengen. Pga. bruken av `.startsWith`, må søket matche fra første bokstav i ordet/setningen. 

Eksempel fra demo, som ikke fungerer i dag: 

<img width="622" alt="Screenshot 2024-05-24 at 08 58 09" src="https://github.com/navikt/aksel/assets/1224956/ef08cf0e-1908-4b05-bc69-749d8f1d39a7">

<img width="593" alt="Screenshot 2024-05-24 at 08 58 15" src="https://github.com/navikt/aksel/assets/1224956/78727aad-bea4-460b-a096-27212e2f462f">

----

### Ønsket resultat

At man får treff på alle tilfeller av `"jedi"`.
I demoen burde dette gitt to resultater: `Return of the Jedi`, og `The Last Jedi`. 

----

### Forslag til mulige løsninger

`filtered-options-util.ts`

#### Variant som matcher med `startsWith` på hvert enkelt ord i setningen

```
const isPartOfText = (value: string, text: string) =>
    normalizeText(text)
        .split(" ")
        .some((s) => s.startsWith(normalizeText(value ?? ""));


isPartOfText('return', 'Return of the Jedi')  // true
isPartOfText('turn', 'Return of the Jedi')    // false (matcher kun starten av ord)
isPartOfText('jedi', 'Return of the Jedi')    // true
isPartOfText('jed', 'Return of the Jedi')     // true
```

#### Variant som matcher "alt", uavhengig av om det er start, midten, eller slutten av ordet

```
const isPartOfText = (value: string, text: string) =>
    normalizeText(text).includes(normalizeText(value ?? ""));


isPartOfText('return', 'Return of the Jedi')  // true
isPartOfText('turn', 'Return of the Jedi')    // true
isPartOfText('jedi', 'Return of the Jedi')    // true
isPartOfText('jed', 'Return of the Jedi')     // true
```

**Comment by it-vegard** [comment]
Vi har nå merget denne featuren, og den slippes i neste versjon av Aksel. Vi har en del andre issues som skal merges nå også, men forhåpentligvis kan vi slippe den i starten av neste uke.
