### ISSUE TITLE
[Innspill til Figma komponent]: <Modal />

### ISSUE THREAD

**Issue by Trent-NAV** [navikt/Designsystemet#2956]
### Tilbakemelding

Modal mangler Danger button i Figma versjonen men utvikler melder å ha tilgang på Danger i kodet versjon. Ser samtidig at Modal er omtalt uten Danger i dokumentasjonen, så det virker til å være en mismatch her?

**Comment by sjur-gr** [comment]
Det er bare å swappe f.eks. primary-knappen med danger. Vi vet ikke om noe pattern som bruker danger-knapp i modal, ennå. Del gjerne så kan vi vurdere om det er noe vi tar inn i dokumentasjonen. Samtidig er nok dette en del av naturlig frihet i teamet ditt basert på deres behov.

**Comment by Trent-NAV** [comment]
@sjur-gr Danger er ikke del av button variantene i button group i Modal og det er ikke swap anordning for elementet? Eneste muligheten jeg ser er å gjøre en detach. Til info har vi destructive style handling som kvitteres ut i modal i sammenheng med slettehandlinger.

![oppgaveliste_slett](https://github.com/navikt/aksel/assets/86958516/7dedb9e1-2fe7-404f-8720-1a9f3b1eb7b3)
