### ISSUE TITLE
[Innspill til komponent]: <Box  />

### ISSUE THREAD

**Issue by perkynades** [navikt/Designsystemet#2963]
### Tilbakemelding

Skulle ønske var mulig å sette statiske bredder eller høyder til en `<Box />`, og da gjerne at bredden og høyden er sine egne design tokens.

Vi har en del steder i koden der vi må lage helt egne komponenter fordi  `<Box />` ikke har støtte for å sette statisk bredde og noen steder blir det problematisk at bredde blir satt til 100%

**Comment by KenAJoh** [comment]
Dette er noe vi ser på nå 🎉 
https://github.com/navikt/aksel/pull/2842

Vil da få en ganske lang rekke med nye props:
```
  width,
  minWidth,
  maxWidth,
  height,
  minHeight,
  maxHeight,
  position,
  inset,
  top,
  right,
  left,
  bottom,
  overflow,
  overflowX,
  overflowY,
  flexBasis,
  flexGrow,
  flexShrink,
```

**Comment by perkynades** [comment]
En ting til @KenAJoh når jeg først har tankene på `<Box />`, kunne det kanskje være mulig å tenke annerledes når det kommer til propsa for `padding`. Istedenfor å ha `paddingBlock` og `paddingInline` så har man kun `padding` der man setter padding på samme måte som med CSS regelen

**Comment by KenAJoh** [comment]
@perkynades

Tenker du f.eks slik som dette da?
```
<Box padding="2 3 4 5" />
```
Vi tenkte først å gjøre det slik, men på grunn av typene blir det for komplekst for typescript å håndtere 🙁 

<img width="918" alt="Screenshot 2024-05-29 at 13 58 44" src="https://github.com/navikt/aksel/assets/26967723/a80a5f05-9e05-48c5-934a-85da2d71e187">

**Comment by perkynades** [comment]
Akuratt sånn ja, ahh det var synd. Kanskje heller gi litt annen navngivning: `verticalPadding` og `horizontalPadding` istedenfor. Sliter med å forstå hvilken retning `paddingBlock` og `paddingInline` går, men det kan bare være jeg som blir forvirret enkelt 😛

**Comment by JulianNymark** [comment]
@perkynades Vi hadde faktisk det i første iterasjon av design her, men så tenkte vi å følge spec navn nærmere, hvor `inline` og `block` er mer semantiske spacing verdier:

> ... depending on the element's writing mode, directionality, and text orientation.

(fra https://developer.mozilla.org/en-US/docs/Web/CSS/padding-block)

Så de er kanskje litt confusing å pugge _enda_ et set med CSS konsepter (i forhold til noe rett fram som `vertical...` og `horizontal...`), men heldigvis er de ganske etablerte standarer nå, og er på en måte "bedre" 😅 (de respekterer en litt mer dynamisk og "levende" DOM)

**Comment by perkynades** [comment]
Aha @JulianNymark så det er `padding-block` og `padding-inline` som er hva CSS'en reglene heter, da er jeg enig i at det blir mye mer riktig å følge det enn å pushe på vår egen standar

**Comment by KenAJoh** [comment]
I 6.12 kan man nå bruke de nye props-ene 🎉 
https://aksel.nav.no/komponenter/primitives/box#bf34bbac5fbe
