### ISSUE TITLE
[Innspill til komponent]: <Modal />

### ISSUE THREAD

**Issue by navperbirg** [navikt/Designsystemet#2964]
### Tilbakemelding

Jeg synes Modal-komponenten er bra, men jeg lurer på hvordan jeg kan lukke komponenten og unmounte den samtidig.

**Comment by HalvorHaugan** [comment]
Hei! [Her er iallfall én måte å gjøre det på](https://aksel.nav.no/sandbox/index.html?code=N4Igxg9gJgpiBcJgApkEoAEBeAfB4AOgHYYaREDOALhgKIAeAhgLYAOANjNhutnoSVJkIlGgCcYAM24AlGIzBUAdAFcKMOZOREV7dmgDcxIcNEYA2hQAWEAO4BZaI3YAaDOqoBlGw6fsAurLyiqrqnlSMVDDIks7qhsTGQhJUKmIkyEkmADxQAJYAbmTsjBQUAHIsMFgEIKwAngC0AIwAbLU4WSYY2QBCKlRUIhgiAMLseWAA1lgomLjuMF4%2BjlDOyFRiKjBoAL44AKOsRFzMftkA9P2DIp1EXSbA1narzhgA-DwP3dmv7N-dEasGD3QSAkwSSSzSG7AHdKzyWBiWbADAIxj5IgAc3gGFqAAkYHlahhdrCweDSGN2BB1LNeAsBJTAeQKBBOEpICoiFRMiBqbSYLUEhTmYtli8-DE4jsjKLwWS4aQ7mLSL8-EpetB6jgACJLKIYGBiI0kKLUJSXP6a7Uq1XqtbsJQAMQgECiYjtqp61yGZvqwJqIAARgM-STqZMZnM%2BBhIZy0hIee9OTT1Oh9krwQAZFRTKZZnJXMO3Qs9C7W13u41e8FWvy1kyYXGZeUmWoAVSIZ25USgtThe2%2Bl3yBVrItIuzlSRSaRI2QYLA4XAuODluzQGeIIBcIFseSgVCsFAQ5maAAYAEwAFn8uyAA). I praksis vil det ofte fungere uten `useRef` også, men vær oppmerksom på at hvis du da "lukker" modalen med bare `setShowModal(false)`, så vil ikke `onClose` bli trigget.

Hvis dette ikke fungerer, kan du gjerne dele og forklare use-caset ditt så ser vi nærmere på det.
