### ISSUE TITLE
<Radio /> rendrer litt feil i Firefox om man zoomer

### ISSUE THREAD

**Issue by toresbe** [navikt/Designsystemet#2965]
### Tilbakemelding

Hvis man zoomer akkurat "feil" vil Radio-button miste noen piksler i Firefox.

Det ser ut som det er en slags avrundingsfeil - hvis man varierer horisontal størrelse på vinduet vil høyre og venstre side vekselvis bli "beskåret".

![image](https://github.com/navikt/aksel/assets/1761606/21e93e6b-48ff-459e-9393-42436ede9d98)

**Comment by KenAJoh** [comment]
Hei, etter litt etterforskning ser dette ut til å være et problem med firefox
https://bugzilla.mozilla.org/show_bug.cgi?id=1662069
Kan se bildet i bugreport at de opplever det samme: 
https://bugzilla.mozilla.org/show_bug.cgi?id=1662069

Setter denne til wontfix siden det ligger på firefox sin side
