### ISSUE TITLE
Stat og kommune

### ISSUE THREAD

**Issue by AndreaPaulsen** [navikt/Designsystemet#2997]
### Navn på ikonet

Stat / kommune

### Eksempel på ikonet

Ikon for stat og ikon for kommune. Ikonet shield kan brukes, men om vi kunne fått en variant som illustrerer kommune og en som illustrerer stad hadde det vært supert :)

**Comment by ivoiv** [comment]
Hva med å bruke Flagg-ikonet for stat?
![image](https://github.com/navikt/aksel/assets/11502345/4b7669c4-99cd-4004-b950-6545b20537e2)

**Comment by Lilyngs** [comment]
Hei @AndreaPaulsen, takk for henvendelse om ikon :)  Shield kunne for eksempel representere kommune, mens stat kunne vært en "statelig" bygning. Eller om det er andre ideer som dukker opp. Kunne du si litt om hvor ikonene skal brukes?
