### ISSUE TITLE
[Innspill til komponent]: <Pagination />

### ISSUE THREAD

**Issue by karihamnes** [navikt/Designsystemet#3015]
### Tilbakemelding

Vi bruker komponenten i en løsning med mange sider med utlisting, og der det kan være så mye som 35 sider. Vi får tilbakemelding om at det er veldig tungvint fordi man ikke får mulighet til å velge sider direkte når det blir mange sider. 

[Jeg brukte sandbox med count=35 for teste oppførselen](https://aksel.nav.no/sandbox/index.html?code=N4Igxg9gJgpiBcJgB0B2ACdAKLBKdAvAHzooabqSoDOALugKIAeAhgLYAOANjIdvsVJoKlCDXoBtDiwDmMAMq0WtGABp01GLQAKshUpUBdPgCUYLMLQB0AV02LlMLACZcAbmEUATlpteMWAA8AGoOYADW6DIsHATIIACMzvFEniKBujIAlqjKWWLo0nIEwEX6jgC%2B6GKZMADCABYsqMXAmjp6DipVkDaotCUAzACsVQBGEH1QLF4AnnWT-SUJVdRZY1w5Mgt9A8ArAPSpqGkUGbI5eQVlJWVdMFU1eo3Nre219z2LeyPji9NzHZLfardabFpAvYrDRZABeMDiIGobBYXC48SOaFOmHO2VytHyGBupU6Bge1VQtReLQRbS0HzJX12Q1G6AmUxm82%2By1BGy2kJ5MPhiKYyNR6JAmPIOIOoSUESI7jQFQ8J2l6B8tD8GECzHY3F4UswFVweGVIFUIAA7lkoLQGtQEBJBs4AAyqJIADldhgqQA), og forsøkte å komme til siden 10 - det er tungvint. Såvidt jeg finner ut må man trykke 5-6 ganger for å nå side 10, fordi man bare viser én side til høyre for den siden man står på. -  

Så lenge man kun har 9 sider funker det sånn noenlunde effektivt, men så bryter det litt sammen. 

Har dere tenkt noe på alternative måter å løse dette på for store lister med mange sider? F.eks. å kunne skrive inn sidetallet noe sted, i tillegg til å navigere med klikk? Elns? 

Man kan påvirke antall sider med hvor mange rader man viser på én side, men for noen løsninger vil dette likevel ikke løse dette problemet på grunn av datamengden.

**Comment by Lilyngs** [comment]
Har diskutert med teamet, og de skal teste ut om de kan bruke pagination slik den er, i en litt annen form. De kommer ev tilbake om de likevel trenger ekstra funksjonalitet.
