### ISSUE TITLE
[Innspill til komponent]: <FormProgress />

### ISSUE THREAD

**Issue by heyvard** [navikt/Designsystemet#3048]
### Tilbakemelding

Har implementert denne i sykepengesøknaden: https://demo.ekstern.dev.nav.no/syk/sykepengesoknad/soknader/d9ac193d-9b67-4a51-80c2-fe4289214878/1 

Synes det var ganske rett frem. Var en litt logikk rundt når de ulike stegene skulle være klikkbare osv. Typisk gitt om alt før et spørsmål var besvart eller ikke.

**Comment by KenAJoh** [comment]
Takk for demo-lenke! Kult å se den i bruk 🙌
