### ISSUE TITLE
[BUG]: Combobox sin readOnly-prop virker ikke

### ISSUE THREAD

**Issue by idaame** [navikt/Designsystemet#3049]
## Hva er feilen/problemet?

ReadOnly på Combobox-komponenten fungerer ikke. Den fungerer helt likt med readOnly=true som false. 

## Steg for å reprodusere problemet (valgfri)

Har laget et lite eksempel for å vise at det ikke har noe effekt å sette readOnly til true.
<img width="522" alt="image" src="https://github.com/user-attachments/assets/b5a23960-9e74-47ba-b889-625b74393bcd">
<img width="645" alt="image" src="https://github.com/user-attachments/assets/bf0dd233-d4b4-4acc-a7dd-4ef242230660">

## Eksempel/Tilleggsinformasjon (valgfri)

```
 Hvis mulig, legg gjerne til kode her, evt lenke til kode i repo
```

**Comment by KenAJoh** [comment]
Takk for heads-up! Vi har ikke implementert `readOnly` for Combobox enda, så readonly nå er bare "native" funksjonen i `<input />` som ikke fungerer i praksis. Vi skal få sett på å implementere den på lik linje med de andre skjemakomponentene våre etterhvert 🤞

**Comment by JulianNymark** [comment]
Tenker vi kan legge til fiks for `disabled`-prop i denne samme PRen (ganske lignende behaviour)

**Comment by idaame** [comment]
Skjønner! Når kan vi forvente at det blir fikset? Det setter en stopper for å få byttet over til combobox for oss siden vi er avhengig av readOnly-funksjonalitet 😅

**Comment by JulianNymark** [comment]
Tar denne tasken i kveld / i morgen (og burde ikke ta for lang tid, burde være klar i neste release. Blir nok en patch release siden det er en bugfix for eksisterende prop, og ikke helt en "ny feature" 🤔 ).
