### ISSUE TITLE
[NEW] Combobox, håndtere PageUp og PageDown

### ISSUE THREAD

**Issue by erik-a-e** [navikt/Designsystemet#3056]
## Hva?

PageUp og PageDown håndtering i combobox sin nedtrekksmeny

## Hva løser dette?

Raskere tastaturnavigering i nedtrekksmenyen. Mer lignende oppførsel med andre komponenter.

**Comment by it-vegard** [comment]
Beklager sein beskjed, men dette ble fikset i #3158
