### ISSUE TITLE
[Nytt ikon]: Ikon for å splitte noe (i to deler)

### ISSUE THREAD

**Issue by idaame** [navikt/Designsystemet#3058]
### Navn på ikonet

Split/DivideInTwo

### Eksempel på ikonet

I Team Baks og EF sin løsning for tilbakekreving finnes det mulighet for å dele en periode med feilutbetaling i to. Der man kan gjøre denne handlingen har vi i dag et hjemmemekket ikon, som det hadde vært veldig fint å kunne erstatte med et Aksel-ikon 🙏 Legger ved bilde av hvordan ikonet vårt ser ut. Ser for meg at noe lignenede kunne ha passet inn i stilen til Aksel, da RotateRight og RotateLeft ligner litt i stilen.

Her er hvordan vårt ikon ser ut:
![image](https://github.com/user-attachments/assets/b04f530c-2575-4667-9747-01e807b033e5)

Og fylt versjon (når man hovrer over):
![image](https://github.com/user-attachments/assets/286547d4-574c-41f1-acfc-cc4137ba9ca0)

**Comment by JorgenMaristuen** [comment]
Her er et forslag til ikon "SplitHorizontal" i Aksel-formspråk som jeg tror kan fungere til dette formålet, samtidig som det er et mer generelt symbol for å dele noe, evt også med en vertikal variant.



![Image](https://github.com/user-attachments/assets/c8e6b393-c9e1-4fbe-82f6-523d9f3ba711)

**Comment by JorgenMaristuen** [comment]
Ready for dev @KenAJoh https://www.figma.com/design/wEdyFjCQSBR3U7FvrMbPXa/Aksel-Icons?m=dev&ready-for-dev=1

**Comment by idaame** [comment]
Ser veldig bra ut 🤩

**Comment by KenAJoh** [comment]
Hei 👋 Ikonet er nå tilgjengelig i versjon 6.15.0 🚀
