### ISSUE TITLE
[Innspill til komponent]: Modal. Indikasjon på at det er mer innhold når container blir scrollable

### ISSUE THREAD

**Issue by erik-a-e** [navikt/Designsystemet#3060]
### Tilbakemelding

F.eks et pil-ikon eller en blur-effekt som som aktiveres når det er innhold under eller over viewport, som forsvinner om man har scrollet helt til toppen eller til bunnen.

**Comment by HalvorHaugan** [comment]
God idé! Dette kommer i neste versjon 🚀
