### ISSUE TITLE
[BUG] Filtreringen på Aksels God Praksis sider 

### ISSUE THREAD

**Issue by sarahbrodwall** [navikt/Designsystemet#3063]
## Hva er feilen/problemet?

Filtreringen på Aksels God Praksis sider gir en ny URL, men oppdaterer ikke nettleserens history.  Navigering med tilbake-knapp sender man tilbake til forrige side (f.eks. Aksels hovedside), ikke til forrige filtreringsstadium.  

Siden filtrering for å finne informasjon kan være en eksplorativ prosess der brukeren skal tilbake og frem, er det fint om tilbake-knappen sender man tilbake til forrige filtreringsstadium.  Dessuten impliserer ny URL en oppdatering av nettleserens historikk.

**Comment by KenAJoh** [comment]
Er selv litt splittet på denne. På en side er jeg helt enig med at ved å oppdatere browser-history vil det være lettere å raskt hoppe tilbake/frem til tidligere filtereringer når man utforsker temaet. Men på den andre siden vil dette gjøre det en del vanskeligere å raskt hoppe tilbake til tema-sidene hvis man ikke fant det man ønsket under et tema, eller bare utforsker Aksel generelt. 🤔 

Har ikke noen sterke meninger om hva som er mest rett her så tenker selv vi kan endre til å oppdatere browser-history, men skal høre med teamet om de har noen tanker først 👍

**Comment by KenAJoh** [comment]
Vi tester å beholde "history" nå, vil fungere i løpet av uken 🤞
