### ISSUE TITLE
[Innspill til komponent]: <Tooltip> UU og Axe

### ISSUE THREAD

**Issue by ivoiv** [navikt/Designsystemet#3067]
### Tilbakemelding

Tooltip setter aria-describedby på sine barn kun når den er aktiv - dvs mens man hovrer over elementet den beskriver. Det liker ikke AXE når denne komponenten ikke har noe beskrivende tekst selv.

F.eks.
````
<Tooltip content="Klikk her">
   <Button 
        as="a"
        href="https://www.nav.no"
        icon={<NavIkon aria-hidden />}
  </Button>
</Tooltip>
````

Her sier AXE at knappen ikke har beskrivende tekst, selv om den vil få beskrivelsen sin av Tooltip når man enten hovrer over den og når den får tastaturfokus. 

Å sette aria-label eller title på Button eller Ikonet fikser det, men da blir det dobbelt opp med beskrivelser. 
Er dette noe farlig, at det er potensielt to forskjellige beskrivelser?

Evt. kunne vi fikset det i selve Tooltip komponenten?

**Comment by KenAJoh** [comment]
Vi skal få sett på om det er noen forbedringer vi enkelt kanskje kan implementere her 👍 Men frem til da ser vi ikke noen store problemer med at Button har `title` i tillegg til Tooltip. Det vil kunne bli litt dobbelt opplesning for skjermeleser, men sikrer da i allefall at knappen er tilgjengelig.

**Comment by KenAJoh** [comment]
Hei, dette skal være fikset i v7 nå 🚀 
https://aksel.nav.no/grunnleggende/kode/endringslogg#ec4d7c39f20f
