### ISSUE TITLE
[Aksel.nav.no - 404] brevdesign

### ISSUE THREAD

**Issue by solumstrand** [navikt/Designsystemet#3122]
Prøvde å gå til https://aksel.nav.no/monster-maler/undefined/visuelle-retningslinjer-for-brevdesign som det lenkes til fra figma, men siden finnes ikke?

**Comment by KenAJoh** [comment]
Hei, tror lenken er utdatert i figma. Du finner artikkelen her: https://aksel.nav.no/preview/monster-maler/brev/visuelle-retningslinjer-for-brev. 

Siden artikkelen ikke er publisert enda vil man bare kunne se den hvis man er logget inn på https://aksel.nav.no/admin 🤞
