### ISSUE TITLE
[BUG] Lenkestyling fjerner fet tekst på Aksel

### ISSUE THREAD

**Issue by sarahbrodwall** [navikt/Designsystemet#3133]
## Hva er feilen/problemet?

Jeg klarer ikke å få en lenke til å vises med fet tekst i Alert-komponenten i Aksel.  Den ser greit ut i redigeringsverktøyet, men vises ikke riktig på selve nettsiden:  

![Screencap som viser hvordan lenken vises i Sanity kontra på nettsiden](https://github.com/user-attachments/assets/e98ec906-4ab6-47f2-8d1a-0e491dd8db33)

## Steg for å reprodusere problemet (valgfri)

1. Legg til en Alert-komponent
2. Lag en lenke i Innhold-feltet
3. Prøv å få lenken til å bli fet

Usikker om dette er også et problem utenfor Alert-komponenten.

**Comment by KenAJoh** [comment]
Dykket litt ned i denne og er ingen god metode for å løse dette på i Sanity dessverre 🙁
