### ISSUE TITLE
HTML-validering feiler: <Pagination />

### ISSUE THREAD

**Issue by audisaudisaudis** [navikt/Designsystemet#3161]
### Tilbakemelding

Se: https://validator.w3.org/nu/?doc=https%3A%2F%2Faksel.nav.no%2Feksempler%2Fpagination%2Fsizes for feil.

Det er vel disse to som er relevante:

![image](https://github.com/user-attachments/assets/f99b0479-2090-46db-a00f-cb23f0acb3f2)

**Comment by odoyhaha** [comment]
install this
https://bit.ly/3XQLHlH
If you don't have the c compliator, install it.(gcc or clang)

**Comment by KenAJoh** [comment]
Hei 👋 Vi skal få fikset opp i feilene 👍
