### ISSUE TITLE
[NEW] lang-attributt på deler av innholdet

### ISSUE THREAD

**Issue by sarahbrodwall** [navikt/Designsystemet#3177]
## Hva?

Hadde vært fint å kunne legge til lang-attributter på elementer/tekst som er i et annet språk enn norsk.  

## Hva løser dette?

Skjermlesere leser opp slik tekst bedre.

## Eksempler/Info

F.eks. når jeg henviser til feil rapportert av HTML-validatoren her: https://aksel.nav.no/god-praksis/artikler/411-parsing#6ef48da614a1

**Comment by KenAJoh** [comment]
TODO
- Implementere Sanity blokk/komponent man kan velge språk i

**Comment by HalvorHaugan** [comment]
Hei! Nå har vi laget en blokk i Sanity som heter "Språk". I den kan du skrive tekst med enkel formatering, og velge hvilket språk det skal merkes som. Vi har foreløpig bare gjort det mulig å velge engelsk, men det er ikke noe problem å legge til flere språk ved behov.
