### ISSUE TITLE
[Innspill til komponent]: combobox i størrelse extra small

### ISSUE THREAD

**Issue by Karroholm** [navikt/Designsystemet#3186]
### Tilbakemelding

Bildet sammenlikner combobox small med input field small. Ønsker oss extra small combobox til interne flater
![image](https://github.com/user-attachments/assets/78b58e20-a285-4c38-baf6-9244ee002856)

**Comment by it-vegard** [comment]
Er du sikker på at dere er på siste versjon av Aksel? Dette ble fikset i mai, i versjon 6.9.0, om jeg ikker tar feil.

Se på [eksempel i Sandbox](https://aksel.nav.no/sandbox/index.html?code=N4Igxg9gJgpiBcJgB0B2ACdAKLBKdAvAHzooabqSoDOALugKIAeAhgLYAOANjIdvsVJoK6AE4xaAV1EYsAHgBqAZVoswAa3R0AnjwLBg6AO4BLKLQAW8dMhAAWAAxgLtgDToOLKFBOoA5ta2duJsbuh%2BLByBIACMIbboAL6JRMIi6HIAqgBySgCCAGIMAPoAwhBsAEYQ1UzoXCyVMFwEtkrsFiyoUDyitNocMAkQHLQmEDT6viZjLFwA8qPjNIlaJgBeMK0g1GxzXLYA9Knk6RkAKjBMtAUmzVD1jc3b2SwAbqgJ1Btbtrv7CWOaUwckOPjeRFwAG40IkYagqHR0NNZgslhNqHwANrAmwgSpdQluXG2SLcIYgVwkkCqfwwUS%2BClU054wYsUTElm2PyiSJM6nqEymTkiWx7fwQEUUWyeajfCboABmokkMylmBljLJPHVeLovKMTVEom0utsRhYtHpbGaEzNIB5fKVKrVlLQAF14bjxFIZBlmOxyeggeRErg8LDKSBTOYLNQEFiAMwAJgcrhiyYAHA53YkgA).

**Comment by ramnav990** [comment]
Dette er versjonene vi har :) 
`"@navikt/aksel-icons": "7.1.0",
    "@navikt/ds-css": "7.1.0",
    "@navikt/ds-react": "7.1.0",`
    
Jeg har derimot blitt truffet av en annen bug lokalt, som jeg ikke klarte å gjensake i sandbox. Så jeg er egentlig veldig usikker på hva problemet er

**Comment by it-vegard** [comment]
Har dere en URL jeg kan gå inn og se på? Er dere sikker på at `size` settes korrekt?

**Comment by ramnav990** [comment]
Ser ut som jeg fant ut av problemet. La til nye versjonene uten å restarte dev server... Dette fikser nok også den andre buggen jeg trodde jeg kom over. Beklager 😅

**Comment by it-vegard** [comment]
Ingen problem! Bra dere fant ut av det!
