### ISSUE TITLE
[Innspill til komponent]: select i størrelse extra small

### ISSUE THREAD

**Issue by Karroholm** [navikt/Designsystemet#3190]
### Tilbakemelding

Ønsker oss extra small select som matcher størrelsen til exstra small button for interne flater 
<img width="881" alt="image" src="https://github.com/user-attachments/assets/fa4f2c21-bc88-4580-88aa-7adc09dff9c2">

**Comment by KenAJoh** [comment]
Hei 👋  Ønsket om skjemaelementer med størrelse `xsmall` (24px height) er noe vi har vurdert at vi ikke blir å støtte i Aksel. Dette er siden klikkflaten bare blir 24px, og siden font må justeres ned for å støtte dette. Fonten vår er i dag allerede en del mindre enn "vanlige" fonter, slik at 14 for vår font ofte kan sammenlignes med 10-12px for andre fonter. 

Button er et unntak vi gjorde for at den skulle fungere bedre i tabeller som vi nevner i dokumentasjonen
> Størrelsen xsmall er tilgjengelig for bruk i tabeller eller interne løsninger. Den bør brukes sparsomt da klikkflaten kan være problematisk, spesielt på mobil.

For eksempelet på skjermbildet ville vi anbefalt "small"-button, men hvis "xsmall" må brukes tror vi det kan fungere å bare sentrere knappene 🤞
