### ISSUE TITLE
[BUG] Tung CSS fil ved import av aksel-icons

### ISSUE THREAD

**Issue by vaarvik** [navikt/Designsystemet#3223]
## Hva er feilen/problemet?

Når vi importerer ikoner får vi en warning om at det er store filer som blir kompliert: `<w> [webpack.cache.PackFileCacheStrategy] Serializing big strings (177kiB) impacts deserialization performance (consider using Buffer instead and decode when needed)`

Antar dette er fordi det blir generert en sædeles tung CSS-fil basert på disse svarene: https://github.com/vanilla-extract-css/vanilla-extract/issues/374#issuecomment-2322632128

## Steg for å reprodusere problemet (valgfri)
1. `npm install @navikt/aksel-icons` 
2. Lag en ny `.tsx` fil.
3. `import { AirplaneIcon } from '@navikt/aksel-icons';`
4. Legg inn `<AirplaneIcon />`
5. `npm run dev`
6. Se warning som kommer i terminal

## Eksempel/Tilleggsinformasjon (valgfri)
Vi bruker Next.js. Dependencies:

```
  "dependencies": {
    "@digdir/designsystemet-css": "1.0.0-next.34",
    "@digdir/designsystemet-react": "1.0.0-next.34",
    "@digdir/designsystemet-theme": "1.0.0-next.34",
    "@navikt/aksel-icons": "^7.2.1",
    "next": "14.2.14",
    "react": "^18",
    "react-dom": "^18"
  }
```

**Comment by KenAJoh** [comment]
Hei 👋 Har dere prøvd `optimizePackageImports` ([docs](https://aksel.nav.no/grunnleggende/kode/nextjs#dd250ad8d7ae))?


```
  experimental: {
    optimizePackageImports: ["@navikt/aksel-icons"]
  }
```

**Comment by vaarvik** [comment]
> Hei 👋 Har dere prøvd `optimizePackageImports` ([docs](https://aksel.nav.no/grunnleggende/kode/nextjs#dd250ad8d7ae))?
> 
> ```
>   experimental: {
>     optimizePackageImports: ["@navikt/aksel-icons"]
>   }
> ```

Tusen takk! Denne docs-linken hadde jeg ikke sett. Beklager misforståelsen.
