### ISSUE TITLE
[Innspill til komponent]: <ActionMenu />

### ISSUE THREAD

**Issue by karihamnes** [navikt/Designsystemet#3266]
### Tilbakemelding

Vil denne finnes i small-variant?

**Comment by HalvorHaugan** [comment]
Tenker du på selve menyen eller triggeren? Selve menyen er allerede liten, så den bør ikke bli noe mindre. Hvis du tenker på triggeren, så velger du selv hva du skal bruke som trigger, så her kan du feks. bruke en Button i størrelse small.
