### ISSUE TITLE
[BUG] Comboxbox: option.label, og ikke option.value, returneres når man velger forslag med autocomplete

### ISSUE THREAD

**Issue by otenav** [navikt/Designsystemet#3286]
## Hva er feilen/problemet?

Når jeg velger et forslag i comboboxen ved bruk av autocomplete, så mottar jeg verdien fra `option.label` i `onToggleSelected`. Jeg forventet å motta verdien fra `option.value`, slik som det skjer ellers når man velger forslag med piltaster eller musepeker.

## Steg for å reprodusere problemet 
- Lag en combobox med complex options `[{value: "HJE", label: "Hjelpemidler [HJE]"}, ...osv]`
- Legg til `allowNewValues` og `shouldAutocomplete`
- Når man så velger et combobox-forslag med autocomplete, så mottar man da verdien til label i `option`-parameteren i `onToggleSelected(option, isSelected, isCustomOption)`. Dessuten er `isCustomOption` true.

## Eksempel/Tilleggsinformasjon 
[Kode som viser issuet](https://aksel.nav.no/sandbox/index.html?code=N4Igxg9gJgpiBcJgApkEoAEBeAfB4AOgHYYaREDOALhgKIAeAhgLYAOANjNhutnoSVJkIlGgG0KMTmCowoAeVZUAliIoAaDJKoBlKTBlzFKtQF1uAJRiMZAOgCuknVUazkY4kKEQlqymIAGU1sAN0Z2exh1Ty8MHxN-AEZgsIiomNJTNABuDIwAJxgqe3ySZDzSAB4oZRCcCqFKgFUAOR0AQQAxWgB9AGEIZgAjCBH6Bq9w9ggAdxaYGYA1cMiKLGAqfMiAXwmhdkYhqSwCEEWpAHMMWWZGAGtoGHyeH192DABmNFO90goACwg9nYUHa9ioEEgbE4snWmx2vzivjU63ifgotlurFQEEwuB4AliRIwByO7HgGAABgASYAQWykqTbDBiWn01I7UyU6KCYlCDkwCnslbpXnE7ZoNC7MVE5QUACywJUemkVERt3oKoMsig62AJOUzGUVApHww22lfL%2B%2BkMCmRlHWklVRntFEtVpEABUIBcLpwtbb1sg0SJNHKAzq8fUZcTwzadYivAB%2BLRFCMuhIUdy2HNO7UZ9GaENELKJoQU7Tpu2Z8oxq1CPO24zo2wAM2U7Fk%2BRxUbiGAAhFgsEiEt861ax-X3USAPTRomVGc1Op5HIxba5QTkagj9HcDxi-WM8kYU4ACQAVlJWDAjVBOPlTpoBRTzwApWinc08rxHw5SV8QEUVhWwAD-YC5lCIC4nwwF9TyAgAFRCv22H8hD-MlAJ0ABPO4YBvaCnlg%2BDTh0ABNABpVD0NITCAIQ3D8OYKQamgkiRWw8j5RovJ6JPU5OggQoQUKABaOIrgoMIiPyCg7kYVgKEIi5iJAZ9OIQzp5AsXjDxJf8BJAdp8iOZQoAoRgQjuA58igi5lJgWSOLSQD2naFCQG-PiDKwhCmjAwpNhwi4oBcyJAKabS9N-XyGNORCnIoC8RHCwUEMQ2gWhijC4qMgAhRhSiKfIQrC9S4M0058vaXSvLQnzj0AyiRBcIgqGoUCqFkNLmvkbL6to-A8sA-KIE67qYF6hD8vkHQcrokaZqKogYCGcz8kYGCKtIkB8vygBJBbhqamaNq2ihW2E%2BT7CgcqNNcmaDs6Y7%2BMAgBxLYiCICSfQwf4r3YG9OqIRh7sqx7Tneiwmhy0xNxiIKShISoGBYDguDnTcJXQaV1JAGZzKof4KAQMQPgAJgCdREgpgAOIJtiAA)

![Skjermbilde 2024-10-29 kl  09 45 42](https://github.com/user-attachments/assets/26cc92bc-3b28-4c98-9fb9-effda27605bf)

**Comment by KenAJoh** [comment]
Bør være fikset i v7.4.2 🤞
