### ISSUE TITLE
Bug: Rette tekst på introside-mal

### ISSUE THREAD

**Issue by sjur-gr** [navikt/Designsystemet#3298]
Teksten til checkbox med brukers erklæring i kodeeksemplene til infoside er feil. 
Riktig tekst er: Jeg bekrefter at jeg vil svare så riktig som jeg kan.

Dette gjelder både malen på toppen av siden og eksemplene på bunnen av siden.

**Comment by HalvorHaugan** [comment]
Er det slik at [ConfirmationPanel](https://aksel.nav.no/komponenter/core/confirmationpanel) egentlig ikke skal brukes lenger? Iallfall ikke i nyutvikling? Burde vi i så fall skrive noe om det i dokumentasjonen, samt vise til malen?
