### ISSUE TITLE
[Innspill til komponent]: <FileUpload />

### ISSUE THREAD

**Issue by frodehansen2** [navikt/Designsystemet#3347]
### Tilbakemelding

Er det meningen at klikk på label skal åpne filvelgeren? Hvis en klikker på labelen "Last opp filer til søknaden" i eksempelet på aksel, så åpnes den. Hvis en klikker på description åpnes den ikke.

**Comment by KenAJoh** [comment]
Hei 👋 Dette fungerer som forventet da Dropzone er et `input` koblet til en `label`. Så er samme interaksjon som i f.eks `TextField` [der klikk på label lar deg begynne å skrive](https://aksel.nav.no/komponenter/core/textfield#textfielddemo-medium) i `input`.
