### ISSUE TITLE
[Innspill til komponent]: <FileUpload />

### ISSUE THREAD

**Issue by frodehansen2** [navikt/Designsystemet#3350]
### Tilbakemelding

ARC Toolkit klager på at label for FileUpload.Dropzone er koblet til en usynlig input. Er dette ok, eller må det tas med i tilgjengelighetserklæringen?

Er det et alternativ å bruke andre måter å skjule input-feltet på, enn vha. display: none?

![image](https://github.com/user-attachments/assets/5d8d6496-d07e-4f94-96e7-2d23c89706bb)

**Comment by mortentollefsen** [comment]
Hei.
Kjempefint at du gir beskjed, og ikke minst at du tester så bra!
Dette trenger du ikke å rapportere! Faktisk er det gjort på denne måten for å gjøre FileUpload best mulig for skjermlesere (ved å skjule selve drop-sonen blir det mer oversiktlig, og sammenliknet med native file upload slipper du litt dobbel og forvirrende info med skjermleser). Axe reagerer ikke på dette, så jeg foreslår egentlig at vi skriver dette på at Arc missforstår litt, hehe. WCAG feil er det i alle fall ikke så langt jeg er i stand til å skjønne.
