### ISSUE TITLE
[Innspill til ikon]: SealCheckmark

### ISSUE THREAD

**Issue by toby1knby** [navikt/Designsystemet#3356]
### Tilbakemelding

Dette kunne kanskje fått en versjon der det er skjold med en hake. Sikringen er oppe / I orden, uten at det er en hengelås. Hengelåsen gjør ting "litt vanskelig". Så det jeg sier er skjold med hake = sikkert med god stemning.

**Comment by JorgenMaristuen** [comment]
@KenAJoh https://www.figma.com/design/wEdyFjCQSBR3U7FvrMbPXa/Aksel-Icons?node-id=1311-6445&t=oJRDA1dF5yFY3I1J-4

**Comment by KenAJoh** [comment]
@toby1knby Var det slikt du så for deg?

<img width="146" alt="Screenshot 2024-11-18 at 09 24 18" src="https://github.com/user-attachments/assets/1bf8a403-c834-488c-9123-c84749553075">

**Comment by KenAJoh** [comment]
Er tilgjengelig i kode da 
https://aksel.nav.no/ikoner/ShieldCheckmark
