### ISSUE TITLE
[Innspill til komponent]: <Button />

### ISSUE THREAD

**Issue by lhartvik** [navikt/Designsystemet#3382]
### Tilbakemelding

Hvis man gir denne knappen id={"reset"} i et react-hook-form hvor man benytter reset() fra useForm, så får man feilmelding "form.reset is not a function" og det virker ikke å nullstille. Forstår ikke hvorfor. Oppdaget ifm [denne committen](https://github.com/navikt/sokos-up-attestasjon/commit/e0760e17b4caa1076b5e95eca7440f14a39ce94a)

**Comment by it-vegard** [comment]
Usikker på hvorfor id-en skulle skape en feil, men knappen har ingen type. Den kan derfor tolkes som en `submit`, som kanskje lager problemer. Prøv med `type="reset"` i stedet, og `type="button"` på andre knapper som ikke skal sende inn.

**Comment by lhartvik** [comment]
Ja det er det samme med en vanlig <button> så det er vel ikke noe med denne Akselkomponenten
