### ISSUE TITLE
[BUG] CopyButton - leses opp flere ganger med VO når man klikker på knappen

### ISSUE THREAD

**Issue by it-vegard** [navikt/Designsystemet#3383]
## Hva er feilen/problemet?

Når jeg klikker på CopyButton med VoiceOver på i Chrome, så leses teksten opp mange ganger ekstra.

Forventet opplesning:

1. "Kopiert"
2. "Kopier" eller ingen opplesning (tilbake til normaltilstand)

Leser i stedet opp:
1. "Kopiert" [pause] "Kopiert Kopiert"
2. "Kopier" [pause] "Kopier Kopier"

NB: I Safari leses det ikke opp ekstra, men "Removed" leses opp først. Se gjerne på dette også. 🤔 

## Steg for å reprodusere problemet (valgfri)

1. Naviger til https://aksel.nav.no/eksempler/copybutton/demo i Chrome
2. Skru på VoiceOver
4. Naviger til knappen
5. Trykk VO + Space
6. Få opplest feil som detaljert over

**Comment by KenAJoh** [comment]
Fikset nå 👏 👏 👏
