### ISSUE TITLE
[Innspill til komponent]: <Select />

### ISSUE THREAD

**Issue by BeoPeter** [navikt/Designsystemet#3410]
### Tilbakemelding

Dette er mer generelt til hele aksel: Dette med at skjermen justerer seg ettersom hva man klikker på, for å rette fokuset til det man har klikket på er veldig forstyrrende oppførsel og fører til at jeg må bruke mer tid på å finne tilbake til der jeg var i flyten min enn jeg egentlig hadde trengt. Dere burde skru av "reset scroll position" når bruker klikker et sted i komponentlista eller på en demo-variant. Igjen. veldig forstyrrende. Gi meg kontrollen av skrollen!

**Comment by sjur-gr** [comment]
Takk for feedback🙌 Vi fikser klikk på demovariant 👍 Men klikk i komponentmenyen lurer jeg på om du kan utdype. Når du klikker på en komponent i menyen nå så sendes du til en ny side, og starter på toppen av den. Er det utfordringen?

**Comment by BeoPeter** [comment]
Hei! Nja, jeg tror problemet er hovedsakelig knyttet til at man forflyttes nedover om man velger et eksempel og skroller, og at dette bryter flyten min. Skulle gjerne beholdt scroll position selv om jeg velger forskjellige eksempler. At man blir flyttet øverst når man velger en nytt valg i venstremenyen er jo logisk, og jeg klarer ikke gjenskape det jeg opplevde i går, så mulig det var en lokal liten bug som fikset seg selv.

**Comment by BeoPeter** [comment]
Når jeg tenker meg om, så tror jeg nå at det jeg reagerte på visuelt er knyttet til at venstremenyen er statisk, og at når jeg har skrollet langt ned, for så å velge en ny komponent i lista, så reagerer jeg når skjermen flyttes opp, og den nye valgte komponenten flyttes ned, selv om man klikket et sted langt opp. prøver å illustrere med skjermbilde: 

![image](https://github.com/user-attachments/assets/c7029d1c-959a-4ff5-a535-320b3b97477d)
![image](https://github.com/user-attachments/assets/f42c8d49-b800-4715-a608-7a9050e996d7)

**Comment by KenAJoh** [comment]
Har oppdatert nettsiden slik at skjerm ikke scroller nå når man klikker for å se på ulike eksempler nå 🚀  

Har testet litt å stoppe scroll ved klikk i venstremeny, men skaper en ganske forvirrende opplevelse da alle sidene har ulikt innhold, lengde etc som fører til man uansett blir flyttet til en "annen" plass på siden. Tror derfor at det er foretrukket at man bli sendt til toppen slik at man ikke trenger å orientere seg på nytt, men vet hvor man er hver gang 🤞 

Takk for inspill, vi ønsker alltid mer feedback på hva vi kan forbedre på nettsiden 🙇
