### ISSUE TITLE
[Innspill til komponent]: <Dropdown />

### ISSUE THREAD

**Issue by BeoPeter** [navikt/Designsystemet#3411]
### Tilbakemelding

Det er litt vanskelig å se hvordan og når man skal bruke denne komponenten til forskjell fra action-menu komponenten. Ser at det skiller seg ut i at det er lenke-farger i innholdet, men utover det så kunne det vært tydeligere skille i "egnet for".

**Comment by KenAJoh** [comment]
Hei 👋 På sikt er planen at ActionMenu skal erstatte Dropdown 100%, og DropdownMenu vil da fjernes fra systemet. Vi skal få oppdatert dokumentasjonen slik at dette blir litt bedre reflektert der 👍
