### ISSUE TITLE
[Innspill til komponent]: <FileUpload />

### ISSUE THREAD

**Issue by sberbom** [navikt/Designsystemet#3412]
### Tilbakemelding

På aksel.nav.no vises `FileUpload.Item` uten bulletpoints, mens i sandbox og når man tar i bruk kode eksempelet får man med bulletpoint. Digg om dette hadde vært likt på aksel.nav.no og når man at i bruk koden fra eksempelet ☺️ 

**aksel.nav.no:**
![Screenshot 2024-11-27 at 15 15 55](https://github.com/user-attachments/assets/dd731f3a-8fbd-4c4f-a2e3-eceeb28a3422)

**Kode eksempelet i sandbox:**
![Screenshot 2024-11-27 at 15 16 10](https://github.com/user-attachments/assets/378891de-be01-4ac0-8099-29d871cf581e)

**Comment by KenAJoh** [comment]
Hei 👋 Takk for heads-up! [Har klar en fix på det vi får inn i løpet av uken](https://github.com/navikt/aksel/pull/3413). For nå skal det holde å wrappe `FileUpload.Item` i `FileUpload` for å fjerne liste-styling lokalt.
