### ISSUE TITLE
[BUG] Design Tokens - kopier-knappene har ikke unike navn

### ISSUE THREAD

**Issue by it-vegard** [navikt/Designsystemet#3450]
## Hva er feilen/problemet?

På artikkel om Design Tokens har hvert design token en knapp for å kopiere tokenet. Disse heter alle "Kopier", som gjør det vanskelig å bruke med skjermleser.

https://aksel.nav.no/grunnleggende/styling/design-tokens

- Anbefaler å endre til "Kopier \<design token\>" eller "\<design token\> kopier".

**Comment by KenAJoh** [comment]
Bør det stå f.eks "Kopier Transparent", "Kopier red-100" etc?

**Comment by it-vegard** [comment]
> Bør det stå f.eks "Kopier Transparent", "Kopier red-100" etc?

Noe sånt, ja. "\<design token\>" ble strippet vekk. Har escapet tegnene riktig nå.
