### ISSUE TITLE
[Innspill til komponent]: <Timeline />

### ISSUE THREAD

**Issue by hannelf** [navikt/Designsystemet#3457]
### Tilbakemelding

Hei,

Hvorfor blir alle periodene slått sammen til 2025?  Den eneste forskjellen er året. 

**2024**
![Image](https://github.com/user-attachments/assets/b19b600c-560a-4671-a09c-e549c7f6e080)
**2025**
![Image](https://github.com/user-attachments/assets/8ced82ae-8bab-4845-863e-d67b2d782fb2)
**2026**
![Image](https://github.com/user-attachments/assets/1dd771c3-36fb-42cd-9951-391cea8d18af)

Har dere lagt inn et konsept om nåtid i timeline? Gir det mening? Vi ønsker å vise en timeline for 2025/2026 uten å involvere nåtid (2024). 

Mvh
Hanne :)
Mattilsynet

**Comment by KenAJoh** [comment]
Hei 👋 Dette skjer siden Timeline-komponenten vår er relativt "dum" uten noen smart logikk bygd inn. I dette tilfellet betyr det at vi rett og slett endrer dato-visningen til bare år hvis timeline viser over 365 dager, ikke basert på tilgjengelig bredde eller periode for tidslinjen. 

Dette er absolutt noe vi kunne ha forbedret, så skal se om vi kan løse dett relativt lett. Hvis det ikke lar seg gjøre har vi dessverre ikke tidslinjen som prioritering nå, slik at jeg er usikker på når vi evt vil kunne få fikset dette.

**Comment by hannelf** [comment]
Hei er du sikker på at dere ikke har en bug fordi når vi sender inn dataene får vi timeline:

```javascript
[
  {
    start: new Date('Jan 1 2026'),
    end: new Date('Jan 31 2026'),
    status: 'danger',
  },
  {
    start: new Date('feb 1 2026'),
    end: new Date('feb 28 2026'),
    status: 'danger',
  },
  {
    start: new Date('mar 1 2026'),
    end: new Date('mar 31 2026'),
    status: 'danger',
  },
  {
    start: new Date('apr 1 2026'),
    end: new Date('apr 30 2026'),
    status: 'danger',
  },
  {
    start: new Date('may 1 2026'),
    end: new Date('may 31 2026'),
    status: 'success',
  },
  {
    start: new Date('jun 1 2026'),
    end: new Date('jun 30 2026'),
    status: 'success',
  },
  {
    start: new Date('jul 1 2026'),
    end: new Date('jul 31 2026'),
    status: 'success',
  },
  {
    start: new Date('aug 1 2026'),
    end: new Date('aug 31 2026'),
    status: 'neutral',
  },
  {
    start: new Date('sep 1 2026'),
    end: new Date('sep 30 2026'),
    status: 'neutral',
  },
  {
    start: new Date('oct 1 2026'),
    end: new Date('oct 31 2026'),
    status: 'neutral',
  },
  {
    start: new Date('nov 1 2026'),
    end: new Date('nov 30 2026'),
    status: 'neutral',
  },
  {
    start: new Date('dec 1 2026'),
    end: new Date('dec 31 2026'),
    status: 'neutral',
  },
]
```
**timeline**

![Image](https://github.com/user-attachments/assets/205ff53c-1bf3-4c01-8615-305cfb4196d6)

Her har vi ikke sendt inn noe data for 2024 eller 2025 men timeline holder av plass til begge to?

**Comment by KenAJoh** [comment]
Ser ut som det var en bug 🐛 [Har opprettet en PR](https://github.com/navikt/aksel/pull/3458) på det, så satser på vi får ut en fix i løpet av neste uke 🚀

**Comment by lbjornbak** [comment]
@KenAJoh Hei, vi ønsker gjerne å bruke denne funksjonaliteten i et prosjekt. Hadde det vært mulig å pushe ut denne endingen? 😬
![Image](https://github.com/user-attachments/assets/5ab38d51-f1e4-4faf-9de4-1fd2759e8482)

**Comment by KenAJoh** [comment]
Beklager at vi ikke fikk den ut tidligere 🙏 Skal være tilgjengelig i [7.8.1](https://github.com/orgs/navikt/packages/npm/ds-react/325554066) nå 🚀

**Comment by lbjornbak** [comment]
Nydelig, tusen takk 🤩
![Image](https://github.com/user-attachments/assets/4e6d4a28-dc0e-4616-a7d9-685faa582954)
